### ISSUE TITLE
Composer Versioning

### ISSUE THREAD

**Issue by oucil** [intuit/QuickBooks-V3-PHP-SDK#1]
Hi guys, we're developing a client services portal on behalf of a client that will tie into your API and serve some custom reports to their clientele.  My question is simply about composer and your versioning... I don't see any official "Releases" or tags, but I see that the current version is 2.6.  

For obvious reasons it's important to be able to test a new version before pushing it to production, but without release tags, I can't do that.  Am I missing something, or, are you able to use tagging to tag your releases so we can properly test future releases before pushing to our production branch.

Thanks.

Kevin.

**Comment by hlu2** [comment]
Hi It seems like the Composer Version is not updated correctly. Let me make a new release and see if it solves the problem

**Comment by oucil** [comment]
Thanks @hlu2 , please let me know when the release is up and I'll verify we can see it.

**Comment by hlu2** [comment]
Hi @oucil Please try to see if it worked now. I update README file and some other configurations.

**Comment by oucil** [comment]
Looks good, see the releases now, thanks very much!
