### ISSUE TITLE
Not able to install quickbooks/v3-php-sdk with PHP 7 on XAMPP with Windows 8 pro.

### ISSUE THREAD

**Issue by ajaygirijr** [intuit/QuickBooks-V3-PHP-SDK#101]
I am getting below error whenever I am trying to install quickbooks/v3-php-sdk through composer i.e 

`$ composer install quickbooks/v3-php-sdk`

Error I am getting is as below:

> [InvalidArgumentException]
> Could not find package quickbooks/v3-php-sdk in any version matching your PHP version (5.5.9.0)

I have installed XAMPP 3.2.2 with PHP 7.0

![php_version](https://user-images.githubusercontent.com/6481098/33768032-740633ce-dc4a-11e7-9d4d-b44b74f0ab64.png)

**Comment by hlu2** [comment]
@ajaygirijr 
It is composer require quickbooks/v3-php-sdk

**Comment by pranay26** [comment]
@hlu2 not able to create invoices using this. It gives CURL 60 Error

**Comment by josephzidell** [comment]
@ajaygirijr The message composer is returning indicates it sees v. 5.5.9, rather than 7.0.13. Does your `composer.json` or any of your other dependencies specify php v 5.5.9?
