### ISSUE TITLE
Invoices Not Creating

### ISSUE THREAD

**Issue by pranay26** [intuit/QuickBooks-V3-PHP-SDK#102]
There is some problem on InvoiceCreate.php here:
```
$theResourceObj = Invoice::create([
     "Line" => [
   [
     "Amount" => 100.00,
     "DetailType" => "SalesItemLineDetail",
     "SalesItemLineDetail" => [
       "ItemRef" => [
         "value" => 20,
         "name" => "Hours"
        ]
      ]
      ]
    ],
"CustomerRef"=> [
  "value"=> 59
],
      "BillEmail" => [
            "Address" => "Familiystore@intuit.com"
      ],
      "BillEmailCc" => [
            "Address" => "a@intuit.com"
      ],
      "BillEmailBcc" => [
            "Address" => "v@intuit.com"
      ]
]);
$resultingObj = $dataService->Add($theResourceObj);
```

Throwing error - 
**_Fatal error: Uncaught QuickBooksOnline\API\Exception\ServiceException: Http Status Code [400]: Request is not made successful. Response Code:[400] with body: [<?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2017-12-09T09:20:14.049-08:00"><Fault type="ValidationFault"><Error code="2500" element="Line.SalesItemLineDetail.ItemRef"><Message>Invalid Reference Id</Message><Detail>Invalid Reference Id : Line.SalesItemLineDetail.ItemRef</Detail></Error></Fault></IntuitResponse>]. thrown in D:\www\QuickBooks-V3-PHP-SDK-master\src\Core\HttpClients\SyncRestHandler.php on line 217_**

**Comment by hlu2** [comment]
@pranay26 It says, the ItemReference,  
"ItemRef" => [
         "value" => 20,
         "name" => "Hours"
        ]

Does not exist on QBO. There is no Item with Id=20 in the company. Check the items API and see what values you can use.
