### ISSUE TITLE
DataService->DownloadPDF causes PHP error when trying to download PDF for Invoice

### ISSUE THREAD

**Issue by donwilson** [intuit/QuickBooks-V3-PHP-SDK#103]
I've been trying to setup my script to download invoice PDFs but I've run into an issue.

My code:

```
$this->data_service = DataService::Configure([
	'auth_mode' => $this->auth_mode,
	'ClientID' => $this->client_id,
	'ClientSecret' => $this->client_secret,
	'accessTokenKey' => $this->access_token,
	'refreshTokenKey' => $this->refresh_token,
	'QBORealmID' => $this->realm_id,
	'baseUrl' => $this->api_uri,
]);
$this->data_service->setLogLocation(TMP_DIR);
$entity = $this->data_service->FindById([REDACTED]);
$this->data_service->DownloadPDF($entity);
```

The code above throws this PHP error:

> Warning: DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in /var/www/vhosts/[REDACTED]/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/SyncRestHandler.php on line 307

Here's the SDK's Request log:

> REQUEST URI FOR SEQUENCE ID 00032
> ==================================
> https://quickbooks.api.intuit.com/v3/company/[REDACTED]/invoice/[REDACTED]/pdf?minorversion=8
> 
> REQUEST HEADERS
> ================
> Authorization: Bearer eyJl[REDACTED]PMw
> host: quickbooks.api.intuit.com
> user-agent: V3PHPSDK4.0.0
> accept: application/pdf
> connection: close
> content-type: application/pdf
> content-length: 0
> 
> REQUEST BODY
> =============
> ` `

and here's the SDK Response log:

> RESPONSE URI FOR SEQUENCE ID 00033
> ==================================
> https://quickbooks.api.intuit.com/v3/company/[REDACTED]/invoice/[REDACTED]/pdf?minorversion=8
> 
> RESPONSE HEADERS
> ================
> Server: nginx
> Date: Wed, 13 Dec 2017 01:23:33 GMT
> Content-Type: application/pdf;charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> Strict-Transport-Security: max-age=15552000
> intuit_tid: bf65c64b-d7ce-7ce3-93f7-539ff658ae2c
> QBO-Version: 1710.850
> Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
> Expires: 0
> Service-Time: total=321, db=69
> 
> RESPONSE BODY
> =============
> `<?xml version="1.0"?>`
> 

Is this an implementation error on my end, in the SDK, or on Intuit's servers?

**Comment by ljudbane** [comment]
Hi.

It looks that your request body is empty which causes the response to also be empty. Check the value of $entity variable if it does contain invoice object.

i'm using similar code (sdk v4.0.1) and i get pdf. The only difference is that i get invoice with `$this->dataService->Query("SELECT * FROM Invoice WHERE Id = '<invoice_id>'");`

**Comment by donwilson** [comment]
@ljudbane where does it download to so I can check too?

**Comment by ljudbane** [comment]
@donwilson i use the return of DownloadPdf() function.
```
$pdfTmp = $this->dataService->DownloadPDF($invoice);
rename($pdfTmp, 'mypath/for/invoices/invoice123.pdf');
```

**Comment by donwilson** [comment]
Ah that works. Also using `@$this->dataService->DownloadPDF($invoice);` suppressed the error for me too.
