### ISSUE TITLE
 Http Status Code [0]: Request is not made successful. Response Code:[0] with body: []???

### ISSUE THREAD

**Issue by BradenBoggs** [intuit/QuickBooks-V3-PHP-SDK#105]
I have spent the majority of my morning toying with the SDK and I have yet to successfully call a single API request. I have no idea where I am messing up. I even watched the "PHP SDK for QuickBooks Online Deep Dive" video on youtube and followed along exactly.

I am trying to run the sample code in InvoiceCreate.php
I have configured my DataService information in my script with the information from my app.
```
$dataService = DataService::Configure(array(
    'auth_mode'         => 'oauth2',
    'ClientID'          => "Q0J8KVSE9vXsNnAoRGkmTYQmdX8TvY7bX2tOCHkW12o89t7eTz",
    'ClientSecret'      => "DF6E8P8WnEbDhreGSfzaYxozdAbXbg4VoIdS3stA",
    'accessTokenKey'    => 'eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..nTDUiZq0rPzemQh3izCoEw.LXU6MzMRVY1AUrxK_WUH6ZDq8OWFrpjTEOXrAkgKfuH7EnpexUn3DcI6Ivv1l51RPgKfwxJQpNriLV01qR6V0HV9WFh4ju87ldlSYGyYKcvHMuZxPXIGDXSbri1rHpoNpPK0vhI2KEJs76EIMicTKWwjehhIO-aBrxGk1ygRzfHGn7xOfPw8or_seWhpmqrIie6OY_AgxuXeBidYi7veb12xK05XfDQ1qpNrel85wAEHlxRBP6V5gDJ1TECSBd4xvY6Kmm-kfc_ANkleAxLX_ssiald-fHLfCgKH52fK0AOCd7mUmQi85XXnqDpyxrGSgXB6-7eAhtsozKH68_l9YLI8VWLF86A1jlD6tDP_Xk4q8xcLjldNW21notWcqgmE3udYcpu_XIYkwztGpZuvEr4ZAc8lZ0WFAQVcJuftxT4oaiWzbuLX4WZYjsf4wb5-9aMtvu2MMONTdhXvwMS52FcghK6FOqsvTPG3NG3Ap4epWd9FFMuoUJ_o-wyraSAAr55Q9F2QKcpjIFqBg8vbZxmTjNJeOV2ifK7ZXXbQF1fsocdDmqoZoNrPfrR3OlO_4Wicj8Shkx6aBNYGivkdeRURYHj7UeQPk_G1TOEg4Hj4qdGKhoKz8Zt1xsfgDpP8HaF65m7lf3tpv2M0EWok1_NvGumR7XV3oP9sHZHUqUJXPR3nmZX9hQw4eER-asceGkNP8sb9SZo4nsQfSqRV_vnZHdjo5RLl590ycfG4pWrbzcsJO4cL0NCQVl2ZcB97THM9ZGRyfMX4Bs8ZsWp8T_9KPVnHBn9elMenQEcJLiDMkzsURchmK7mAYN8I0rGp_Y9ocQJAihrTo3lC73ENkQ.PRqUR1btqHhpgjzRp9L0mw',
    'refreshTokenKey'   => "Q011522085268OxoIAfvoLsgJYBOkCgY6ei1pZlOWScjaT4VVi",
    'QBORealmID'        => "123145948911139",
    'baseUrl'           => "Development"
));
```

But when I run the code I get these errors.

```
Warning: DOMDocument::loadXML(): Empty string supplied as input in C:\wamp64\www\redesign\vendor\quickbooks\v3-php-sdk\src\Core\HttpClients\SyncRestHandler.php on line 307

Warning: Invalid argument supplied for foreach() in C:\wamp64\www\redesign\vendor\quickbooks\v3-php-sdk\src\Diagnostics\LogRequestsToDisk.php on line 87

Fatal error: Uncaught QuickBooksOnline\API\Exception\ServiceException: Http Status Code [0]: Request is not made successful. Response Code:[0] with body: []. thrown in C:\wamp64\www\redesign\vendor\quickbooks\v3-php-sdk\src\Core\HttpClients\SyncRestHandler.php on line 217
```

The only thing I changed was the Data Service Config so i'm not sure why I am producing these errors.

I have attached the log files
[00096-Request-1513363285-0.txt](https://github.com/intuit/QuickBooks-V3-PHP-SDK/files/1563647/00096-Request-1513363285-0.txt)
[00097-Response-1513363285-0.txt](https://github.com/intuit/QuickBooks-V3-PHP-SDK/files/1563648/00097-Response-1513363285-0.txt)

**Comment by hlu2** [comment]
Hi @BradenBoggs 
Can you do "composer update" to update to version 4.0.1? I am wondering if it is the bug on 4.0.0 that caused your issue.

Let me know if you need my help.

Hao

**Comment by BradenBoggs** [comment]
Hi @hlu2, thanks for the speedy response!

I ran "composer update" and the issue continues to persist. If you need anymore information from my end I will be glad to provide.

Thank you!

**Comment by hlu2** [comment]
@BradenBoggs Can you send your complete code to my E-mail Address? Hao_Lu@intuit.com

**Comment by BradenBoggs** [comment]
@hlu2 E-mail has been sent

Here is a bit more info from my working environment in case it might help solve the issue.
I'm using: 
Apache v2.4.27
PHP v5.6.31
quickbooks/v3-php-sdk v4.0.1

**Comment by khyatibhojawala** [comment]
Hello, I have spent so many time searching is an error, but I didn't find any error please anyone can help me with this?
Thank you

Error:
Fatal error: Uncaught QuickBooksOnline\API\Exception\ServiceException: Http Status Code [400]: Request is not made successful. Response Code:[400] with body: [<?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2019-08-02T04:48:37.097-07:00"><Fault type="ValidationFault"><Error code="6240" element=""><Message>Duplicate Name Exists Error</Message><Detail>The name supplied already exists. : Another customer, vendor or employee is already using this name. Please use a different name.</Detail></Error></Fault></IntuitResponse>]. thrown in C:\wamp64\www\quickbook\vendor\quickbooks\v3-php-sdk\src\Core\HttpClients\SyncRestHandler.php on line 214
