### ISSUE TITLE
When i am creating new Tax Rate getting error

### ISSUE THREAD

**Issue by mohit-varshney** [intuit/QuickBooks-V3-PHP-SDK#106]
I am using below code
$data["Name"] = substr($TaxdetailData["Taxdetail"]["taxcode"],0,31);
$data["Description"] = substr($TaxdetailData["Taxdetail"]["taxdesc"],0,31);
$data["RateValue"] = $TaxdetailData["Taxdetail"]["salestax"];
$data["AgencyRef"] = $TaxdetailData["TaxVendor"]["quickbooks_online_listid"];
		
$taxRateObj = TaxRate::create($data);
				
$resultingTaxRateObj = $dataService->Add($taxRateObj);
				
<Error code="500" element="Operation"><Message>Unsupported Operation</Message><Detail>Operation Create is not supported.</Detail></Error>

**Comment by hlu2** [comment]
@mohit-varshney 
You need to use TaxService to do it, not TaxRate. Check for our API reference page:https://developer.intuit.com/docs/api/accounting/taxservice
and also our sample: https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/_Samples/TaxServiceExample.php
