### ISSUE TITLE
Property LastFileDate does not exist

### ISSUE THREAD

**Issue by mohinmathakia1** [intuit/QuickBooks-V3-PHP-SDK#108]
When getting TaxAgency data, it will throw exception below file:

Property **LastFileDate** does not exist. Class QuickBooksOnline\API\Data\IPPTaxAgency in quickbooks/v3-php-sdk/src/XSD2PHP/src/com/mikebevz/xsd2php/Bind.php

**Comment by mohinmathakia1** [comment]
I am using minor version 8

**Comment by hlu2** [comment]
@mohinmathakia1 It seems it is missing in the data file. I will add it in the next release.

Thanks
hao

**Comment by mohinmathakia1** [comment]
@hlu2  Ok let me know when you update it on next release.

Thanks
