### ISSUE TITLE
Property AccountAlias does not exist - version 4.0.1

### ISSUE THREAD

**Issue by myedition** [intuit/QuickBooks-V3-PHP-SDK#109]
I'm trying to Query the accounting accounts list and both 'FindAll' and 'Query' methods are throwing me back the same exception: `Property AccountAlias does not exist`

I've been using the sample code so I don't think there's anything wrong, considering I'm able to query other resources the same way (customers, vendors, items...).
Has AccountAlias been removed in the latest version of the SDK ?

Any help appreciated ✌️

**Comment by hlu2** [comment]
@myedition It was not added, will update it on the next release.

**Comment by DinoMC** [comment]
Is there an alternate way to get a list of accounts in the current version?

Thanks
