### ISSUE TITLE
difficult to debug 404 issues

### ISSUE THREAD

**Issue by TimOgilvy** [intuit/QuickBooks-V3-PHP-SDK#11]
Apart from the fact that the API endpoints frequently return HTML despite the "accept" header being set to "application/xml" or "application/json", it really isn't fun trying to figure out why I'm getting a 404. 

In my case it was a silly mistake -  I was including /v3/ on the end of the API url, and once I dumped the URI from your library I could see it was added twice. It took a damn long time to find this tho.

Better debugging of endpoint issues would be great - and it will probably save you all a lot of time in providing support to people having problems with this SDK.

**Comment by hlu2** [comment]
I have reported a bug to QuickBooks Online Platform team. In the release after tomorrow's one,  you will see a "Test" function from dataService to give you the result of an HTTP call.  You can see the HTTP status header and body. 

Thanks
Hao

**Comment by TimOgilvy** [comment]
Thanks Hao, 

Looks like you are working hard to improve this.  Appreciate your replies!

**Comment by hlu2** [comment]
Fixed in v3.2.3, see:
"Test your OAuth settings" parts on Readme file.
