### ISSUE TITLE
Uncaught QuickBooksOnline\API\Exception\ServiceException: Http Status Code [400]: Request is not made successful. Response Code:[400] with body:

### ISSUE THREAD

**Issue by shaileshkumarcs** [intuit/QuickBooks-V3-PHP-SDK#110]
Fatal error: Uncaught QuickBooksOnline\API\Exception\ServiceException: Http Status Code [400]: Request is not made successful. Response Code:[400] with body: [<?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2018-01-08T03:44:20.887-08:00"><Fault type="ValidationFault"><Error code="2500" element=""><Message>Invalid Reference Id</Message><Detail>Invalid Reference Id : Something you're trying to use has been made inactive. Check the fields with accounts, customers, items, vendors or employees.</Detail></Error></Fault></IntuitResponse>].

  thrown in /Users/shailesh/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/SyncRestHandler.php on line 217

**Comment by hlu2** [comment]
@shaileshkumarcs It looks like something is wrong with your request body. Check if the Reference is correctly mapped.
