### ISSUE TITLE
revokeToken is not working sometimes

### ISSUE THREAD

**Issue by alex-p-crest** [intuit/QuickBooks-V3-PHP-SDK#111]
I have used the revoke token function as below,

    $ds = Ds::Configure([
        'auth_mode' => 'oauth2',
        'ClientID' => config('client_id'),
        'ClientSecret' => config('client_secret'),
        'accessTokenKey' => 'access_token',
        'refreshTokenKey' => 'refresh_token',
        'QBORealmID' => $qbCompanyId,
        'baseUrl' => config('quickbooks.baseUrl')
    ]);

    $OAuth2LoginHelper = $ds->getOAuth2LoginHelper();
    $access_token = ($OAuth2LoginHelper->getAccessToken())->getAccessToken();
    $OAuth2LoginHelper->revokeToken($access_token);

this code works sometimes and sometimes produces error something like below,

    ServiceException {#540 ▼
        #message: "Revoke Token failed. Body: []."
        #code: 429
        #file: "C:\MAMP\htdocs\siyea2.0\vendor\quickbooks\v3-php-sdk\src\Core\OAuth\OAuth2\OAuth2LoginHelper.php"
        #line: 281
        trace: {▶}
    }

**Comment by hlu2** [comment]
@alex-p-crest alex, it looks like a Quickbooks Online OAuth server issue. They are upgrading their server so you may receive an error sometimes. Hope it is not happening any more. In the next release, refreshToken() method and revokeToken() method will be static, it is not very user friendly now,

**Comment by mayankvadiya** [comment]
After revoke token this function is return 1 instead of  new revoked token, How can I get new revoke token ?
