### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by AliceMakk** [intuit/QuickBooks-V3-PHP-SDK#112]
Hello there,

There is the variable $tmpXML which might be undefined.
It would be good to assign it somewhere before Line:804 in DataService.php.

Thank you.

**Comment by hlu2** [comment]
@AliceMakk Thanks, I will initialize it on the code

**Comment by challgren** [comment]
I'm getting Notice Error: Undefined variable: tmpXML in [/home/atxliquor/Vendor/quickbooks/v3-php-sdk/src/DataService/DataService.php, line 947]
