### ISSUE TITLE
Atachment not deleted

### ISSUE THREAD

**Issue by xyzgd** [intuit/QuickBooks-V3-PHP-SDK#121]
I want to delete attachments. I have used code of purchase delete but still attachments not deleted, please help..

**Comment by hlu2** [comment]
@xyzgd it will be different code. We didn't provide the an object wrapper so you have to construct your own object to do it. I will provide a working example later.

**Comment by hlu2** [comment]
Here is the example: https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/_Samples/DeleteAttachment.php
