### ISSUE TITLE
DOMDocument::loadXML(): Start tag expected, '<' not found in Entity

### ISSUE THREAD

**Issue by mohinmathakia1** [intuit/QuickBooks-V3-PHP-SDK#123]
When i fetch AccountList report data, it will give me error:

DOMDocument::loadXML(): Start tag expected, '<' not found in Entity

Getting Error from below file
quickbooks\v3-php-sdk\src\Core\HttpClients\SyncRestHandler.php:307

Error getting after SDK updation of latest version 4.0.2

**Comment by hlu2** [comment]
It is a typo in the sdk. Fixed.

**Comment by mohinmathakia1** [comment]
@hlu2 Updated latest sdk but it's not fixed.

**Comment by mohinmathakia1** [comment]
@hlu2  Thanks
I got SDK update today and solved problems.
