### ISSUE TITLE
cURL Error Number:[28]

### ISSUE THREAD

**Issue by xyzgd** [intuit/QuickBooks-V3-PHP-SDK#126]
Fatal error: Uncaught QuickBooksOnline\API\Exception\SdkException: [0]: cURL error during making API call. cURL Error Number:[28] with error:[Operation timed out after 0 milliseconds with 0 out of 0 bytes received] thrown in quickbooks-oauth2/v3-php-sdk/src/Core/HttpClients/CurlHttpClient.php on line 122

I got this error some time, I can't able to find solution, please help..

**Comment by hlu2** [comment]
@xyzgd It is a proper respond. Sometimes QuickBooks Online Server is busy, so the respond time to a request is too long. To avoid long waiting time, we terminate the request from client side.

When you see this error, just retry at a later time.
