### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by xyzgd** [intuit/QuickBooks-V3-PHP-SDK#128]
1. How to add new payment method?
2. How to add card details?

**Comment by hlu2** [comment]
@xyzgd Intuit has two APIs, accounting API and Payment API. The V3 PHP SDK is only support Accounting API rightnow. If you are referring to the payment API, unfortunately, it is not supported right now.

**Comment by mashiox** [comment]
I ran into this limitation today, too! Are there plans to add Payment API support to the PHP SDK; is there a preferable way that the project would like to see support for the Payment API? 
Should I copy the patterns from the Accounting portion of the SDK?

**Comment by hlu2** [comment]
https://github.com/intuit/PHP-Payments-SDK
