### ISSUE TITLE
How can i get user profile info from API?

### ISSUE THREAD

**Issue by samktest** [intuit/QuickBooks-V3-PHP-SDK#131]
I need the user profile information. For example, who is currently logged in? By pulling his Name and Email on our web app.This functionality needs to be provided by the API developer.

**Comment by hlu2** [comment]
@samktest Unfortunately, our API does not provide such functionalities. I think this is a good use case, can you make a request here:https://intuitdevelopergroup.uservoice.com/forums/182764-intuit-developer-group/filters/top? I will vote for it.
