### ISSUE TITLE
CreditMemo not being Voided on QuickBooks

### ISSUE THREAD

**Issue by vfranchi** [intuit/QuickBooks-V3-PHP-SDK#133]
I'm trying to void a CreditMemo on QuickBooks but it's not working. The API is returning true, which for me I'm logging a success. But when I go to QuickBooks, the CreditMemo is not voided.

```
$CreditMemo = $this->dataService->Query("SELECT * FROM CreditMemo WHERE Id = 'XXX'");
$CreditMemo = $CreditMemo[0];
if ($this->dataService->Void($CreditMemo))
{
    self::log("success", true);
}
else
{
    $error = $this->dataService->getLastError();
}
```

`$this->dataservice` is defined on the class constructor:
```
$dataService = DataService::Configure([...])
```

**Comment by hlu2** [comment]
@vfranchi  The Operation Void for CreditMemo is not supported for Quickbooks Online. However, there is a typo on dataService class for Void operation, and it results a 200. I have updated the code and make a patch. Please updated the SDK and try again.

Thanks
Hao
