### ISSUE TITLE
How do we use IPPSalesFormsPrefs to update ETransactionPaymentEnabled

### ISSUE THREAD

**Issue by adsherpa** [intuit/QuickBooks-V3-PHP-SDK#135]
I would like to see a use case api example for updating `ETranssationPaymentEnabled = true` to use 
`IPPInvoice->AllowOnlineCreditCardPayment = true` when creating and sending Invoice to customer.

**Comment by adsherpa** [comment]
Hi @hlu2 
Can you look into this and let me direct into a path that would help me.
We are processing large amount of invoices per month and having to go online to send these invoices manually is quite work. This would really help if you can direct me to a solution or work around. Thx.

**Comment by hlu2** [comment]
@adsherpa 
If you want to use API to send Email for invoice, here is the example: https://intuit.github.io/QuickBooks-V3-PHP-SDK/quickstart.html#sending-e-mail

**Comment by adsherpa** [comment]
@hlu2 
Thank you for the response, yes I have been using api to send invoice via email. Problem is that when sending invoice via email using api, user receiving the invoice is not getting the options to pay payment online. setting AllowOnlineCreditCardPayment = true has no effect via api.

Was wondering if I am missing any other calls to have this option enabled. I can't seem to find example in api documentation.

**Comment by hlu2** [comment]
@adsherpa 
I don't think that fields are currently recognized by "?SendInvoice" API. I might need to create a story for it. Let me check with the team.

**Comment by adsherpa** [comment]
Cool! that would be awesome and thank you again for looking into this.

**Comment by adsherpa** [comment]
@hlu2 Any timeline on this? Please do let me know if you have roadmap listed for this api call.
We heavily depend on this to be automated. 
Thank you,

**Comment by hlu2** [comment]
@adsherpa 
The team seems like have maximized their workload recently. I couldn't get an estimate from the team. I have marked your request together with another request that "Provide Address in BillPayment api endpoint" to a higher priority queue. Hope they will work on it soon.

Sincere this is non PHP SDK related, I will close this issue. 

Thanks
Hao

**Comment by adsherpa** [comment]
Hello @hlu2 
I know this thread is closed but I wanted to ping back to see if you have any status on that request.
Also you mentioned you have added my request with "Provide Address in BillPayment api endpoint".
Can I get that request list link so I can monitor that?
I did search in git issues and on developer.intuit.com, I couldn't find where your priority or developer submitted request were listed.
We are continuing to integrate our platform with quickbook online to make full automation but this is the core hurdle we are facing right now. we have over 1000 invoices each month that are generated via api but due to limitation from this Allow payment link not being implemeted in email api, we have to go to qbo online web UI and it is verify slow process. We have to open every invoices and click to check "payment option" and then send them from Web UI.
I would really appreciate your response on this.

**Comment by hlu2** [comment]
@adsherpa 
The ticket number is: https://jira.intuit.com/browse/ACCTG-14887
Since this is a feature request, so it is not available to external developers in the bug tracker. The status for the ticket is still Open. I have left a comment, hoping some people will reply.
