### ISSUE TITLE
Tax rate

### ISSUE THREAD

**Issue by AryaKottayam** [intuit/QuickBooks-V3-PHP-SDK#138]
hi,
we have tried to add a tax group to quick book using qb v3 php sdk

$data=[
            "TaxCode"=>"Test",
            "TaxRateDetails"=>[
                ["RateValue"=> "8"],
                ["TaxRateName"=> "myNewTaxRateName"],
               ["TaxAgencyId"=> "1"],
                ["TaxApplicableOn"=> "Sales"]
                
                
            ]
        ];
     
        $taxRateEntityObj = TaxService::create($data);
        $taxRateEntity = $dataService->Add($taxRateEntityObj);

and obtained an error " Property Name:Can not deserialize instance of com.intuit.schema.finance.v3.TaxR specified is unsupported or invalid ".Please advise on how to create a tax group to QBO using sdk in php

**Comment by challgren** [comment]
PR #145 should fix this

**Comment by challgren** [comment]
Also your array is built incorrectly. Below is the corrected code

```
$data = [
    "TaxCode" => "Test",
    "TaxRateDetails" => [
        "RateValue" => "8",
        "TaxRateName" => "myNewTaxRateName",
        "TaxAgencyId" => "1",
        "TaxApplicableOn" => "Sales"
    ]
];

$taxRateEntityObj = TaxService::create($data);
$taxRateEntity = $dataService->Add($taxRateEntityObj);
```

**Comment by PrakharSambhav1** [comment]
This did not work for me
Required param missing, need to supply the required value for the API","Detail":"Required parameter TaxCode.TaxRateDetails is missing in the request","code":"2020","element":"TaxService.TaxCode"}],"type":"ValidationFault"},"time":"2018-08-22T07:15:50.518-07:00"}]

**Comment by unlockr** [comment]
I have the same problem

**Comment by tobiasvielmetter** [comment]
Same here

**Comment by tobiasvielmetter** [comment]
@AryaKottayam I ran into the same problem. Check out the example here: https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/_Samples/TaxServiceExample.php – you will have to use the TaxRate Facade for the 'TaxRateDetails' portion of the TaxService data Array.

**Comment by hlu2** [comment]
Please refer to https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/_Samples/TaxServiceExample.php for creating TaxService
