### ISSUE TITLE
Employee Time Activity - error on insert using PHP

### ISSUE THREAD

**Issue by AryaKottayam** [intuit/QuickBooks-V3-PHP-SDK#139]
Hi,
I have a requirement to insert employee time activity in Quick Books using php.
I am using quickbooks v3 php SDK.
We tried to insert time activity to QB using the sdk with below code
$data = [
 
"NameOf" => "Employee",
"EmployeeRef" => "114",
"EmployeeRef.name" => "gfgfdhdfh",
"StartTime" => $Result[$i]->start_time ,
"EndTime" => $Result[$i]->end_time,
"Description" => $Result[$i]->dispatch_status
 
];
$timeActivityEntityObj = TimeActivity::create($data);
$timeActivityEntity = $dataService->Add($timeActivityEntityObj);
 
but we are getting an error Property EmployeeRef.name does not exist
 
Please advise on how to make a time entry to QBO using sdk in php

**Comment by challgren** [comment]
You should change your data to the following and your code should work. 

```
$data = [
    "NameOf" => "Employee",
    "EmployeeRef" => [
        "value" => "114",
        "name" => "gfgfdhdfh",
    ],
    "StartTime" => $Result[$i]->start_time,
    "EndTime" => $Result[$i]->end_time,
    "Description" => $Result[$i]->dispatch_status
];
```
