### ISSUE TITLE
 Class 'DataService' not found

### ISSUE THREAD

**Issue by muhammadadnan97** [intuit/QuickBooks-V3-PHP-SDK#14]
I install the quickbook sdk in my codeignater project from this command.

$ composer require quickbooks/v3-php-sdk 
$ composer update

it create the sdk in the vendor folder

when i call from my controller

$configpath =  '../vendor/quickbooks/v3-php-sdk/src/sdk.config';
$dataService = DataService::Configure($configpath);

it return me Fatal error   Class 'DataService' not found

**Comment by josephzidell** [comment]
@muhammadadnan97 Did you `require` the `autoload.php` file?

**Comment by josephzidell** [comment]
@muhammadadnan97 Also make sure to put this at the top of your controller:
```php
use QuickBooksOnline\API\DataService\DataService;
```

**Comment by hlu2** [comment]
Thanks @josephzidell 
@muhammadadnan97 
I updated the readme file with more clear explanation of how to use the PHP SDK. As joseph suggested, you will need to import the DataService class before you can make the HTTP Call:
`use QuickBooksOnline\API\DataService\DataService;`

**Comment by muhammadadnan97** [comment]
Thanks it really helpful for me
