### ISSUE TITLE
"Namespace Error" exception creating a customer.

### ISSUE THREAD

**Issue by zynyz** [intuit/QuickBooks-V3-PHP-SDK#142]
Calling $data_service -> Add() to create a new customer throws an exception:

`Uncaught DOMException: Namespace Error in /var/www/flow/vendor/quickbooks/v3-php-sdk/src/XSD2PHP/src/com/mikebevz/xsd2php/Php2Xml.php:159
`

**Comment by challgren** [comment]
What minorVersion of the SDK are you using? If you are using higher than the default of version 8 you may have issues as the Customer XSD was updated with minorVersion 10. PR #145 should bring the SDK up to minorVersion 23.

**Comment by zynyz** [comment]
Thank you!

Our Ansible build just pulls the latest version via composer, currently 4.04 (according to composer/installed.json).

Silly question (I'm kind of new at composer and github), but how do I tell for sure what SDK version I have? Latest in the repo is 4.0.6.1.

**Comment by challgren** [comment]
You can always type composer info and it will show you the current installed version. As for what I can see so far the changes that will fix your issue are in dev-master so if you are comfortable using a development version you change change your composer.json file to use dev-master but be forewarned changes may get contributed that may break your implementation so its best to stick with a specified version until you can test your own code. I learned the hard way and a production server did a composer update and updated to a version that broke my code on production.

**Comment by challgren** [comment]
Ok so it looks like all the changes are in v 5.0.0
