### ISSUE TITLE
Unable to Query Invoices with Minor Version 16-23 and VendorCredits 12-23

### ISSUE THREAD

**Issue by challgren** [intuit/QuickBooks-V3-PHP-SDK#143]
The error is ```Exception appears in converting Response to XML.```

Further investigation reveals the root cause being

```
object(RuntimeException) {
        [protected] message => 'Property FreeFormAddress does not exist. Class QuickBooksOnline\API\Data\IPPInvoice'
        [protected] code => (int) 0
        [protected] file => '/Users/challgren/Projects/ATX Liquor/website v1/Vendor/quickbooks/v3-php-sdk/src/XSD2PHP/src/com/mikebevz/xsd2php/Bind.php'
        [protected] line => (int) 135
}
```

Also the [Developer Docs](https://developer.intuit.com/docs/00_quickbooks_online/2_build/20_explore_the_quickbooks_online_api/80_minor_versions) state that PHP SDK v4.0.4 supports Minor Version 23

My guess is the IPPSalesTransaction need to be updated to support SalesTransaction.FreeFormAddress that was added in Minor Version 21. I also looked and it appears that IPPVendorCredit needs to be updated to support VendorCredit.balance

My guess is no one has run the XSD2PHP since the project was started.

**Comment by hlu2** [comment]
@challgren I really appreciate your pointing out. Thanks so much for your contribution. I will review the changes and merge ASAP.

**Comment by challgren** [comment]
This can be closed when its released.

**Comment by challgren** [comment]
Release 5.0.0
