### ISSUE TITLE
how to get new refresh token after revoked ?

### ISSUE THREAD

**Issue by ghost** [intuit/QuickBooks-V3-PHP-SDK#147]
I trying to get new refresh token after revoked but i am getting 1 instead of refresh token

```
$dataService = DataService::Configure(array(
     		'auth_mode' => 'oauth2',
	     	'ClientID' => 'xxxxxxxxxxxxxxx',
	     	'ClientSecret' => 'xxxxxxxxx',
	     	//get the refresh token from session or database
	     	'refreshTokenKey' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
	     	'QBORealmID' => '13934156454157',
	     	'baseUrl' => "development"
		));

$OAuth2LoginHelper = $dataService->getOAuth2LoginHelper();

$refreshedAccessTokenObj = $OAuth2LoginHelper->refreshToken();
$revokeResult = $OAuth2LoginHelper->revokeToken($refreshedAccessTokenObj->getAccessToken());

```

**Comment by ebogdanov** [comment]
Can you explain your logic, please?

Revoking means that this set of Access+Refresh tokens are void, and can't be used anymore.
Why do you want to void token and get new one?

**Comment by mayankvadiya** [comment]
Hello @ebogdanov 
Its necessary for if some user want to disconnect from authorized app, that's why I revoked that token.

I am creating a demo for how to regenerate new refresh token after 101 days/

**Comment by ebogdanov** [comment]
OK, I see.

I just capture refresh token every time after refreshToken call to solve this.

**Comment by ebogdanov** [comment]
Yes, you're right.


But documentation says that we need to save every refreshToken, since they "can return new key someday", and old will not be valid after 24 hours.

https://developer.intuit.com/docs/00_quickbooks_online/2_build/10_authentication_and_authorization/10_oauth_2.0#/Refreshing_the_access_token

**Comment by mayankvadiya** [comment]
I tried to get new refreshToken after revoked existing token, I get an error about **invalid_grant**. RefeshToken is valid for 101 days and accessToken vallid for 24 hours. After run above function I am getting new accessToken on every request. I am storing on refreshToken.

**Comment by ebogdanov** [comment]
Yes, this is correct API behaviour. You need to reconnect application to get new pair of access+refresh tokens, if your refresh token is expired or revoked.

AccessToken is valid for 3600 seconds, which is 1 hour.
RefreshToken is valid for 100 days if initial accessToken was not used.

Check link, please, it describes all of those cases.

**Comment by mayankvadiya** [comment]
That means I need to reconnect or re-authorize app after 101 days, Right @ebogdanov ?

**Comment by ebogdanov** [comment]
Yes, during 100 days you should be able to load new access token and refresh token.

If during this was was not done - your keyset have been revoked by Intuit and as a result there is only one solution: to reconnect app, to get new key set.

If you revoked key manually (by code or user disconnected application) you should reconnect app too.

**Comment by mayankvadiya** [comment]
Thanks @ebogdanov
