### ISSUE TITLE
Can't retrieve a Customer/invoice/accounts based on updated time Using FindAll() function

### ISSUE THREAD

**Issue by murugasundaram** [intuit/QuickBooks-V3-PHP-SDK#149]
I am using the function FindAll() in QuickBooks-V3-PHP-SDK. This function only allows 3 parameters (Entity name, page num, page size). But i want to get the data based on Updated time. please help me.

**Comment by murugasundaram** [comment]
why is no one responding this issue?

**Comment by hlu2** [comment]
Please don't use findall if you want to get the data based on Updated time, use query() instead. See https://intuit.github.io/QuickBooks-V3-PHP-SDK/quickstart.html#query-and-access-resources-get

**Comment by murugasundaram** [comment]
I just customized the "FindAll" function based on my requirement. now I can use that function to retrieve a Customer/invoice/accounts based on updated time.

Thanks for the delayed reply.
