### ISSUE TITLE
disableLogger seems to have no effect

### ISSUE THREAD

**Issue by brumiser1550** [intuit/QuickBooks-V3-PHP-SDK#154]
It took me a while to trace this down but I think there is an issue that causes `$dataService->disableLog();` to not work. 

In this file /src/Core/ServiceContext.php is where the disableLog method is and it calls `LocalConfigReader::setupLogger()`

When it does that it passes the value "FALSE" to EnableRequestResponseLogging

When it is time for the logging handler here /src/Diagnostics/LogRequestsToDisk.php LogPlatformRequests to run it checks for `if ($this->EnableServiceRequestsLogging) ` which evaluates as truthy since it is a string and the logs write regardless of disableLog or not.

I am not sure why it would be set that way but when changed to `false` it runs correctly and does not create any logs.

**Comment by Jarrid** [comment]
I think this is an open issue (#104 )....I'm experiencing it as well.

**Comment by brumiser1550** [comment]
You are correct, I missed that. I will go ahead and close this one.
