### ISSUE TITLE
How to get initial quantity on hand?

### ISSUE THREAD

**Issue by jayshri123** [intuit/QuickBooks-V3-PHP-SDK#157]
When fetching sold items, it not returning sold quantity of item.

**Comment by challgren** [comment]
It won't you'll either need to access the report service or do a combo of adding up bills/expenses/vendor credits and invoices/sales receipts/credit memos on your own database

**Comment by hlu2** [comment]
@jayshri123 If you are trying to get initial quantity, the /Item API endpoint will have a field called: "QtyOnHand" that will provide the quantity. However, for sold items, challgren is right, you will need to use report service to get it, or adding items up. QuickBooks Online API is still in progress, and not all the features are implemented. I think this is a good feature, if you can post it here: https://intuitdevelopergroup.uservoice.com/forums/182764-intuit-developer-group/filters/top our Project managers will take a look.

Again, @challgren  thanks for your good response.
