### ISSUE TITLE
Php2Xml breaks in Zend

### ISSUE THREAD

**Issue by becquerel** [intuit/QuickBooks-V3-PHP-SDK#16]
`Php2Xml` constructor checks if `\Zend_Registry` class exists (it does in Zend 1), and then tries to use `\Zend_Registry::get('logger')`. This however throws and exception with message `No entry is registered for key 'logger'` if the `logger` is not registered.

I already created a PR for this issue

https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/15

**Comment by hlu2** [comment]
Thanks. Pull Request approved.
