### ISSUE TITLE
Payment LineEx data not readable

### ISSUE THREAD

**Issue by webspectyler** [intuit/QuickBooks-V3-PHP-SDK#160]
When I use the DataService's Query method to retrieve Payment records, the LineEx data is not accessible through the returned object. 

Here is the XML returned by the query (via the API Explorer):

![quickbooks_api_explorer___intuit_developer](https://user-images.githubusercontent.com/959960/42533809-832ec902-8450-11e8-9030-3741803a4074.jpg)

And here is the object returned by the Query method:

![query-object](https://user-images.githubusercontent.com/959960/42533945-f06c56c4-8450-11e8-83a8-80231a4fa3a8.jpg)

(In this particular case, I need the txnReferenceNumber field.) Let me know if I'm doing something wrong. I realize I could do a 2nd query to get this data, but that would dramatically increase the run time of this script. Thank you!

**Comment by pixelskribe** [comment]
I am not sure if this will help you or not, but I ran into a similar issue and wrote about it here https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/163.

I ran a query for Payments and can see that the `LineEx` is returned with the field you have found is missing.   Be aware that some of the data is returned slightly different, and this has only been tested with  invoice and sales receipts.

**Comment by webspectyler** [comment]
Thank you - I have decided to make the extra queries after all due to a tight deadline, but I appreciate your insights!
