### ISSUE TITLE
json Serializer syntax error

### ISSUE THREAD

**Issue by pixelskribe** [intuit/QuickBooks-V3-PHP-SDK#161]
When doing something like....
```
$query = 'select * from Invoice';
$dataService = DataService::configure($config);
$dataService->forceJsonSerializers();
$dataService->Query($query);
```
I am receiving an error message  `QuickBooksOnline \ API \ Exception \ IdsException` *Syntax error, ,* 

I am not sure what is causing it.   Without the json serializers the query returns without errors.

**Comment by javabudd** [comment]
This has been happening to me while querying tax rates, not sure why yet

`string(84) "SELECT * FROM TaxRate WHERE Name = :name AND Active IN (true, false) ORDERBY Id DESC"

string(16) "Syntax error, , "

string(4281) "#0 vendor/quickbooks/v3-php-sdk/src/Core/Http/Serialization/JsonObjectSerializer.php(53): QuickBooksOnline\API\Exception\IdsExceptionManager::HandleException('Syntax error')
#1 vendor/quickbooks/v3-php-sdk/src/Core/Http/Serialization/JsonObjectSerializer.php(214): QuickBooksOnline\API\Core\Http\Serialization\JsonObjectSerializer->checkResult(NULL)
#2 vendor/quickbooks/v3-php-sdk/src/DataService/DataService.php(804): QuickBooksOnline\API\Core\Http\Serialization\JsonObjectSerializer->Deserialize('<QueryResponse ...', false)
#3 module/QuickBooks/src/QuickBooks/Online/Core/Data/LiveDataService.php(77): QuickBooksOnline\API\DataService\DataService->Query('SELECT * FROM T...')`

**Comment by javabudd** [comment]
Looks like the code is trying to JSON Serialize xml, calling useXml() on the dataservice fixes this issue
