### ISSUE TITLE
issues with xsd2php library's  bindXML function

### ISSUE THREAD

**Issue by pixelskribe** [intuit/QuickBooks-V3-PHP-SDK#163]
In using the the SDK's   `$dataService->Query()` method  I noticed that the object being returned by the api was lacking some values available when otherwise doing a manual query using postman, curl, or the API explorer.

For example a manual query to an invoice returns the following json or xml snippet. 
```
//as JSON
"CustomerRef": {
          "value": "23",
          "name": "Amy's Bird Sanctuary"
  },
//as XML
<CustomerRef name="Amy's Bird Sanctuary">1</CustomerRef>

```
However using the SDK  `Query()` I was receiving simply
```
CustomerRef : "23"
```
This I believe is due to the parsing done in
`\quickbooks\v3-php-sdk\src\Core\Http\Serialization\XmlObjectSerializer` - `PhpObjFromXml()` which uses the xsd2php library.  The `bindXML()` method does not seem to support  preserving XML Attributes and I think there may be other issues as well.   In the example the `name`  attribute is lost. 

In order to get this working as needed for my project I replaced the  call to the xsd2php library with another parser.  [xml2array](http://www.bin-co.com/php/scripts/xml2array/)  Unfortunately it includes the attributes in another property with an `_attr` suffix. (see below)  This is sufficient for my projects needs but could be reworked further  to include both `value` and `name` etc in original property
```
CustomerRef : "23"
CustomerRef_attr : { name:  "Amy's Bird Sanctuary"}
```
Fork here https://github.com/pixelskribe/QuickBooks-V3-PHP-SDK
This may not be as robust as xsd2php but may help if you are experiencing similar issues with values being lost.

**Comment by hlu2** [comment]
Duplicate #38

**Comment by karneaud** [comment]
Issue still exists

**Comment by hyphen81** [comment]
This is still a problem. Has anyone used this fork and had good luck with it?

**Comment by karneaud** [comment]
> This is still a problem. Has anyone used this fork and had good luck with it?

Yes. But the workaround I would not be considered a "catch all" solution but just a means to an end for my use case

**Comment by chas688** [comment]
What is behind the SDK in trying to replace the return with XML from the server? I have had some issues as well with not all data getting through when passed through the XML conversion. What about not having any XML, but just converting the return from the server to an array? Thoughts?
