### ISSUE TITLE
Not able to put check no using php sdk

### ISSUE THREAD

**Issue by 22wpexpert** [intuit/QuickBooks-V3-PHP-SDK#164]
![check_no](https://user-images.githubusercontent.com/16928188/43466407-15cbaf70-94fd-11e8-9f55-a0459de4899f.png)

I want to add check no as highlighted in attached image. 
`<?xml version="1.0" encoding="utf-8"?>
								<?qbxml version="13.0"?>
								<QBXML>
							    <QBXMLMsgsRq onError = "continueOnError">
							        <CheckAddRq requestID="551">
										<CheckAdd>
											<AccountRef>                    
									          <ListID>800000D3-1424720891</ListID>                     
									        </AccountRef>
									        <PayeeEntityRef>
									          <ListID>80000DE6-1485903291</ListID>                            
									        </PayeeEntityRef> 
									        <RefNumber>1234</RefNumber>
									        <TxnDate>2018-07-31</TxnDate>
									        <Memo>test</Memo>
									        <ExpenseLineAdd>            
											<AccountRef>                                                             
												 <ListID>1A0000-935014156</ListID>                   
											</AccountRef>
											<Amount>5.00</Amount>                           
											<ClassRef>                                        
												<ListID>80000021-1502402112</ListID>                                            
											</ClassRef>                                   
											</ExpenseLineAdd>
											<ExpenseLineAdd>            
												<AccountRef>                                                             
													 <ListID>800000E9-1494101714</ListID>                   
												</AccountRef>
												<Amount>395.14</Amount>                           
												<ClassRef>                                        
													<ListID>80000021-1502402112</ListID>                                            
												</ClassRef>                                   
									        </ExpenseLineAdd>
									      </CheckAdd>
										</CheckAddRq>
							    </QBXMLMsgsRq>
							</QBXML>` 

Please let me know how can i put check no ?

**Comment by challgren** [comment]
Are you using QuickBooks Online or QuickBooks Desktop. From the screenshot you posted it appears that you are using QuickBooks Desktop.
