### ISSUE TITLE
invoice delete / void : How can i get deleted / void invoice only?

### ISSUE THREAD

**Issue by murugasundaram** [intuit/QuickBooks-V3-PHP-SDK#167]
How can i get **deleted / void** invoice only?

**Comment by challgren** [comment]
To find deleted invoices you can use [Change Data Capture](https://developer.intuit.com/docs/api/accounting/changedatacapture) to get invoices that are deleted. However if the invoice was deleted 30 days prior you would need to query all the invoices and compare the IDs to what you have stored to the IDs that are not returned and locally remove the deleted invoices.

Void invoices will return with a balance and total_amount of ```0.0000``` and ```Void``` in the private_note the line items will be returned however the qty will be 0 and the amount maybe 0.00.

I do know that a [Bug ACCTG-9279](https://help.developer.intuit.com/s/bug?category=all&id=ACCTG-9279&page=2&status=all&type=all) is logged to expose the invoice status however it appears that it is still inprogress

Hopes this helps you.
