### ISSUE TITLE
Problem after calling ::create (object gets created, but I got an include warning)

### ISSUE THREAD

**Issue by nicosavini** [intuit/QuickBooks-V3-PHP-SDK#176]
I got the following code:

```$dataService = $this->getDataService();
        $theResourceObj = \QuickBooksOnline\API\Facades\JournalEntry::create([
            "Line" => $this->createJournalConfiguration($lineConfiguration)
        ]);
        $dataService->Add($theResourceObj);
        $error = $dataService->getLastError();
        if ($error) {
            return false;
        }
        return true;
```

Whenever I call this, the Journal Entry gets created in my QBO Intuit Account but I get a warning `include(IPPJournalEntry.php) no such file or directory` 

I solved this ignoring warnings for this call, but I believe this is something that could be avoided directly from de SDK. 

I've installed the SDK using composer...

**Comment by hlu2** [comment]
@nicosavini The `include` keyword is in your code. I don't think there is any code in the SDK that has include(IPPJournalEntry.php)
