### ISSUE TITLE
Reminder Emails

### ISSUE THREAD

**Issue by treestonemedia** [intuit/QuickBooks-V3-PHP-SDK#177]
I'm looking for a way to send email reminders for past due invoices.

I have a query to get all the ID's of the past due invoices but I'm stuck after that.
What action and what parameters should we use?

**Comment by diana-derose** [comment]
Try using https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/invoice#send-an-invoice also for non SDK related questions, please post on our help community.
https://help.developer.intuit.com/s/
