### ISSUE TITLE
How to specify payment method and Reference no when set payment for some invoice?

### ISSUE THREAD

**Issue by stojankukrika** [intuit/QuickBooks-V3-PHP-SDK#178]
Hi,
How to specify payment method and Reference no when set payment for some invoice using this SDK? We use quickbooks online and like to specify this fields in payments. Is there any option to do over your API?

![153851285679136684](https://user-images.githubusercontent.com/10199584/46375273-41b9fc00-c693-11e8-8e39-f813aa430b3b.png)

**Comment by hlu2** [comment]
Please refer to our crud example: https://github.com/IntuitDeveloper/SampleApp-CRUD-PHP/tree/master/CRUD_Examples and docs: https://intuit.github.io/QuickBooks-V3-PHP-SDK/
