### ISSUE TITLE
Only variables should be passed by reference in D:\xamp\htdocs\php\QB\src\Core\Http\Serialization\XmlObjectSerializer.php on line 54

### ISSUE THREAD

**Issue by cse00241** [intuit/QuickBooks-V3-PHP-SDK#180]
Exception Call Stack (Namespace Error): In (D:\xamp\htdocs\php\QB\src\XSD2PHP\src\com\mikebevz\xsd2php\Common.php) on 278
Notice: Only variables should be passed by reference in D:\xamp\htdocs\php\QB\src\Core\Http\Serialization\XmlObjectSerializer.php on line 54
getXmlFromObj() XmlObjectSerializer.php:75 getPostXmlFromArbitraryEntity() XmlObjectSerializer.php:200 Serialize() DataService.php:1171 executeObjectSerializer() DataService.php:765 Add() AccountCreate.php:188

I got this error and I tried both localhost and online. Same error show. and also below is my code: 

include('src/config.php');
use QuickBooksOnline\API\DataService\DataService;
use QuickBooksOnline\API\Core\Http\Serialization\XmlObjectSerializer;
use QuickBooksOnline\API\Facades\Account;
use QuickBooksOnline\API\Core\ServiceContext;
use QuickBooksOnline\API\Facades\Invoice;

// Prep Data Services
$dataService = DataService::Configure(array(
     'auth_mode' => 'oauth2',
    'ClientID' => "nnnn",
    'ClientSecret' => "zzzz",
    'accessTokenKey' => "xxxxx",
    'refreshTokenKey' => "yyyy",
    'QBORealmID' => "tttt",
    'baseUrl' => "Development"
));

$OAuth2LoginHelper = $dataService->getOAuth2LoginHelper();
$refreshedAccessTokenObj = $OAuth2LoginHelper->refreshToken();
$error = $OAuth2LoginHelper->getLastError();
if($error){
  echo 'fail';
}else{
  //Refresh Token is called successfully
  $dataService->updateOAuth2Token($refreshedAccessTokenObj);
  echo 'done';
}

$dataService->setLogLocation("/Users/hlu2/Desktop/newFolderForLog");
$theResourceObj = Invoice::create([
	"Deposit" => 500,
     "Line" => [
   [
     "Amount" => 100.00,
     "DetailType" => "SalesItemLineDetail",
     "SalesItemLineDetail" => [
       "ItemRef" => [
         "value" => 1,
         "name" => "Services"
        ]
      ]
      ]
    ],
   "CustomerRef"=> [
      "value"=> 21
   ]
]);

//$theResourceObj = Invoice::create(json_decode($json, true));
$resultingObj = $dataService->Add($theResourceObj);
print_r($resultingObj);exit;
$error = $dataService->getLastError();
if ($error) {
    echo "The Status code is: " . $error->getHttpStatusCode() . "\n";
    echo "The Helper message is: " . $error->getOAuthHelperError() . "\n";
    echo "The Response message is: " . $error->getResponseBody() . "\n";
}
else {
    echo "Created Id={$resultingObj->Id}. Reconstructed response body:\n\n";
    $xmlBody = XmlObjectSerializer::getPostXmlFromArbitraryEntity($resultingObj, $urlResource);
    echo $xmlBody . "\n";
}

**Comment by challgren** [comment]
Are you by chance using dev-master?

**Comment by alexjeen** [comment]
Downgrade to not dev version. Ie. change in composer.json:

    "quickbooks/v3-php-sdk": "5.0.3",

And run composer update.

**Comment by cse00241** [comment]
I use dev when I downgrade in 5.0.2.1 now everything works fine. Why the latest version shows a problem? I use Development.

**Comment by alexjeen** [comment]
Track this issue, the problem is discussed here:
https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/182
