### ISSUE TITLE
Hidden dependency on mbstring

### ISSUE THREAD

**Issue by jclxx** [intuit/QuickBooks-V3-PHP-SDK#181]
A first use of the SDK with the basics has a hidden dependency on `mbstring` which generates a fatal error.

## Environment ##

    PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
    QuickBooks-V3-PHP-SDK v5.0.3
    https://github.com/intuit/QuickBooks-V3-PHP-SDK.git "797d1a2dc2685b4f103e938c5d4f43da46af33ae"

## Severity ##

Fatal, can't progress unless worked around.

## Ease of fix ##

Should be straightforward

* Modify `setIntuitResponse` to not need it, or
* Ensure composer files declare the requirement, and/or
* Document it on requirements of documentation page

## Workaround ##

Install mbstring, such as Ubuntu:

    sudo apt-get install php7.2-mbstring

## Reproduce ##
```

include("vendor/autoload.php");
use QuickBooksOnline\API\DataService\DataService;
$dataService = DataService::Configure(array(
     'auth_mode' => 'oauth2',
      'ClientID' => "a valid client id",
      'ClientSecret' => "a valid client secret",
      'RedirectURI' => "https://developer.intuit.com/v2/OAuth2Playground/RedirectUrl",
      'scope' => "com.intuit.quickbooks.accounting",
      'baseUrl' => "Development/Production"
));
$OAuth2LoginHelper = $dataService->getOAuth2LoginHelper();
$authorizationUrl = $OAuth2LoginHelper->getAuthorizationCodeURL();
printf("url %s\n", $authorizationUrl);

$authcode = readline("authcode? ");
$realmid = readline("realmid? ");
$accessToken = $OAuth2LoginHelper->exchangeAuthorizationCodeForToken($authcode, $realmid);
printf("never gets here\n")

PHP Fatal error:  Uncaught Error: Call to undefined function QuickBooksOnline\API\Core\HttpClients\mb_substr() in /home/projects/accounting/quickbooks/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/CurlHttpClient.php:131
...
```

**Comment by challgren** [comment]
I fixed this in the latest pull request. I also found a hidden ext-dom requirement so I added that to the composer.json file too.
