### ISSUE TITLE
Unable to set TxnDate when creating an invoice

### ISSUE THREAD

**Issue by thunberg** [intuit/QuickBooks-V3-PHP-SDK#185]
Attempting to set a date when creating a new invoice, setting as an array element that gets passed to Invoice::create:

`'TxnDate' => ['date' => $trip->datetime_scheduled->format('Y-m-d\Z')],`

Receive the following error when attempting to do so:

The name value:{TxnDate} can't be used to construct an Intuit Entity Object. Please check the name and try again.

**Comment by challgren** [comment]
You should just use 'TxnDate' => $trip->datetime_scheduled->
format('Y-m-d\Z'),

**Comment by thunberg** [comment]
Worked, thank you for the quick reply. Not sure if I'm reading the API reference wrong:

https://developer.intuit.com/docs/api/accounting/invoice

All other attributes that listed a child attribute needed to be passed as an array (e.g. CustomerRef, BillEmail, SalesTermRef, etc). Am I missing something or is it a docs typo?

**Comment by challgren** [comment]
Yep you just need the field => [value = id]
