### ISSUE TITLE
Uncaught Error: Class 'WebhooksEvent' not found

### ISSUE THREAD

**Issue by kingIZZZY** [intuit/QuickBooks-V3-PHP-SDK#188]
Trying to use webhooks results in the above exception thrown

```
$event = WebhooksService::getWebhooksEvent(file_get_contents('php://input'));
```

src/Utility/ReflectionUtil.php
QuickBooksOnline\API\Utility\ReflectionUtil::**constructObjectFromWebhooksArray**()
`$wrapObject = new $clazz();`

It seems you cannot instantiate a class from a string like this - even if the class is mentioned in `use` above - rather only if using the fully qualified class name with namespace.

Temporary hack fix:
```
$clazz = 'QuickBooksOnline\\API\\WebhooksService\\'.$clazz;
$wrapObject = new $clazz();
```

**Comment by Kigamba** [comment]
I am also facing the same problem. Anyone who can help on this? 

@diana-derose Would you have an idea on why this is happening or point us to the right person?

**Comment by diana-derose** [comment]
Hi @Kigamba  - @hlu2  will get back to you on this.

**Comment by hlu2** [comment]
@kingIZZZY It seems like the namespace is not matched correctly. I will check what goes wrong here.
