### ISSUE TITLE
Journal Voucher Entry not created with Entity

### ISSUE THREAD

**Issue by pankajk79** [intuit/QuickBooks-V3-PHP-SDK#189]
Getting "Passed array has no key for 'Value' when contructing an ReferenceType
status: 0" while creating Journal Voucher Entry with Entity.

Without Entity it is working find.

Below are details:

I am creating Journal Entry using API.

I have prepared array like
$data = array();
		
$line_data = array();
$JournalEntryLineDetail['PostingType'] = 'Debit';
$JournalEntryLineDetail['Entity'] = array(
           "Type" => "Customer",
           "EntityRef" => array(
               "value" => "2",
               "name" => "Bill's Windsurf Shop"
           )
        );
$JournalEntryLineDetail['AccountRef']['value'] = '34';
$JournalEntryLineDetail['AccountRef']['name'] = 'Opening Bal Equity';

$line_data['Description'] = "nov portion of rider insurance";
$line_data['Amount'] = 100.0;
$line_data['DetailType'] = "JournalEntryLineDetail";
$line_data['JournalEntryLineDetail'] = $JournalEntryLineDetail;

$Line[] = $line_data;
		
$line_data = array();
$JournalEntryLineDetail = array();
$JournalEntryLineDetail['PostingType'] = 'Credit';
		
$JournalEntryLineDetail['AccountRef']['value'] = '44';
$JournalEntryLineDetail['AccountRef']['name'] = 'Notes Payable';

$line_data['Description'] = "nov portion of rider insurance";
$line_data['Amount'] = 100.0;
$line_data['DetailType'] = "JournalEntryLineDetail";
$line_data['JournalEntryLineDetail'] = $JournalEntryLineDetail;
$Line[] = $line_data;
		
$data['Line'] = $Line;

The json created using array is 
{"Line":[{"Description":"nov portion of rider insurance","Amount":100,"DetailType":"JournalEntryLineDetail","JournalEntryLineDetail":{"PostingType":"Debit","AccountRef":{"value":"34","name":"Opening Bal Equity"},"Entity":{"Type":"Customer","EntityRef":{"value":"2","name":"Bill's Windsurf Shop"}}}},{"Description":"nov portion of rider insurance","Amount":100,"DetailType":"JournalEntryLineDetail","JournalEntryLineDetail":{"PostingType":"Credit","AccountRef":{"value":"44","name":"Notes Payable"}}}]}

When I paste this json in API EXPLORER then Journal voucher created with Entity.

But when the same array from which json created is used in

$theResourceObj = JournalEntry::create($data);

I got message "Passed array has no key for 'Value' when contructing an ReferenceType
status: 0"

Please fix this issue, as it is important to create Journal Voucher with entity.

**Comment by challgren** [comment]
Make sure your variables are in the correct case value is not the same as
Value

**Comment by pankajk79** [comment]
Tried both 'value' and 'Value' both result same.

**Comment by hlu2** [comment]
@pankajk79 Do you still see this issue? If you still see the issue, please open a support ticket at https://help.developer.intuit.com/s/

**Comment by hyphen81** [comment]
I know this is old, but I'm seeing this issue now. I've tried both value and Value, and it doesn't work for the EntityRef. lower case (value) is fine for the AccountRef object, but It get the key error for EntityRef.
