### ISSUE TITLE
Error in checking cURL version for TLS 1.2. Error Num:[7] Error message:[Failed to connect to www.howsmyssl.com port 443: Connection refused]

### ISSUE THREAD

**Issue by niceproject** [intuit/QuickBooks-V3-PHP-SDK#191]
BaseCurl.php:115
At the moment it tries to check tls 1.2 support by requesting following URL https://www.howsmyssl.com/a/check however in my case the request fails intermittently. As I know that tls 1.2 is supported in my web server then could this check be made optional?

**Comment by eezaamout** [comment]
I am having the same issue. What I noticed is, inside the src/Core/HttpClients/CurlHttpClient.php, at line 148 (inside the setSSL function), the tlsVersion is returning 1.3 from howsmyssl.com, and the curl_exec, was successful. I think the solution for this would be to check for TLS 1.2 and greater. or changing the check for 1.3 (this is inside the setSSLfunction, mainly strcmp($tlsVersion, "TLS 1.2") != 0 should check for 1.3 or check for equal or greater than 1.3.

**Comment by hlu2** [comment]
This has been fixed.
