### ISSUE TITLE
SdkException in CurlHttpClient.php line 122

### ISSUE THREAD

**Issue by msankar1991** [intuit/QuickBooks-V3-PHP-SDK#192]
Followed the same steps given this [link](https://intuit.github.io/QuickBooks-V3-PHP-SDK/authorization.html)
Latest version SDK was installed **^5.0** in composer.json also with laravel, and guzzle also installed.
PHP version: _7.0.10_

```
SdkException in CurlHttpClient.php line 122:
cURL error during making API call. cURL Error Number:[28] with error:[Operation timed out after 10000 milliseconds with 0 out of 0 bytes received]
```

**Comment by hlu2** [comment]
QBO returns data within 2 minutes, Please increase the time out to 12000 milliseconds.
