### ISSUE TITLE
Facade Missing for Terms

### ISSUE THREAD

**Issue by murugasundaram** [intuit/QuickBooks-V3-PHP-SDK#194]
In the Quickbooks-V3-PHP-SDK, there is no facade for Sales Terms. so i am not able to create / update Terms to QuickBooks Online. Is there any alternative way to create Sales Terms?

**Comment by developergaurav** [comment]
Is there any update on this issue? I am getting the same problem.

**Comment by hlu2** [comment]
https://jira.intuit.com/browse/IDG-3105

**Comment by hlu2** [comment]
Fixed
