### ISSUE TITLE
ShipFromAddr

### ISSUE THREAD

**Issue by dsbcourtney** [intuit/QuickBooks-V3-PHP-SDK#195]
All of a sudden this morning ShipFromAddr started appearing in Invoices and Estimates and I am getting the following error:

Fatal error: Uncaught exception 'RuntimeException' with message 'Property ShipFromAddr does not exist. Class QuickBooksOnline\API\Data\IPPInvoice'

Can't find that property in this API at all. I am using minorVersion 8.

It is in here though... 
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/invoice

**Comment by jrock24** [comment]
We also just started seeing the 'ShipFromAddr' property and are getting the following Exception: 

> Exception: Exception appears in converting Response to XML.

**Comment by dsbcourtney** [comment]
Yes I am presuming that it is just a new property that hasn't been added yet. As a temporary fix I added it into the IPPSalesTransaction.php file.

**Comment by iseayam-webpoint** [comment]
> Yes I am presuming that it is just a new property that hasn't been added yet. As a temporary fix I added it into the IPPSalesTransaction.php file.

Hello, I am having the same error. Can you let me know what exactly did you add in the IPPSalesTransaction.php file and the line number please? 

I have added the property as ```public $ShipFromAddr;``` but now it is throwing following error:
> Can't find corresponding CLASS for className in Bind.php

**Comment by dsbcourtney** [comment]
This might depend on the version you are using but I have tested on the following:
4.0.1:
After where the ShipAddr property is declared I added the following (on line 108):
`    /**
     * @Definition
                                Product: ALL
                                Description: QBO: Shipping address of the Invoice.[br]See [a href="http://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0060_Financial_Management_Services_(v3)/01000_Using_Data_Service_Entities#Addresses"]Addresses[/a]
                                Description: QBW: Identifies the address where the goods must be shipped. [br /]QuickBooks Note: If ShipAddr is not specified, and a default ship-to address is specified in QuickBooks for this customer, the default ship-to address will be used by QuickBooks.[br]See [a href="http://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0060_Financial_Management_Services_(v3)/01000_Using_Data_Service_Entities#Addresses"]Addresses[/a]

     * @xmlType element
     * @xmlNamespace http://schema.intuit.com/finance/v3
     * @xmlMinOccurs 0
     * @xmlName ShipAddr
     * @var com\intuit\schema\finance\v3\IPPPhysicalAddress
     */
    public $ShipFromAddr;    `

and on 5.0.3 the same but on line 151.

I am not 100% sure but you might need to make sure you add all the definition parts above.

**Comment by iseayam-webpoint** [comment]
I am using 5.0.1 and the code you provided has worked for me. 
Thanks a lot for helping me out. 👍

**Comment by challgren** [comment]
To fix this download the XSDs from https://developer.intuit.com/app/developer/qbo/docs/develop/explore-the-quickbooks-online-api/minor-versions then unzip them into `src/XSD` then cd into `src` and type `php xsd2php.php` and that will update your Class files.

**Comment by challgren** [comment]
My guess is they released an update that accidentally exposed the `ShipFrom` variable to all minorVersions when this is really a minorVersion 35 only feature. @hlu2 any idea?
