### ISSUE TITLE
Unsupported or undocumented operation (no examples?)

### ISSUE THREAD

**Issue by vicentor** [intuit/QuickBooks-V3-PHP-SDK#197]
We are trying to upload a text file (text/plain mime type) to QBO and attach it to an invoice using PHP. We couldn't find any relevant examples or documentation about this operation, kindly guide us to it if we missed it.

Here's a snippet we tried. It uploads the file successfully but does not attach it to the invoice.

```
$up = file_get_contents('file.txt');
$sendMimeType = "text/plain";

$entityRef = new IPPReferenceType(array('type'=>'Bill', 'name' => 'Bill', 'value'=>2049));
$attachableRef = new IPPAttachableRef($entityRef);
$objAttachable = new IPPAttachable();

$objAttachable->FileName =  date('Y-m-d H:i:s')."--file.txt";
$objAttachable->AttachableRef = $attachableRef;
$objAttachable->Note = "Test";
$objAttachable->ContentType = $sendMimeType;

$resultObj = $data_service->Upload($up,
$objAttachable->FileName,
$sendMimeType,
$objAttachable);
```

Good work everyone!

**Comment by jason-newvision** [comment]
Hi @vicentor in case you're still having an issue with this.. I used the example here as a basis:
[https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/2943e4d9581cb41336475ac707774c9273cff9db/src/_Samples/UploadAttachment.php](url)

Using this I was able to upload a file and attach it to a bill/invoice in one go.

**Comment by jason-newvision** [comment]
For anyone who finds this old post. The above example no longer works. The file must be base64 encoded first.
I found my old answer while trying to solve a new issue! The following should work:

`$result = $this->dataService->Upload(
            base64_encode(file_get_contents($request->file->getRealPath())),
            $objAttachable->FileName,
            $request->file->getClientMimeType(),
            $objAttachable
        );
`
