### ISSUE TITLE
Global discount on Invoices

### ISSUE THREAD

**Issue by theoblkr** [intuit/QuickBooks-V3-PHP-SDK#198]
I cannot set up global discount on invoices using QBO APIs. It is working on non-French companies but not on French companies.
Any solutions ?

**Comment by hlu2** [comment]
@theoblkr Please see our docs and CRUD example: https://intuit.github.io/QuickBooks-V3-PHP-SDK/ https://github.com/IntuitDeveloper/SampleApp-CRUD-PHP/tree/master/CRUD_Examples If you still can't figure it out, create a support ticket.
