### ISSUE TITLE
Wrong file name: IPPcurrencyCode.php should be IPPCurrencyCode.php

### ISSUE THREAD

**Issue by xgretsch** [intuit/QuickBooks-V3-PHP-SDK#201]
You have a wrong file name as shown in the title. The lower case 'c' doesn't cause a problem on my MacOS development system (and I assume works OK under Windows), but my production server is case sensitive to filenames and it causes the class not to be found.

Renaming the file to IPPCurrencyCode.php solves the problem.

(My production server is PHP7.3, Centos 7)

**Comment by hlu2** [comment]
@xgretsch The data service is generated from schema: https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/XSD/Finance.xsd since it has lower case, the file generated has lower case as well.
