### ISSUE TITLE
Invoice Create Sample is not updated with oAuth  2 code

### ISSUE THREAD

**Issue by vk-sourcefuse** [intuit/QuickBooks-V3-PHP-SDK#203]
Invoice Create Sample is not updated with oAuth  2 code

Link :
https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/_Samples/InvoiceCreate.php

**Comment by coopergarry** [comment]
Hello, 
Did you found a way to create an invoice ?
Thanks for reply.

**Comment by vk-sourcefuse** [comment]
Yes, this was my code ::
`<?php
 public function createInvoice($invoiceID, $customerRef, $lines, $options)
    {
        $this->loadAccessToken();
       
        $tmpObj = new \QbMain();
        $dataService = $this->getDataserviceObj();

        $defaultItemID = $options["itemID"];

        $invArr = [];
        $invArr["DocNumber"] = $options["invoiceNumber"];
        $invArr["TxnDate"] = date("d:m:Y");
        $invArr["CustomerRef"] = ["value" => $customerRef];
        $invArr["CustomerMemo"] = ["value" => "test"];

        foreach ($lines as $line) {
            $lineItemID = $line["itemID"] ?  $line["itemID"] : $defaultItemID;
            $line["serviceDate"] = ($line["serviceDate"] == "") ? date("Y-m-d", strtotime("now")) : $line["serviceDate"];
            $line["quantity"] = ($line["quantity"] == "") ? 0 : $line["quantity"];
            $line["unitPrice"] = ($line["unitPrice"] == "") ? "0.00" : $line["unitPrice"];

            $invLine["Amount"] = $line["amount"];
            $invLine["DetailType"] = "SalesItemLineDetail";
            $invLine["LineNum"] = $line["lineNumber"];
            $invLine["Description"] = $line["description"];
            $invLine["SalesItemLineDetail"] = [
                "ItemRef" => [
                    "value" => $lineItemID
                ],
                "ServiceDate" => $line["serviceDate"],
                "Qty" => $line["quantity"],
                "UnitPrice" => $line["unitPrice"]
            ];

            $invArr["Line"][] = $invLine;
        }
        $theResourceObj = Invoice::create($invArr);
        $resultingObj = $dataService->Add($theResourceObj);
        $invoiceNumber = $resultingObj->DocNumber;
        $tmpObj->__destruct();
        return $invoiceNumber;
    }`

**Comment by coopergarry** [comment]
A big thank you!
I was just having a problem with the personalized invoice number. The error I have talk about company.
Thank you for confirming that it was working.

**Comment by ivangomes** [comment]
@vaibhavkumar-sf  thank you!
