### ISSUE TITLE
How to get all products and inventory data?

### ISSUE THREAD

**Issue by octalsolutions** [intuit/QuickBooks-V3-PHP-SDK#206]
I want to update my local inventory data using API. So I can just press Sync button and it will get all products with its inventory.
Any Help? How we can do that?

**Comment by aegenes** [comment]
Here's how I was able to retrieve inventory details using the INVENTORYVALUATIONSUMMARY report. There's probably a better way, but it works:

`/**
 * Define Inventory Variables & Values
 */

$inventory = new ReportService($serviceContext);

if (!$inventory) {
	exit("Problem while initializing ReportService.\n");
}

$inventory_results = json_decode(json_encode($inventory->executeReport(ReportName::INVENTORYVALUATIONSUMMARY)), true);

//$inventory_total = end($inventory_results['Rows']['Row']['ColData'][3]['value']);

/*
echo '<pre>';
print_r($inventory_results);
echo '</pre>';
*/

$total = 0;

foreach($inventory_results['Rows']['Row'] as $inventory_item) {
	$inventory_item_description = $inventory_item['ColData'][0]['value'];
	$inventory_item_retail = $inventory_item['ColData'][2]['value'];
	$inventory_item_quantity = $inventory_item['ColData'][4]['value'];
	
	/*
	echo 'Description: ' . $inventory_item_description . '<br />';
	echo 'Retail: $' . number_format($inventory_item_retail) . '<br />';
	echo 'Quantity: ' . $inventory_item_quantity . '<br /><br />';
	*/
	
	$inventory_subtotal = $inventory_item['ColData'][2]['value'] * $inventory_item['ColData'][4]['value'];
	$inventory_total += $inventory_subtotal;
}

//echo 'Total: $' . number_format($inventory_total);`
