### ISSUE TITLE
No Support for OpenID

### ISSUE THREAD

**Issue by VERT9** [intuit/QuickBooks-V3-PHP-SDK#208]
There are no methods to get the OpenID tokens out of the OAuth2LoginHelper object. There's a code snippet on [Intuit's docs](https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/openid-connect#step-6-validate-id-token) about validating the ID tokens but that doesn't exist in this "Official" SDK.

The snippet:
```php
//Return true if it is correct, or false otherwise
$result = $OAuthLoginHelper::ValidateIDToken($clientID, $ID_token);
```

It should be accessible after calling:
```php
$OAuth2LoginHelper->exchangeAuthorizationCodeForToken("authorizationCode", "RealmID")
```
with the `openid` scope, but there's no way to get it. I don't even see a way to get the response from that function at all.

Is this going to be supported soon?

**Comment by hlu2** [comment]
Create jira for it: IDG-3106

**Comment by hlu2** [comment]
Fixed
