### ISSUE TITLE
Why TxnTaxCodeRef not work

### ISSUE THREAD

**Issue by pioter** [intuit/QuickBooks-V3-PHP-SDK#210]
`$result = Invoice::create([
            "Line" => [
                [
                    "Amount" => 15,
                    "DetailType" => "SalesItemLineDetail",
                    "SalesItemLineDetail" => [
                        "ItemRef" => [
                            "value" => 1,
                            "name" => "Services"
                        ],
                        "TaxCodeRef" => [
                            "value" => "TAX",
                        ],
                        "Qty" => 1
                    ],
                ],
                [
                    "Amount" => 15,
                    "DetailType" => "SubTotalLineDetail",
                    "SubTotalLineDetail" => [],
                ]
            ],
            "TxnTaxDetail" => [
                "TxnTaxCodeRef" => [
                    "value" => 6,
                ],
                "TaxLine" => [
                    [
                        "Amount" => 0.60,
                        "DetailType" => "TaxLineDetail",
                        "TaxLineDetail" => [
                            "TaxRateRef" => [
                                "value" => "10",
                                "name" => 'trsfgfdgdfgd'

                            ],
                            "TaxPercent"=> 4,
                            "NetAmountTaxable" => 15,
                            "PercentBased" => true
                        ],
                    ],
                    [
                        "Amount" => 0.68,
                        "DetailType" => "TaxLineDetail",
                        "TaxLineDetail" => [
                            "TaxRateRef" => [
                                "value" => "11",
                                "name" => 'trsfgfdgdfgd'

                            ],
                            "TaxPercent"=> 4.5,
                            "NetAmountTaxable" => 15,
                            "PercentBased" => true
                        ],
                    ],
                    [
                        "Amount" => 0.06,
                        "DetailType" => "TaxLineDetail",
                        "TaxLineDetail" => [
                            "TaxRateRef" => [
                                "value" => "12",
                                "name" => 'trsfgfdgdfgd'

                            ],
                            "TaxPercent"=> 0.375,
                            "NetAmountTaxable" => 15,
                            "PercentBased" => true
                        ],
                    ]
                ],
                "TotalTax" => 2.34,
            ],
            "CustomerRef" => [
                "value" => "3"
            ]
        ]);`

I set TxnTaxCodeRef for my tax code but always set default tax code.

**Comment by hlu2** [comment]
Check if your company is AST enabled. If it is AST enabled, the TxnTaxCodeRef is set by AST. For line item, the Tax Code is always "TAX" or "NON".
