### ISSUE TITLE
Invalid Company StatusSubscription period has ended or cancelled or there was a billing problem

### ISSUE THREAD

**Issue by meltsasv** [intuit/QuickBooks-V3-PHP-SDK#211]
During debugging found response for clients dataService add request:

[body:QuickBooksOnline\API\Core\HttpClients\IntuitResponse:private] => Invalid Company StatusSubscription period has ended or cancelled or there was a billing problem : You can't add data to QuickBooks Online Plus because your trial or subscription period ended, you cancelled your subscription, or there was a billing problem. To update your subscription, click the gear icon and view your account information.
[httpResponseCode:QuickBooksOnline\API\Core\HttpClients\IntuitResponse:private] => 200

faultHandler is empty, dataService getLastError will not pick it up as an error.
There is no nice way to ask this information from dataService and doing a hack solution to compare the string is not an option.

Can there be an error code for this or a getter so it would be possible to ask it directly from dataService object.

**Comment by hlu2** [comment]
@meltsasv The API should return 400. I will fire a bug for API Team to fix it.
