### ISSUE TITLE
Unable to implement grant_type: client_credentials

### ISSUE THREAD

**Issue by thammer67** [intuit/QuickBooks-V3-PHP-SDK#214]
I am developing an in-house application that needs to communicate with the QBO API and I have been unsuccessful in getting "client_credentials" to work using Postman and our sandbox setup in the developer site. We need to bypass authorizing a specific QBO user to directly access our company data. Is there a trick to getting "client_credentials" to work correctly?

**Comment by hlu2** [comment]
We do not support API keys or HTTP Basic Authentication. We only support OAuth 1 and OAuth 2. That applies to developers who want to create an app for his/her own QuickBooks Online Company. 

However, once the user is granted access to the app, all subsequent requests can be achieved through backend without user interaction. Refresh token is the key.
