### ISSUE TITLE
TLS error with version 1.2 fails as i have TLS version 1.3

### ISSUE THREAD

**Issue by robertclarkson** [intuit/QuickBooks-V3-PHP-SDK#215]
Getting this error
```
Error. Checking TLS 1.2 version failed. Please make sure your PHP cURL supports TSL 1.2
```
Dumping my TLS version gives
```
TLS 1.3
```
I guess the check should be for TLS versions < 1.2 ?

My other versions are;
```
curl --version
curl 7.58.0 (x86_64-pc-linux-gnu)
openssl version
OpenSSL 1.1.1b  26 Feb 2019
```

**Comment by robertclarkson** [comment]
Just found this PR https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/209

**Comment by Jewhurst** [comment]
Yep, that should solve that issue for you. Wish they'd pull that in

**Comment by Jewhurst** [comment]
they just merged it in, so you can prob update and be good @robertclarkson

**Comment by robertclarkson** [comment]
Awesome. The power of social media!
https://twitter.com/IntuitDev/status/1116107859941445632

Thanks for that
