### ISSUE TITLE
Updated to Minor Version 36 - Error code="4002" - Error processing query - QueryProcessingError: To email address entered is invalid

### ISSUE THREAD

**Issue by icircletech** [intuit/QuickBooks-V3-PHP-SDK#216]
I recently updated from Minor Version 35 to 36 to see if the "ShipFromAddr" issue would be resolved. ( #195  ) After updating to 36, The "ShipFromAddr" issue goes away, however a new issue occurs. I get the following from intuit:

> [12-Apr-2019 13:54:02 UTC] The Status code is: 500

>[12-Apr-2019 13:54:02 UTC] The Helper message is: Invalid auth/bad request (got a 500, expected HTTP/1.1 20X or a redirect)

>[12-Apr-2019 13:54:02 UTC] The Response message is: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2019-04-12T06:54:02.693-07:00"><Fault type="Service"><Error code="4002"><Message>Error processing query</Message><Detail>QueryProcessingError: To email address entered is invalid</Detail></Error></Fault></IntuitResponse>

Any thoughts on how to resolve this issue?

**Comment by icircletech** [comment]
Updating QuickBooks-V3-PHP-SDK from 5.0.3 to 5.0.4 solved my issue for anyone else experiencing this issue.

**Comment by icircletech** [comment]
Error is Back, Same exact issue

**Comment by hlu2** [comment]
@icircletech  Mind post your request log and response log? I will take a look.

**Comment by hlu2** [comment]
Fixed.
