### ISSUE TITLE
PHP version and coding style

### ISSUE THREAD

**Issue by becquerel** [intuit/QuickBooks-V3-PHP-SDK#22]
This isn't much of an issue, it is more about general direction of this library/package, but I'm not sure where is a better place to put this. I have been working with QB SDK for past couple weeks, and I will for few more, so I am happy to push few pull requests here and there if I run into anything that helps me (because it could help somebody else too)

However (so far I have made only couple bugfixes and typos and PHPDoc comments), I would like to clear up few things. I will write my suggestions, but I am ok to adhere to decisions @hlu2 or community will agree on.

1) code style. Currently, library is kind of a mix of all different styles, weird indentation in many places. I would propose using PSR-1 and PSR-2 standards going forward where possible. I understand, that not everything can be updated due to BC breaks (for example method names on `DataService` like `public function Query(...)` - changing these to follow PSR would break many apps out there), but in the places where it is possible, I would suggest using PSR as much as possible (while 100% maintaining backwards compatibility of a public methods)

2) PHP version. Most of the code is PHP 5.3 compatible. However, in `composer.json`, min. supported PHP version is 5.6.0 and this is even mentioned in docs. Can we use the full 5.6.0 feature set going forward ? Or should we stick to 5.3.0 ? This is a tough call, package would not even install using composer, but people may still download it manually and use it (even though, nobody should be really using php 5.3 nowadays anymore ...). I would recommend allowing at least 5.5 (this by itself would allow some deeper refactoring and making the code more maintainable due to short array syntax, perhaps traits and `::class` for class name resolutions, instead of strings). 5.6 seems reasonable to me, since even docs mention it as a requirement.

3) removing commented code. There are instances where old code that should no longer be active is just commented out. While this makes kind of sense for library not on github (or version controlled in general), I would propose removing all unused code / variables / etc., to make code more readable (commented code rarely makes it back to production anyway, and if there is a need to bring it back, we have git history for that)

I would have more ideas, but I think this is more than enough for start

**Comment by hlu2** [comment]
@becquerel 
Thanks for the valid feedback. Believe it or not, all of them are in my working list, especially for your point 2 and 3. Right now, my first priority is still remove the PECL OAuth extension requirement; once I have that part done, I will work on upgrading all legacy codes from PHP 5.3 to PHP 5.6(without breaking existed behaviors)

You are free to send a pull request for point 3. As long as it is not in the /core/HttpClients/ folder and /dataService folder 

Best,
Hao

**Comment by becquerel** [comment]
@hlu2 perfect, thank you
