### ISSUE TITLE
Cannot generate access token

### ISSUE THREAD

**Issue by Dbinutu** [intuit/QuickBooks-V3-PHP-SDK#222]
I have gone through the sample code, I have been able to successfully redirect to and from intuit server after clicking the connect button. When I look at my callback url , I realized that `$_SERVER['QUERY_STRING']` is empty, and `parseAuthRedirectUrl` gives error because code is not defined in `$qsArray['code']`.

Please note that I am using a development environment and pretty url's like `mysite/some-link`.

Thank you!

**Comment by hlu2** [comment]
@Dbinutu 
Try to run your website through ngrok: https://ngrok.com/
It may be a certificate issue.

Then use:
```
$queries = array();
parse_str($_SERVER['QUERY_STRING'], $queries);
```
