### ISSUE TITLE
XmlObjectSerializer::getXmlFromObj using $this error...

### ISSUE THREAD

**Issue by TechnologySolutionsGroup** [intuit/QuickBooks-V3-PHP-SDK#223]
This "static" function uses "$this" if there's an exception. Also "IDSLogger" could be null, but it's not checked before attempting to log the exception.

**Comment by suddenTim** [comment]
Ran into this same problem.

**Comment by hlu2** [comment]
https://jira.intuit.com/browse/IDG-3011

**Comment by hlu2** [comment]
It is fixed.

**Comment by stri8ed** [comment]
> jira.intuit.com/browse/IDG-3011

That link is down. Any more information on when/where this was fixed?
