### ISSUE TITLE
Lose information in the Name(AccountRef) field after deserialization

### ISSUE THREAD

**Issue by sidikhalifa** [intuit/QuickBooks-V3-PHP-SDK#226]
hello, 

I want to call QBO API to get `JournalEntry` Entities, but I have a problem with the `Name` field, like next image, I'm losing information:

![FireShot Capture 005 - New Issue · intuit_QuickBooks-V3-PHP-SDK - github com](https://user-images.githubusercontent.com/14994150/58802595-dc495100-860d-11e9-8cd4-0a4fd14d8be0.png)

Before `Deserialize` response : 
![FireShot Capture 007 -  - local short-edition com](https://user-images.githubusercontent.com/14994150/58803325-79f15000-860f-11e9-824e-fada248faada.png)

After Deserialize : 

![FireShot Capture 009 -  - local short-edition com](https://user-images.githubusercontent.com/14994150/58803617-3b0fca00-8610-11e9-94bf-7125f50577d5.png)

I'm losing this information !

I use `Symfony 4.2` and `"quickbooks/v3-php-sdk": "dev-master"`,

Thanks
Sidi

**Comment by hlu2** [comment]
@sidikhalifa 
This is a feature that will be fixed in the new Quickbooks PHP SDK. For current SDK, fixing the xml conversion issue(fix the library) will cause code break.
