### ISSUE TITLE
FIG/PSR compliance

### ISSUE THREAD

**Issue by TimOgilvy** [intuit/QuickBooks-V3-PHP-SDK#227]
Hello Hao and team!

I had the privilege of meeting some of your lovely colleagues at QuickBooks Connect in Melbourne Australia this week. They all speak very highly of you, and I was impressed by their enthusiasm.

I'd like to look into helping you get this repo to FIG PSR-2 compliance. Is this something you are open to?  I'd rather not start and put a PR in before I have a sense of your position on this.

https://www.php-fig.org/psr/psr-2/ 

I'm sure you're working on a number of features and so on. Is there a spot in the timeline which might best make sense for this?

**Comment by hlu2** [comment]
Online meeting scheduled. Not bug related. close.
