### ISSUE TITLE
it's an infinite loop!

### ISSUE THREAD

**Issue by rimoi** [intuit/QuickBooks-V3-PHP-SDK#229]
Hello, 
I tried but it's an infinite loop! 

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/1ca3ffe35fb54c053ce67adc99442484b1eab766/src/_Samples/CustomersFindAll.php#L28

I think it's rather : 
` $allCustomers = $dataService->FindAll('Customer', $i * 500, 500); `

what do you think?

thanks
sidi

**Comment by hlu2** [comment]
story added:
https://jira.intuit.com/browse/IDG-3010

**Comment by sidikhalifa** [comment]
page not found!

**Comment by hlu2** [comment]
@rimoi  The $i is page number here. Check your code. It shouldn't be an infinite loop.
