### ISSUE TITLE
Can you add a line to an invoice without overwriting the line thats already there?

### ISSUE THREAD

**Issue by ryanbarsatan** [intuit/QuickBooks-V3-PHP-SDK#23]
Hi, I'm creating invoices and I have a dynamic amount of lines that need to be created. Using the update for line will overwrite the existing line. Is there a way to add lines without overwriting them? Thanks in advance.

**Comment by becquerel** [comment]
@ryanbarsatan I'm not  sure if this will answer your question, but this is how I am creating invoices with dynamic number of lines:

``` php
        $qbEntity = new QuickBooksOnline\API\Data\IPPInvoice;
        ...
        $qbEntity->Line = []; // lines are empty array

        $i = 0;
        foreach ($invoiceItemsLoadedFromSomewhere as $invoiceItem) {
            // add a new line to array of lines
            $qbEntity->Line[] = new \QuickBooksOnline\API\Data\IPPLine([
                'LineNum' => $i,
                'Description' => $invoiceItem->getDescription(),
                'Amount' => (float)$invoiceItem->getTotal(),
                'DetailType' => 'SalesItemLineDetail',
                'SalesItemLineDetail' => new \QuickBooksOnline\API\Data\IPPSalesItemLineDetail([
                    'ItemRef' => new \QuickBooksOnline\API\Data\IPPReferenceType([
                        'value' => $qbItemFerefenceId,
                        'name' => 'Advertising'
                    ]),
                    'UnitPrice' => $invoiceItem->getPrice(),
                    'Qty' => $invoiceItem->getQuantity()
                ])
            ]);
        }

        /** @var QuickBooksOnline\API\DataService\DataService $quickbooksClient ?>
        $quickbooksClient->Add($qbEntity); // or ->Update($qbEntity); depending on the operation I need to do

```

This deals with `SalesItemLineDetail` type, but you get the idea. When updating an existing invoice, I think you need to also provide `Id` of each item to be updated (or if you omit the `Id` from individual lines, then new items would be created)

Does this answer your question ?

**Comment by ryanbarsatan** [comment]
@becquerel This is exactly what I was trying to do! Thanks a bunch, I didn't realize I could reference Line like that.

**Comment by hlu2** [comment]
@ryanbarsatan 
"Line" will also be included in the Facade List later for easy programming purpose. I will include examples in the README file once it is available. Please check the progress from wiki page: https://github.com/intuit/QuickBooks-V3-PHP-SDK/wiki

**Comment by khyatibhojawala** [comment]
hey @becquerel can you please tell me how can I add Customer Email using your array?
