### ISSUE TITLE
Improvement: Allow option to set TLS version

### ISSUE THREAD

**Issue by alexjeen** [intuit/QuickBooks-V3-PHP-SDK#233]
I see in BaseCurl the following function:

    /**
    * Set the curl TLS Version and check if TLS 1.2 is supported
    * @return int TLSversion
    */
    public function versionOfTLS(){
        $tlsVersion = "";
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, "https://www.howsmyssl.com/a/check");
        curl_setopt($curl, CURLOPT_SSLVERSION, 6);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        $curlVersionResponse = curl_exec($curl);
        if($curlVersionResponse === false){
            throw new SdkException("Error in checking cURL version for TLS 1.2. Error Num:[" . curl_errno($curl) . "] Error message:[" . curl_error($curl) . "]");
        }else{
             $tlsVersion = json_decode($curlVersionResponse)->tls_version;
        }
        curl_close($curl);
        return $tlsVersion;
    }

I also see this function is called prior to every call to the QBO API this causes a lot of overhead and sometimes:

    Quickbooks error: QuickBooksOnline\API\Exception\SdkException: [0]: Error in checking cURL version for TLS 1.2. Error Num:[6] Error message:[Could not resolve host: www.howsmyssl.com

Is it not better to make this an option in the PHP SDK so you can set this if you are sure about your TLS version (because we containerize the images we have full control).

**Comment by hlu2** [comment]
Fixed.
