### ISSUE TITLE
Undefined index: Content-Type

### ISSUE THREAD

**Issue by Nks** [intuit/QuickBooks-V3-PHP-SDK#237]
`/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/SyncRestHandler.php` 
270 row

Here the headers:
``` "date" => "Wed, 17 Jul 2019 16:31:09 GMT"
  "content-type" => "application/xml;charset=UTF-8"
  "server" => "nginx"
  "strict-transport-security" => "max-age=15552000"
  "intuit_tid" => "ad5f9bcd-9325-4b35-bb79-09f3bea9fd39"
  "set-cookie" => "JSESSIONID=4AFACBDE0623B7F206C0AF71AF703942.c41-pprdc41uw2apv090094-stack-a; Domain=qbo.intuit.com; Path=/; Secure; HttpOnly"
  "qbo-version" => "1915.183"
  "service-time" => "total=209, db=28"
  "expires" => "0"
  "cache-control" => "max-age=0, no-cache, no-store, must-revalidate, private"
  "vary" => "Accept-Encoding"
  "x-xss-protection" => "1; mode=block"
```

But in CoreConstants::CONTENT_TYPE we have ```Content-Type```.
Then ```$httpHeaders[CoreConstants::CONTENT_TYPE]``` will return error: ```Undefined index: Content-Type```

**Comment by tariqwiztech** [comment]
I am facing the same issue :(

**Comment by msankar1991** [comment]
Same issue I'm also getting now

**Comment by virendrachandak** [comment]
This is duplicate of #236 where a solution is provided. Hopefully this will be fixed in the next version.

**Comment by diana-derose** [comment]
Hi - Can one of you provide the company id for which you are getting the incorrect headers?

**Comment by Nks** [comment]
> Hi - Can one of you provide the company id for which you are getting the incorrect headers?

I can't because of NDA but why just not simply make a ```strtolower``` for all headers like this done in #236?

Of course this is just a notice which can be hidden by adding ```error_reporting(error_reporting() & ~E_NOTICE);``` before configuring the service.

**Comment by Nks** [comment]
Also I think this is really bad behavior when the system breaking on the log.

**Comment by diana-derose** [comment]
Yes, we'll update the SDK to fix the lower case issue too but we were trying to solve the root cause than adding a patch here. We are unable reproduce it with any of our trial companies which makes us think this is happening for special kind of requests, hence the ask to share additional details.

**Comment by hlu2** [comment]
If the issue still persist, re-open this issue.
