### ISSUE TITLE
ServiceContext::ConfigureFromPassedArray leaves IppConfiguration->baseUrl->Ipp NULL

### ISSUE THREAD

**Issue by mjhca** [intuit/QuickBooks-V3-PHP-SDK#24]
Configuring **ServiceContext** using **ServiceContext::ConfigureFromPassedArray()** leaves platform services base URL null.  So using that ServiceContext to initialize a PlatformService and make a request fails because the URL for IPP is invalid.

This is inconsistent with configuring from sdk.config file which passes an "ipp" value of "https://appcenter.intuit.com/api/" in the examples.

**Suggestion:**
1) ServiceContext::ConfigureFromPassedArray should accept an ippBaseUrl value.  This is passed to LocalConfigReader::ReadConfigurationFromParameters() which should then set the value in IppConfiguration->BaseUrl->Ipp
2) Why not default /src/Core/Configuration/BaseUrl.php $ipp property to https://appcenter.intuit.com/api/ ?  It doesn't change between sandbox and production anyway.

**Comment by hlu2** [comment]
@mjhca 
You are right. It will be changed at next release.

Thanks
hao

**Comment by hlu2** [comment]
@mjhca 
Hi Mjhca, this has been fixed. 

Thanks
Hao
