### ISSUE TITLE
Unable to use InvoiceRef in CreditMemos

### ISSUE THREAD

**Issue by lemnisk8** [intuit/QuickBooks-V3-PHP-SDK#242]
For GST compliance in India linking the creditmemos to invoices is required.

The API explorer has an option for InvoiceRef
https://www.developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/creditmemo

<img width="646" alt="Screenshot 2019-08-07 at 3 01 36 pm" src="https://user-images.githubusercontent.com/1185625/62612019-4f2fba80-b924-11e9-8b70-900451e62088.png">

I doesn't seem to  have been implemented in this SDK as yet.

I would be glad if someone could point me in right direction, to implement it so I can start using it, and create a pull request.

Thanks

**Comment by lemnisk8** [comment]
Figured how to add it the invoice ref. 

As Its in the minor version 37, the minorVersion needs to be set when making the API call.
`$dataService->setMinorVersion("37");`

Created a pull request if any one needs it...
https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/243

Cheers

**Comment by ssbannaji** [comment]
I am getting Same issues in Python and Postman also.
I had pass InvoiceRef in request but in response not showing  InvoiceRef.
Anyone faced the same issue ?

**Comment by ssbannaji** [comment]
Below is my Code 
       invoice = Invoice.get(invoiceId, qb=client)
       credit_memo.InvoiceRef = invoice.to_ref()
