### ISSUE TITLE
Migration Fails

### ISSUE THREAD

**Issue by hyperiums** [intuit/QuickBooks-V3-PHP-SDK#244]
This method OAuth1ToOAuth2Migration has the redirectUri hard coded which is fine for development but in production it will fail. There is no way to over ride it either. One possible solution is to change scope to be an array of params or add a new param called params so implementation teams can override it easily. Otherwise, the library works great.

**Comment by hyperiums** [comment]
Or use the redirect uri from the constructor. That would probably be simpler.

**Comment by hyperiums** [comment]
Just realized that $baseURL in this method is hard coded to the prod end point as well which means you can't switch back and forth easily.

**Comment by hlu2** [comment]
@hyperiums I will fix it.
