### ISSUE TITLE
Migration RealmId Not Parsed

### ISSUE THREAD

**Issue by hyperiums** [intuit/QuickBooks-V3-PHP-SDK#245]
OAuth2LoginHelper.php method: OAuth1ToOAuth2Migration
```
else{
           $this->faultHandler = false;
           $this->oauth2AccessToken = $this->parseNewAccessTokenFromResponse($intuitResponse->getBody());
           return $this->getAccessToken();
        }
```
The parse access token actually will have the realmId in the body and could set it. This method could get it from the body if it isn't passed in to preserve backwards compatibility while allowing people who might want to use it later easy access to the one their response just received. I could see an argument for not including it since it isn't needed for refreshing the token but during the migration you might not have it. I wanted to call it out so it could be examined by a maintainer. Thanks.

**Comment by bsivalingam** [comment]
@hyperiums Closing the issue since we are past the migration phase.
