### ISSUE TITLE
Encountered an error parsing the batch response.Namespace Error

### ISSUE THREAD

**Issue by caalvinz** [intuit/QuickBooks-V3-PHP-SDK#248]
Hi, is there anyone can give me a hand?

I tried to submit an invoice to Quickbooks through API calling. An error was popped up:
`
Stack Trace: #0 /var/www/html/syntac/app/vendor/quickbooks/v3-php-sdk/src/XSD2PHP/src/com/mikebevz/xsd2php/Php2Xml.php(161): DOMDocument->createElementNS('http://schema.i...', 'ns0:')
#1 /var/www/html/syntac/app/vendor/quickbooks/v3-php-sdk/src/XSD2PHP/src/com/mikebevz/xsd2php/Php2Xml.php(89): QuickBooksOnline\API\XSD2PHP\src\com\mikebevz\xsd2php\Php2Xml->parseClass(Object(stdClass), Object(DOMDocument), true)
#2 /var/www/html/syntac/app/vendor/quickbooks/v3-php-sdk/src/Core/Http/Serialization/XmlObjectSerializer.php(50): QuickBooksOnline\API\XSD2PHP\src\com\mikebevz\xsd2php\Php2Xml->getXml(Object(stdClass))
#3 /var/www/html/syntac/app/vendor/quickbooks/v3-php-sdk/src/Core/Http/Serialization/XmlObjectSerializer.php(78): QuickBooksOnline\API\Core\Http\Serialization\XmlObjectSerializer::getXmlFromObj(Object(stdClass))
#4 /var/www/html/syntac/app/vendor/quickbooks/v3-php-sdk/src/Core/Http/Serialization/XmlObjectSerializer.php(203): QuickBooksOnline\API\Core\Http\Serialization\XmlObjectSerializer::getPostXmlFromArbitraryEntity(Object(stdClass), 'class')
#5 /var/www/html/syntac/app/vendor/quickbooks/v3-php-sdk/src/DataService/DataService.php(1185): QuickBooksOnline\API\Core\Http\Serialization\XmlObjectSerializer->Serialize(Object(stdClass))
#6 /var/www/html/syntac/app/vendor/quickbooks/v3-php-sdk/src/DataService/DataService.php(779): QuickBooksOnline\API\DataService\DataService->executeObjectSerializer(Object(stdClass), NULL)
#7 /var/www/html/syntac/app/Application/Backend/Controller/Order/OrderController.class.php(980): QuickBooksOnline\API\DataService\DataService->Add(Object(stdClass))
#8 /var/www/html/syntac/app/Application/Backend/Controller/Order/OrderController.class.php(712): Backend\Controller\Order\OrderController->syncToQuickbooks('14')
#9 [internal function]: Backend\Controller\Order\OrderController->ajax_quickbooks()
#10 /var/www/html/syntac/app/Core/Library/Think/App.class.php(166): ReflectionMethod->invoke(Object(Backend\Controller\Order\OrderController))
#11 /var/www/html/syntac/app/Core/Library/Think/App.class.php(208): Think\App::exec()
#12 /var/www/html/syntac/app/Core/Library/Think/Think.class.php(122): Think\App::run()
#13 /var/www/html/syntac/app/Core/ThinkPHP.php(98): Think\Think::start()
#14 /var/www/html/syntac/app/index.php(40): require('/var/www/html/s...')
`

codes:
`
        $dataService->updateOAuth2Token($accessToken);

        $obj = new IPPInvoice();
        $invoice->AutoDocNumber="1"; //Invoice number generated by QB 

        //Assign Customer to the invoice
        $customerRef = new IPPReferenceType();
        $customerRef->value = $customerID
        $invoice->CustomerRef = $customerRef;
        $invoice->TotalAmt = $info['total'];
        $invoice->Balance = $info['total'];
        $line_number = 0;
        $items = [];
        foreach($info['lines'] as $line) {
            $line_number = $line_number + 1;
            //New Invoice Line
            $IPPLine = new IPPLine();
            $IPPId = new IPPReferenceType(); //Reference type of all IDs that are taken as input or output
            $IPPId->value = "4";
            $IPPLine->Id = $IPPId;
        
            $IPPLine->LineNum = $line_number;
            $IPPLine->Description = $line['product_name']
            $IPPLine->Amount = (float)($line['total']);
            $enum = new IPPLineDetailTypeEnum();
            $enum->value = "DescriptionOnly";
            $IPPLine->DetailType = $enum;
            
            array_push($items, $IPPLine); 
        }
        $invoice->Line = $items;
        //Add Invoice to quickbooks
        try {
            $resultingInvoiceObj = $dataService->Add($invoice);
        } catch (Exception $e) {
            echo('<pre>'); print_r($e); echo('</pre>');
        }
`

appreciate for any information.

**Comment by hlu2** [comment]
@caalvinz Can you create a support ticket at https://help.developer.intuit.com/s/ with the same information? We now track all our github issues on salesforce.
