### ISSUE TITLE
Php2Xml should throw an exception if invalid entity is passed ?

### ISSUE THREAD

**Issue by becquerel** [intuit/QuickBooks-V3-PHP-SDK#25]
I was creating an invoice, and passed `DateTime` instance, instead of the invoice date as a string. `Php2Xml` just threw a notice when trying to process the entity. Am I correct to assume that only entities that have `IPPIntuitEntity` as a parent can be processed ? If so, it would be nice if we can get an actual exception when invalid entity is passed, instead of notice and silent fail

**Comment by becquerel** [comment]
it could be some entity validator kicking in before entity is passed to `Php2Xml` library (which should be ideally moved to composer dependency and removed from package completely)

**Comment by hlu2** [comment]
@becquerel 
PHP2XML is not available in composer so I can't add it as a dependency. Substitution of PHP2XML with a newer library is my preferred plan. I don't think it is the IPPIntuitEntity that cause the issue, it is the code. I will take a look and see what the cause of it. It should throw an exception.

I have created a temp wiki page to record known issues and my progress, https://github.com/intuit/QuickBooks-V3-PHP-SDK/wiki, hope it give community a better idea of the progress.

**Comment by hlu2** [comment]
@becquerel David, it will be on my next working list.

**Comment by hlu2** [comment]
Just want to update the progress, I may need to reconsider how to resolve it with issue #38, since the Deserialization do not take the attributes into consideration, and changing it has too much of work.

**Comment by josephzidell** [comment]
Is #41 related?

**Comment by hlu2** [comment]
Now The SDK handles the DateTime correctly.
