### ISSUE TITLE
Refresh OAuth 2 Access token with Refresh Token failed. Body: [{"error":"invalid_grant"}]

### ISSUE THREAD

**Issue by hriziya** [intuit/QuickBooks-V3-PHP-SDK#259]
I am facing same problem like https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/240 I have already followed same code logic as mentioned there.. 
In my case, I can get the new `AccessToken` from `RefreshToken` in **Development** mode.. but when I use the **Production** mode, this logic does not work and throws the `invalid_grant` error. 
here is exact error details.
![image](https://user-images.githubusercontent.com/4135216/68663159-3575c300-0564-11ea-8082-1933b546f648.png)

The only thing I am not sure about is, why it is throwing an error only for Production mode and how come it works for Development mode?

Can anybody help me with this?

Thanks

**Comment by antonyanand** [comment]
I have the same problem if you had solved this, please let me know. @hriziya

**Comment by hlu2** [comment]
This error usually happened when the configuration is not correct. Check the keys, base URL, environment and realmID you used. One of them probably is used for development mode, not for production.
