### ISSUE TITLE
DataService SendEmail does not attach PDF invoice

### ISSUE THREAD

**Issue by lmorroni** [intuit/QuickBooks-V3-PHP-SDK#26]
The invoice gets emailed and the email references an attached invoice but there is only the link, not an actual PDF attached.  
I call something like this:
`$qb_client->SendEmail($theInvoice,$customer['email']);`

**Comment by hlu2** [comment]
Hi @lmorroni 
It should be a download PDF. Could you forward your E-mail to my E-mail address: Hao_Lu@intuit.com?

**Comment by hlu2** [comment]
@lmorroni 
Hi Larry, thanks for forwarding me the E-mail. The product and sandbox has different view of SendEmail Page. If you use Product QBO, the downloadPDF is within the "Pay Invoice" button. In sandbox, it is in the E-mail itself. If you go to the "Pay Invoice" page, you should see the "download PDF" option there
