### ISSUE TITLE
Cannot get tax to update on invoice? What is wrong with my code?

### ISSUE THREAD

**Issue by tone10** [intuit/QuickBooks-V3-PHP-SDK#263]
$targetInvoiceArray = $dataService->Query("select * from Invoice where DocNumber='$invoice_number'");
if(!empty($targetInvoiceArray) && sizeof($targetInvoiceArray) == 1){
    $theInvoice = current($targetInvoiceArray);

$updatedInvoice = Invoice::update($theInvoice, [
    "sparse" => true,
    "Id" => "1",
    "SyncToken" => "9",
    "TxnTaxDetail" => [
        "TaxLine"=> [[
           "Amount"=> $total_tax,
           "DetailType"=> "TaxLineDetail",
           "TaxLineDetail"=> [
              "TaxRateRef"=> [
                   "value"=> $total_rate,
                   "name"=> "Sales Tax"
              ],
              "PercentBased"=> true,
              "TaxPercent"=> $total_rate,
              "NetAmountTaxable"=> $taxable_amount
           ]
        ]],
        "TotalTax"=> $total_tax,
    ]]);
$updatedResult = $dataService->Update($updatedInvoice);

**Comment by hlu2** [comment]
@tone10  Can you enable the logging and post the request log and response log here?

**Comment by bsivalingam** [comment]
@tone10 Please reopen the issue if you are still encountering this.
