### ISSUE TITLE
cannot set Job=0, ParentRef=null on Customer

### ISSUE THREAD

**Issue by kaeverens** [intuit/QuickBooks-V3-PHP-SDK#265]
I'm working through making sure customer/child references are respected in a sync, and the one thing I just can't seem to figure out is how to turn off "Job" mode on a customer once it has been set.

within the qbo website, it's possible, by simply unticking "Is sub-customer" on a Customer and saving the Customer, but how do I do it via API?

the "obvious" answer would be to set 'Job'=false and 'ParentRef'=null, but I get an fatal error message back if I try that: `Can't convert Passed Parameter to IPPReferenceType`

so what if I use 0 for the ParentRef? now I get this error message: `"Error":{"@attributes":{"code":"6150","element":"Job"},"Message":"ParentRef Required Error","Detail":"ParentRef is either required or not if Job is true or false."}` <-- while that looks like English, it doesn't actually contain any information...

if I try setting ParentRef to false, I get another fatal error: `Can't convert Passed Parameter to IPPReferenceType`

so how do I convert a sub-customer back into a top-level customer?

**Comment by bsivalingam** [comment]
@kaeverens can you please create a support ticket here: https://help.developer.intuit.com/s/
