### ISSUE TITLE
Invalid auth/bad request (got a 502, expected HTTP/1.1 20X or a redirect)

### ISSUE THREAD

**Issue by derekjosepholson** [intuit/QuickBooks-V3-PHP-SDK#266]
Context: 
PHP version: 7.2.21
Using updated library version as of December 11th 2019.

I have tested my app with sandbox info and it was working as expected. When I changed to production keys I was still able to authenticate successfully. The problem comes when I try to execute a report for a user. I am also not using a sandbox account for testing production keys so that's not my issue. 

Here's a look at my code being used. $report ends up being set to null and this is the error I get "Invalid auth/bad request (got a 502, expected HTTP/1.1 20X or a redirect)". I have made sure ClientID, ClientSecret, accessTokenKey, and QBORealmID are all matching the correct values. start and end date are formatted properly. In this case they are 2019-12-09 and 2019-12-12.
$report_type = ‌'ProfitAndLoss'

`$dataService = DataService::Configure(array(
        'auth_mode' => 'oauth2',
        'ClientID' => $qbo_prod_client_id,
        'ClientSecret' => $qbo_prod_client_secret,
        'accessTokenKey' => $token,
        'QBORealmID' => $company_id,
        'baseUrl' => "https://api.intuit.com"
    ));

    $serviceContext = $dataService->getServiceContext();

    $reportService = new ReportService($serviceContext);
    if (!empty($reportService)) {
        $reportService->setStartDate($start_date);
        $reportService->setEndDate($end_date);
        //$reportService->setAccountingMethod("Accrual");
        $reportService->setSummarizeColumnBy($summarize_by);

        $report = $reportService->executeReport($report_type);
      }

**Comment by hlu2** [comment]
@derekjosepholson your baseUrl seems incorrect for me. 
can you try:
`'baseUrl' => "Production"`
