### ISSUE TITLE
Notice in Php2Xml

### ISSUE THREAD

**Issue by igorfialko** [intuit/QuickBooks-V3-PHP-SDK#267]
Seems like this line doesn't do anything in particular. Can be removed?
https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/XSD2PHP/src/com/mikebevz/xsd2php/Php2Xml.php#L268

**Comment by bsivalingam** [comment]
Fair. Since it is not causing any issues for now, we do not plan on fixing it.

**Comment by igorfialko** [comment]
@bsivalingam 
It does indeed. Sometimes the array's property is not defined and causes a notice. We use this a lot and our log gets full of it. As you can see further in the code similar array accesses are guarded with **isset**. That line looks like dead code to me. Is there any particular reason to spam notices by the code that does nothing?
