### ISSUE TITLE
Setting Customer->PrimaryEmailAddr does not work correctly

### ISSUE THREAD

**Issue by tupto** [intuit/QuickBooks-V3-PHP-SDK#27]
I believe this is an issue with the upload process (or maybe a validation error).

I set the PrimaryEmailAddr value, upload the object but the returned object does not have PrimaryEmailAddr set.

print_r of before upload:

    QuickBooksOnline\API\Data\IPPCustomer Object
    (
        [Taxable] => 
        [BillAddr] => 
        [ShipAddr] => 
        [OtherAddr] => 
        [ContactName] => 
        [AltContactName] => 
        [Notes] => 
        [Job] => 
        [BillWithParent] => 
        [RootCustomerRef] => 
        [ParentRef] => 
        [Level] => 
        [CustomerTypeRef] => 
        [SalesTermRef] => 
        [SalesRepRef] => 
        [TaxGroupCodeRef] => 
        [TaxRateRef] => 
        [PaymentMethodRef] => 
        [CCDetail] => 
        [PriceLevelRef] => 
        [Balance] => 
        [OpenBalanceDate] => 
        [BalanceWithJobs] => 
        [CreditLimit] => 
        [AcctNum] => 
        [CurrencyRef] => 
        [OverDueBalance] => 
        [TotalRevenue] => 
        [TotalExpense] => 
        [PreferredDeliveryMethod] => 
        [ResaleNum] => 
        [JobInfo] => 
        [TDSEnabled] => 
        [CustomerEx] => 
        [SecondaryTaxIdentifier] => 
        [ARAccountRef] => 
        [PrimaryTaxIdentifier] => 
        [IntuitId] => 
        [Organization] => 
        [Title] => 
        [GivenName] => Test
        [MiddleName] => 
        [FamilyName] => User
        [Suffix] => 
        [FullyQualifiedName] => 
        [CompanyName] => Test User Inc
        [DisplayName] => test@email.us
        [PrintOnCheckName] => 
        [UserId] => 
        [Active] => 
        [PrimaryPhone] => 
        [AlternatePhone] => 
        [Mobile] => 
        [Fax] => 
        [PrimaryEmailAddr] => test@email.us
        [WebAddr] => 
        [OtherContactInfo] => 
        [DefaultTaxCodeRef] => 
        [Id] => 
        [SyncToken] => 
        [MetaData] => 
        [CustomField] => 
        [AttachableRef] => 
        [domain] => 
        [status] => 
        [sparse] => 
    )

and a print_r of the returned object

    QuickBooksOnline\API\Data\IPPCustomer Object
    (
        [Taxable] => false
        [BillAddr] => 
        [ShipAddr] => 
        [OtherAddr] => 
        [ContactName] => 
        [AltContactName] => 
        [Notes] => 
        [Job] => false
        [BillWithParent] => false
        [RootCustomerRef] => 
        [ParentRef] => 
        [Level] => 
        [CustomerTypeRef] => 
        [SalesTermRef] => 
        [SalesRepRef] => 
        [TaxGroupCodeRef] => 
        [TaxRateRef] => 
        [PaymentMethodRef] => 
        [CCDetail] => 
        [PriceLevelRef] => 
        [Balance] => 0
        [OpenBalanceDate] => 
        [BalanceWithJobs] => 0
        [CreditLimit] => 
        [AcctNum] => 
        [CurrencyRef] => GBP
        [OverDueBalance] => 
        [TotalRevenue] => 
        [TotalExpense] => 
        [PreferredDeliveryMethod] => None
        [ResaleNum] => 
        [JobInfo] => 
        [TDSEnabled] => 
        [CustomerEx] => 
        [SecondaryTaxIdentifier] => 
        [ARAccountRef] => 
        [PrimaryTaxIdentifier] => 
        [IntuitId] => 
        [Organization] => 
        [Title] => 
        [GivenName] => Test
        [MiddleName] => 
        [FamilyName] => User
        [Suffix] => 
        [FullyQualifiedName] => test@email.us
        [CompanyName] => Test User Inc
        [DisplayName] => test@email.us
        [PrintOnCheckName] => Test User Inc
        [UserId] => 
        [Active] => true
        [PrimaryPhone] => 
        [AlternatePhone] => 
        [Mobile] => 
        [Fax] => 
        [PrimaryEmailAddr] => 
        [WebAddr] => 
        [OtherContactInfo] => 
        [DefaultTaxCodeRef] => 
        [Id] => 82
        [SyncToken] => 0
        [MetaData] => QuickBooksOnline\API\Data\IPPModificationMetaData Object
            (
                [CreatedByRef] => 
                [CreateTime] => 2017-06-01T08:22:10-07:00
                [LastModifiedByRef] => 
                [LastUpdatedTime] => 2017-06-01T08:22:10-07:00
                [LastChangedInQB] => 
                [Synchronized] => 
            )

        [CustomField] => 
        [AttachableRef] => 
        [domain] => 
        [status] => 
        [sparse] => 
    )

**Comment by becquerel** [comment]
@tupto I think the problem is that `PrimaryEmailAddr` should not be a string, but a `\QuickBooksOnline\API\Data\IPPEmailAddress` instance instead.

When I create a customer, I set email address this way:

``` php
$customer = new QuickBooksOnline\API\Data\IPPCustomer;
...
$customer->PrimaryEmailAddr = new \QuickBooksOnline\API\Data\IPPEmailAddress([
    'Address' => 'test@email.us'
]);
```

**Comment by hlu2** [comment]
@becquerel Thanks for pointing it out david.
For all future readers: 
Please refer to the class library here: https://developer-static.intuit.com/SDKDocs/QBV3Doc/IPPPHPDevKitV3/index.html to refer to the class fields. Some of them are objects while some of them are strings/integers.
