### ISSUE TITLE
InvoiceLink no longer returned from DataService call

### ISSUE THREAD

**Issue by evancrose** [intuit/QuickBooks-V3-PHP-SDK#276]
When looking up transactions, InvoiceLink is always blank now whereas before it was a usable URL. How can we properly get the InvoiceLink for transactions that have been sent? It used to propagate but it seems the data is no longer available in the API. We're using 5.3.1, I checked commit history and don't see anything that corresponds to InvoiceLink.

**Comment by tsoslow** [comment]
I'm seeing the same issue. The API Explorer does correctly return an InvoiceLink for the same record.

**Comment by tsoslow** [comment]
It looks like the API no longer returns InvoiceLink from a query by default. You would have to add it to the includes list and I'm not sure if the PHP SDK has that ability.

I was able to fix it for my needs since I'm only looking up a single invoice. Instead of making a query call, do the following: FindById("invoice", $id)

**Comment by bsivalingam** [comment]
@evancrose & @tsoslow The API was updated to not return the invoiceLink by default, we now require to pass a get parameter. We have a backlog story to update the SDK, it has not been prioritized yet, please feel free to create a PR and we will merge it in.

**Comment by evancrose** [comment]
> @evancrose & @tsoslow The API was updated to not return the invoiceLink by default, we now require to pass a get parameter. We have a backlog story to update the SDK, it has not been prioritized yet, please feel free to create a PR and we will merge it in.

Done:

https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/283
