### ISSUE TITLE
Error in checking cURL version for TLS 1.2. Error Num:[7] Error message:[Failed to connect to www.howsmyssl.com port 443: Connection refused]

### ISSUE THREAD

**Issue by katerina-n** [intuit/QuickBooks-V3-PHP-SDK#277]
Hi there,
Faced a problem: once in a few months an «Error in checking cURL version for TLS 1.2. Error Num:[7] Error message:[Failed to connect to www.howsmyssl.com port 443: Connection refused]» error appears. But after 5-10 minutes and page reloading it is gone by itself. TLS version is 1.2, checked twice. The error appears during execution of $curlVersionResponse = curl_exec($curl); in a versionOfTLS method. Any thoughts of what it might be caused by?

Thanks a lot in advance.

**Comment by rogerd330** [comment]
I ran into this recently on 1/29/20 around 10:50am CST it seems the www.howsmyssl.com was unavailable for 5 minutes, causing this payment SDK to stop working.

**Comment by MrHeart** [comment]
As it stands howsmyssl.com is down causing this library to fail perpetually. Is there any plan to replace howsmyssl.com? Their downtime is getting too much. For hours now, they're still not up

**Comment by bsivalingam** [comment]
@MrHeart What is the version of SDK you are on? We updated the SDK to not use howsmyssl in the release 5.3.5. Can you please pull the latest version of the SDK?
