### ISSUE TITLE
How to create a new PaymentMethod using the API

### ISSUE THREAD

**Issue by chethankswamy** [intuit/QuickBooks-V3-PHP-SDK#278]
Hi,
I am not able to find how to create a new PaymentMethod using the QuickBooks-V3-PHP-SDK, it's not mentioned in the sample codes either, can you please let me know how I can do this.
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/paymentmethod

Thank you

**Comment by Er-Kalpesh** [comment]
checkout \QuickBooksOnline\API\Facades\Payment::create($data);

**Comment by chethankswamy** [comment]
Hi, 
\QuickBooksOnline\API\Facades\Payment::create($data); is used to create "Payment" object to record a payment right.
Can I use the same to create a new PaymentMethod?
I did try but got following error,
"Property Name does not exist"
Request:
QuickBooksOnline\API\Facades\Payment::create( Array
(
    [Name] => My CC
    [Active] => 1
    [Type] => NON_CREDIT_CARD
)

**Comment by bsivalingam** [comment]
@chethankswamy We do not have a Facade for PaymentMethod at the moment. I have added it to our backlog to add one(ticket reference IDG-3446). If you like you can contribute to the repo, we will review the code and merge it.
