### ISSUE TITLE
create purchase order sample is missing here

### ISSUE THREAD

**Issue by Er-Kalpesh** [intuit/QuickBooks-V3-PHP-SDK#279]
the first thing is to create a purchase order sample that is missing here.

but if I try to implement it using API documentation I am getting an error :
```
"Error": [
   {
    "Message": "A business validation error has occurred while processing your request",
    "Detail": "Business Validation Error: Please enter a valid email address.",
    "code": "6000",
    "element": ""
   }
  ],
```

also I tried to add `"EmailStatus" => 0`
but it becomes like
```
[EmailStatus] => QuickBooksOnline\API\Data\IPPEmailStatusEnum Object
        (
            [value] => 0
        )
```
and in json it passes like:
```
"EmailStatus": {
    "value": 0
  },
```
instead of `"EmailStatus": 0`
not sure how to fix it. I am using v5.3.3

**Comment by bsivalingam** [comment]
@Er-Kalpesh I can't tell for sure what is causing this error without seeing the payload you are sending through. For API errors, can you please create a support ticket at https://help.developer.intuit.com/s/ ? Can you please also include the intuit_tid of the error response?

**Comment by Er-Kalpesh** [comment]
@bsivalingam I have created ticket there
https://help.developer.intuit.com/s/question/0D54R00006usaZNSAY/i-am-creating-purchase-order-using-guidelineshttpsdeveloperintuitcomappdeveloperqbodocsapiaccountingallentitiespurchaseordercreateapurchaseorderstill-getting-error-business-validation-error-please-enter-a-valid-email-addres?t=1580811040023

but I am using sdk and its issue in sdk 
If i use api in postman its working fine

**Comment by Er-Kalpesh** [comment]
```
$poData = [
    **"EmailStatus" => 0,**
    "APAccountRef" => [
        "value" => $accounts->id,
        "name" => $accounts->name
    ],
    "Line" => $line_items,
    "VendorRef" => [
        "value" => $objectData->value,
        "name" => $objectData->nickname
    ],
    "TotalAmt" => empty($total) ? 0 : $total,
    "DocNumber" => $objectData->id,    
];
$inputObjData = PurchaseOrder::create($poData);
```

here is the my code

**Comment by ajkreuer** [comment]
> ```
> $poData = [
>     "EmailStatus" => 0,            // <<<<<<<------- Here we have to focus
>     "APAccountRef" => [
>         "value" => $accounts->id,
>         "name" => $accounts->name
>     ],
>     "Line" => $line_items,
>     "VendorRef" => [
>         "value" => $objectData->value,
>         "name" => $objectData->nickname
>     ],
>     "TotalAmt" => empty($total) ? 0 : $total,
>     "DocNumber" => $objectData->id,    
> ];
> $inputObjData = PurchaseOrder::create($poData);
> ```
> 
> here is the my code

It looks like there's 3 valid values for Email status of the purchase order.

**Valid values:** `NotSet`, `NeedToSend`, `EmailSent`

[Reference](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/purchaseorder#full-update-a-purchase-order)

**Comment by Er-Kalpesh** [comment]
@ajkreuer  thanks that works
