### ISSUE TITLE
Can get CompanyInfo, but UserInfo not working

### ISSUE THREAD

**Issue by roel018** [intuit/QuickBooks-V3-PHP-SDK#281]
Hello,

I can successfully get authorization and connect my client PHP application to QuickBooks Online. However, while I can make a getCompanyInfo request and receive the results, I can't make a getUserInfo request, as it will complain about the access token object not being set yet.

While connecting to QuickBooks and getting authorization, everything seems to work - and the access token object is placed in the Session. But for some reason, it complains when I try to get the UserInfo data. 

Here's the error I receive: 

```
Fatal error:  Uncaught QuickBooksOnline\API\Exception\SdkException: [0]: Can't get OAuth 2 Access Token Object. It is not set yet.

thrown in /compiled/src/Core/OAuth/OAuth2/OAuth2LoginHelper.php on line 129
```

Here's how I try to get the UserInfo:

```
$dataService->updateOAuth2Token($accessToken);
$OAuth2LoginHelper = $dataService->getOAuth2LoginHelper();
$result = $OAuth2LoginHelper->getUserInfo();
```

Again, getting the CompanyInfo works without any problems.

Any idea what's going on?

[apiCall.zip](https://github.com/intuit/QuickBooks-V3-PHP-SDK/files/4174196/apiCall.zip)

Please also see my Stackoverflow question about this, that explains the issue more in-depth:
https://stackoverflow.com/questions/60138631/quickbooks-v3-php-sdk-only-working-partially-with-quickbooks-online

**Comment by bsivalingam** [comment]
Following up on SF#00092238
