### ISSUE TITLE
Facing issue while receiving Currency Name,Vendor Name and APAccountRef Name

### ISSUE THREAD

**Issue by Sankalpk98** [intuit/QuickBooks-V3-PHP-SDK#282]
Hello,
I am using official library of intuit but i am facing issue while receiving following parameters mentioned above in title. Can you guys please let me know how to receive these parameters?

**Comment by bsivalingam** [comment]
@Sankalpk98 can you please create a support ticket at https://help.developer.intuit.com/s/ details on what entity you are looking to get this information from? We can track issues on salesforce and you can get a quicker response.
