### ISSUE TITLE
Unable to delete Item Category using Active=false or Operation=Delete

### ISSUE THREAD

**Issue by salasmark** [intuit/QuickBooks-V3-PHP-SDK#293]
When trying to (soft) delete an Item Category using Active=false, it says:
`The Category Item type does not support soft delete with Active=false; use Operation=Delete to Hard Delete a Category`

So I tried using Operation=Delete by replacing Active=false in the data to be sent. 
```
            $data = [
                "sparse" => "true",
                "Operation" => "Delete",
            ];
```

But it throws an error:
`Property Operation does not exist`

**Comment by bsivalingam** [comment]
@salasmark Could you please tell me which API endpoint are you hitting for this request?
