### ISSUE TITLE
Logging is not exists for getOAuth2LoginHelper() and CurlHttpClient()

### ISSUE THREAD

**Issue by alexeycarpe** [intuit/QuickBooks-V3-PHP-SDK#296]
Add logging logic to these files.

**Comment by bsivalingam** [comment]
@alexeycarpe As mentioned in the PR, I will take this up in our next sprint to add logging for all failed scenarios and log just the intuit_tid for the success. Closing the issue.

**Comment by alexeycarpe** [comment]
@bsivalingam thank you! Please notify me somehow when it will be released

**Comment by bsivalingam** [comment]
Will do!
