### ISSUE TITLE
\QuickBooksOnline\API\DataService\Batch::AddEntity Doesn't support passing `optionsData`

### ISSUE THREAD

**Issue by PeterCat12** [intuit/QuickBooks-V3-PHP-SDK#304]
In order to batch `void` operations the `\QuickBooksOnline\API\Data\IPPBatchItemRequest` class requires it's `$optionsData` property to be set to `void` per the API documentation: 

https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/batch#sample-batch-request

Unfortunately the `AddEntity` method doesn't support passing in any `optionsData`. Seems like an oversight to me as the `IPPBatchItemRequest` already supports dealing with optionsData (it adds it to the request as a valid parameter).

**Comment by bsivalingam** [comment]
@PeterCat12 Thanks for bringing it up. I will create a JIRA to add it in, meanwhile if you are able to send a PR I can add it to the next release too.

**Comment by PeterCat12** [comment]
Sure. I'll take a crack at it this weekend. Thanks for the response.

**Comment by alexjeen** [comment]
Hi guys,

Check our PR
https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/311

It has this functionality in there.

**Comment by PeterCat12** [comment]
❤️

**Comment by bsivalingam** [comment]
Thanks @alexjeen for sending in your PR. I will merge it in after you have addressed the comments.
