### ISSUE TITLE
Business Validation Error - Error code: -10600

### ISSUE THREAD

**Issue by perrystone1** [intuit/QuickBooks-V3-PHP-SDK#305]
When **updating** an Item and setting its **QtyOnHand**, the API returns the error message below.

**[A business validation error has occurred while processing your request
Business Validation Error: It looks like something went wrong on our end. We couldn't adjust the stock starting value of this item. Please try again later. Error code: (-10600) (-10600)]**

Sample code:

$item = $dataService->FindbyId('item', 24);
$theResourceObj = Item::update($item , [
    "QtyOnHand" => 100
]);
$resultingObj = $dataService->Update($theResourceObj);

What's the problem and how can it be fixed? It does not appear to be a user's error.

**Comment by nimisha84** [comment]
Please enable logs for this issue -
https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/php/logging#execution-log

Then, check if you are sending the invStartDate or not? Add your logs here and also, add the intuit-tid from the response header.

**Comment by bsivalingam** [comment]
@perrystone1 Can you please let us know if this issue is resolved? Since it is not a SDK issue please create a ticket here: https://help.developer.intuit.com/s/ when you have collected all the information as Nimisha mentioned above. Thanks!

**Comment by perrystone1** [comment]
This was a bug on Intuit's end. I believe it has been resolved.
