### ISSUE TITLE
ReflectionException: Property Name does not exist. Class: IPPTaxRate

### ISSUE THREAD

**Issue by jakesuellentrop** [intuit/QuickBooks-V3-PHP-SDK#306]
Trying to add a new TaxRate using the SDK. I'm passing in this array, and I've tried setting the Name statically, as well as leaving it out of the array. Always the same error.

```
$data = [
    'Name' => $this->tax_code,
    'RateValue' => $this->tax_rate,
    'Description' => $this->name,
];
```

**Comment by bsivalingam** [comment]
@jakesuellentrop can you please send the complete request and response?

**Comment by bsivalingam** [comment]
@jakesuellentrop Is this issue resolved, please let me know.
