### ISSUE TITLE
Get Error: Attempted to load class "DataService" from namespace "QuickBooksOnline\API\DataService

### ISSUE THREAD

**Issue by parthiv2585** [intuit/QuickBooks-V3-PHP-SDK#307]
We have developed our application in “Symfony 3.4” and install the SDK using the below command.
“composer require quickbooks/v3-php-sdk”

**And get below error: 
Attempted to load class "DataService" from namespace "QuickBooksOnline\API\DataService".**

Can you please help to fix this issue ASAP.

Thanks in advance.

**Comment by bsivalingam** [comment]
@parthiv2585 Could you please let us know the version of PHP you are using?

**Comment by parthiv2585** [comment]
Hi,
Thanks for the reply.
I am using PHP version  7.2.

**Comment by bsivalingam** [comment]
@parthiv2585 do you have the `use QuickBooksOnline\API\DataService\DataService;` in the class/file you are using `DataService` in?

**Comment by bsivalingam** [comment]
@parthiv2585 since we haven't heard back from you I am closing the issue.

**Comment by parthiv2585** [comment]
@bsivalingam  Sorry for let reply.
Yes, I have added use QuickBooksOnline\API\DataService\DataService;
