### ISSUE TITLE
Undefined Variable in Refresh Request

### ISSUE THREAD

**Issue by lukecurtis93** [intuit/QuickBooks-V3-PHP-SDK#319]
When attempting to obtain a access token with a refresh token I receive the following error:

```
 ErrorException  : Undefined variable: requestUri

  at /Users/admin/code/service-app/vendor/quickbooks/v3-php-sdk/src/Core/OAuth/OAuth2/OAuth2LoginHelper.php:306
```

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/OAuth/OAuth2/OAuth2LoginHelper.php#L306

This appears to be the offending line, the most recent PR doesn't appropriately pass this variable to the functions that use it. https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/315/files

**Comment by bsivalingam** [comment]
@lukecurtis93 Fixing right now.

**Comment by lukecurtis93** [comment]
All good mate really appreciate the speed on this one great stuff cheers!
