### ISSUE TITLE
Typo getClinetName in DataService.php

### ISSUE THREAD

**Issue by gmariani** [intuit/QuickBooks-V3-PHP-SDK#325]
Line 352 in DataService.php:

`public function getClinetName(){
       return $this->getClientName();
    }`

**Comment by bsivalingam** [comment]
Thanks for bringing it up, will have it fixed in the next release.

**Comment by bsivalingam** [comment]
@gmariani I just went back to the code to check this, it seems like it was never used. Definitely need a code clean up here. That said, there is a method to get `clientName` in L226.

**Comment by gmariani** [comment]
no problem, was just building my first app with the sdk and ran across that and figured I'd report it. it did say deprecated but figured I'd report it none-the-less. Thanks!
