### ISSUE TITLE
refreshAccessTokenWithRefreshToken not working properly

### ISSUE THREAD

**Issue by rogerms** [intuit/QuickBooks-V3-PHP-SDK#328]
$newAccessToken = $OAuth2LoginHelper->refreshAccessTokenWithRefreshToken($accessToken->getRefreshToken());
The $newAccessToken doesn't have 'realmID' and because of that, I can't use it to make calls to api.

To be able to use $newAccessToken I need to add realmID manually like this 
$newAccessToken ->setRealmID($realmID);
Only then I can use it the new token.
It would be great if you could fix that. I spent many hours to find the problem.

 using: "quickbooks/v3-php-sdk": "^5.3"

**Comment by bsivalingam** [comment]
@rogerms Can you please upgrade to the latest SDK? Also, what are the calls you are unable to make without the realmId?

**Comment by rogerms** [comment]
I thought version 5.3 was the latest one; what do I need to change in the composer to get it?
I can only receive results from calls made with the original accessToken (from the user login form); after I refresh the token, all calls return null.
for example, here

>  $entities 

will be NULL
```
$accessToken = $OAuth2LoginHelper->refreshAccessTokenWithRefreshToken($refreshToken);
$dataService->updateOAuth2Token($accessToken);
$entities = $dataService->Query("SELECT * FROM Invoice"); 
```

Thank you for your help

**Comment by bsivalingam** [comment]
@rogerms I am sorry I didn't get back to you earlier. Are you still blocked?

**Comment by rogerms** [comment]
I found a workaround; I create a new DataService every time I get a new accessToken.
Thank you

**Comment by TPXP** [comment]
I just ran into this issue with the latest version of the SDK (`v6.0.2`).


Just call `refreshToken` or `refreshAccessTokenWithRefreshToken` and try using the returned token.

The faulty code is
https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/OAuth/OAuth2/OAuth2LoginHelper.php#L541

It expects `realmId` to be passed to the function, but the two token refreshing functions do not set this argument:

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/OAuth/OAuth2/OAuth2LoginHelper.php#L312

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/OAuth/OAuth2/OAuth2LoginHelper.php#L292

BTW, those two functions are very similar, you could avoid code duplication by rewriting `refreshToken`:
```php

    public function refreshToken(){
       $refreshToken = $this->getAccessToken()->getRefreshToken();
       return $this->refreshAccessTokenWithRefreshToken($refreshToken);
    }
```
