### ISSUE TITLE
Request / Response always logging

### ISSUE THREAD

**Issue by Benjaminhu** [intuit/QuickBooks-V3-PHP-SDK#330]
Hi,

Tested with the latest release ([example code](https://gist.github.com/Benjaminhu/be504a99a08943f5c2af2e463f4b2cc3)).

I think the problem is:

```
DataService::Configure()
...
$ServiceContext = ServiceContext::ConfigureFromPassedArray($settings);
...
$IppConfiguration = LocalConfigReader::ReadConfigurationFromParameters($OAuthConfig, $checkedBaseURL, CoreConstants::DEFAULT_LOGGINGLOCATION, CoreConstants::DEFAULT_SDK_MINOR_VERSION);
...
LocalConfigReader::setupLogger($ippConfig, $defaultLoggingLocation, "TRUE"); // !!!!!!
```

The setupLogger always create **$EnableRequestResponseLogging = TRUE**

**Comment by bsivalingam** [comment]
@Benjaminhu Good point it should be a flag we pass down to the function. Will update in the next release.

**Comment by abisalehalliprasan** [comment]
Opening up our SDK for hacktoberfest contributions.

**What is it?** 
Hacktoberfest is underway right now and we would love for you to contribute  🚀  . More information on #hacktoberfest is [here](https://hacktoberfest.digitalocean.com/)

[Develop-with-Intuit for Hacktoberfest](https://medium.com/intuit-engineering/develop-with-intuit-for-hacktoberfest-2020-8f29b70ff2b4)
