### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by almasaeed2010** [intuit/QuickBooks-V3-PHP-SDK#333]
The static function listed below is using `$this` resulting in an error:

```
Error: Using $this when not in object context at quickbooks/v3-php-sdk/src/Core/Http/Serialization/XmlObjectSerializer.php:50
```

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/70dbb727bc9caa1cb104b0dc8cd9744fda8a8677/src/Core/Http/Serialization/XmlObjectSerializer.php#L37-L56

**Comment by pramodwagh** [comment]
hey,
have you found any solution on this?..

**Comment by bsivalingam** [comment]
Thanks for raising this, I have a JIRA to fix the issue, meanwhile feel free to send in a PR.

**Comment by bsivalingam** [comment]
https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/340/files will fix the issue.

**Comment by pramodwagh** [comment]
@bsivalingam,Thanks.

**Comment by tehs0ap** [comment]
@bsivalingam I don't see how this resolves the issue. You are now trying to access a non-static property from a static context.
