### ISSUE TITLE
Server is not responding

### ISSUE THREAD

**Issue by onlinecheckwriter** [intuit/QuickBooks-V3-PHP-SDK#335]
Please check out the video....
https://www.loom.com/share/15db54a6b2c54903b0f57b608ef35fe6

**Comment by onlinecheckwriter** [comment]
is this happening only to us or someone else too?

**Comment by lcnervick** [comment]
I’ve been having this problem all morning. My error logs are saying there is a timeout waiting for cUrl to get TLS.

**Comment by fr8train-homebase** [comment]
The problem is that the library is using https://www.howsmyssl.com/a/check to check your TLS version. It's currently down and not responding. I hacked around this by commenting out lines 148-152 in src/Core/HttpClients/CurlHttpClient.php

**Comment by bsivalingam** [comment]
@onlinecheckwriter @lcnervick @fr8train-homebase What version of the SDK are you on? This was a problem before, we fixed the SDK to not use this a TLS checker. Here is the fix: https://github.com/intuit/QuickBooks-V3-PHP-SDK/commit/91050cbdc0e82e5f6df8bacc40bfe6e1b232a30e#diff-7c7999b6354f6c110c0dd868941595d1 this was as part of release 5.3.5.

**Comment by bsivalingam** [comment]
@onlinecheckwriter I see that you are running into issues with connecting to the app, I will check with the App Connections team. Can you please share with us your app information?

**Comment by chadpriddle** [comment]
@fr8train-homebase Thanks for the work around. I got new error after commenting out those 4 lines:
SyncRestHandler.php
Line 213
"throw new ServiceException("Request is not made successful. Response Code:[" . $faultHandler->getHttpStatusCode() . "] with body: [" . $faultHandler->getResponseBody() . "].", $faultHandler->getHttpStatusCode());"

Using the API to post data back to an invoice when I got this error

**Comment by onlinecheckwriter** [comment]
what do you want from us : @bsivalingam 

We are also using old sdk, we didn't even change sdk

**Comment by bsivalingam** [comment]
@onlinecheckwriter the issue you are experiencing for connection is different from the what others are referring to. Sorry I jumped the gun there. But if you can share more information from the network tab of the UI that is hung up, we will be able to triage it faster. We haven't had reports on connection error from other apps so we would need specifics for triaging. This could be a browser issue or something more specific to the app. If you can send us your app id and if possible the intuit_tid from the network tag for the app connection call that will help us.

For the TLS error please **upgrade** the version of SDK.

**Comment by onlinecheckwriter** [comment]
Let me update the sdk version and try it.

**Comment by onlinecheckwriter** [comment]
We moved this new SDK . I think it fix the issue
