### ISSUE TITLE
Call to undefined method QuickBooksOnline\API\WebhooksService\Entity::__set()

### ISSUE THREAD

**Issue by walkersteele** [intuit/QuickBooks-V3-PHP-SDK#337]
`
$payload = '{"eventNotifications":[{"realmId":"XXXXX","dataChangeEvent":{"entities":[{"name":"Account","id":"91","deletedId":"135","operation":"Merge","lastUpdated":"2019-06-27T17:12:40.000Z"}]}}]}';

WebhooksService\WebhooksService::getWebhooksEvent($payload)
`
Throws an undefined method __set() when handling an account merge webhook

**Comment by bsivalingam** [comment]
PR: https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/339 fixes the issue.
