### ISSUE TITLE
ClientID Must be provided

### ISSUE THREAD

**Issue by coebooker** [intuit/QuickBooks-V3-PHP-SDK#338]
I've installed the SDK using composer, and am trying to run this [source code](https://github.com/IntuitDeveloper/QBOConceptsTutorial-PHP/blob/master/PayBill.php) and I've properly configured the $config array with my ClientID, ClientSecret, RedirectUri, and scope however whenever I run the file it gives me the error Fatal error: Uncaught QuickBooksOnline\API\Exception\SdkException: [0]: 'ClientID' must be provided in C:\wamp64\www\Bill\vendor\quickbooks\v3-php-sdk\src\Core\ServiceContext.php on line 205. I've been stuck for a couple of days and am pretty new to the Quickbooks API, so I think it might just be a simple mistake during installation, but I'm not sure.

**Comment by bsivalingam** [comment]
@coebooker can you please share what the `config.php` looks like?

**Comment by coebooker** [comment]
`<?php

/**
 * This is a file that required for using the files located in _Sample folders.
 * It is a SQL autoloader that performs the exact same function as composer "require "vendor/autoload.php";"
 * If you are using the _sample file. Remove the required include('../config.php'); line and add "require "vendor/autoload.php"" instead.
 *
 * @author Hao
 */
// PSR-4 Autoloader,QuickBooksOnline\Data;
spl_autoload_register(function ($class) {
	  $prefix = 'QuickBooksOnline\\API\\';
		$base_dir = __DIR__ . DIRECTORY_SEPARATOR;
		$len = strlen($prefix);
		if (strncmp($prefix, $class, $len) !== 0) {
        return;
    }
		$relative_class = substr($class, $len);
		$filewithoutExtension = $base_dir . str_replace('\\', '/', $relative_class);
		$file =  $filewithoutExtension. '.php';

		//Below str_replace is for local testing. Remove it before putting on Composer.
	  if (file_exists($file) ) {
	        require ($file);
	   }
	});`
There's my config file

**Comment by bsivalingam** [comment]
@coebooker you see in the above code at no point do we define `$config['CLIENTID']` and `$config['CLIENTSECRET']`. For purposes of testing you might want to hardcode the values.

**Comment by coebooker** [comment]
@bsivalingam I have hardcoded these values....but obviously I am not going to post my ClientID and ClientSecret on a public forum

**Comment by bsivalingam** [comment]
I need to see the code flow to answer this @coebooker. Please create a support ticket here:  https://help.developer.intuit.com/s/. This is an implementation problem and not a SDK issue.
