### ISSUE TITLE
Deprecation Notice:

### ISSUE THREAD

**Issue by onlinecheckwriter** [intuit/QuickBooks-V3-PHP-SDK#341]
Deprecation Notice: Class QuickBooksOnline\API\Data\IPPWrapper located in D:/xampp/htdocs/ocw/vendor/quickbooks/v3-php-sdk/src\Data\IPP.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201.

Am I only getting this or everyone else is getting too?

**Comment by bsivalingam** [comment]
This has been reported: https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/329. We have a fix, but there was a failure with regression so the PR is on hold.

**Comment by streamingsystems** [comment]
I was just checking in as I upgraded to the new composed (2.0) tonight and am seeing this as well.

**Comment by raftalks** [comment]
@bsivalingam where is the PR, may be we can fix the PR too

**Comment by hotmeteor** [comment]
What's the status on this one?

**Comment by Khairulbashar010** [comment]
I'm having this problem with RestPasswordController. Any updates on this issue?
