### ISSUE TITLE
Reconnect fails due to incomplete changes in commit 12856b6

### ISSUE THREAD

**Issue by markwoods241** [intuit/QuickBooks-V3-PHP-SDK#35]
Unable to run reconnect to replenish expiring oauth access tokens.

Call to `Reconnect()` function in `PlatformService` returns:

>Call to undefined method QuickBooksOnline\\API\\Core\\HttpClients\\SyncRestHandler::GetResponse()

It appears that in commit 12856b6279c22550355eed9ef33fcad95f7a1b96 the function `GetResponse()` in  `src/Core/HttpClients/SyncRestHandler.php` was renamed to `sendRequest()`, though only around half of the respective calls to `GetResponse()` were updated to reflect this (`DataService` looks good, but `PlatformService` was missed, as well as a single reference missed in `SyncRestHandler` too, inside the `CallRestService()` function).

Regards,

Mark

**Comment by hlu2** [comment]
@markwoods241 
Fixed on v3.2.6
