### ISSUE TITLE
Installation Failed when trying to install PHP SDK

### ISSUE THREAD

**Issue by salmanahmad456** [intuit/QuickBooks-V3-PHP-SDK#37]
@hlu2 
I am trying to install PHP SDK through composer and every time i try to run command "composer require quickbooks/v3-php-sdk"
after 100% download i am seeing an error of installation failed.
 
i have also installed oauth extension and enabled this. (which i know is not required after 3.2.4)
 
Please see attached screenshots of OAuth and Error
![installation_failed](https://user-images.githubusercontent.com/24820449/27876408-73be7704-61d0-11e7-95b9-77bb49e6326e.png)
![oauth](https://user-images.githubusercontent.com/24820449/27876409-73bf965c-61d0-11e7-9288-7bffe53af8fb.png)

**Comment by markwoods241** [comment]
At a glance, I think your project path is causing a problem here, resulting in the full path exceeding the windows max file path character limit (similar example here: https://github.com/composer/composer/issues/3755).

As it's an image, I can't count how many chars are in that full path. If you're not far over 260 (https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath) you might be able to rename your project to get around the limitation as a relatively simple "fix".

**Comment by hlu2** [comment]
@salmanahmad456 
It looks like a path issue. The path is too long. Composer is complaining about a path that is too long for PHP on Windows. Windows has a max path length (MAXPATHLEN) of 260 characters. There is nothing we can do for it. 

See if you can change it to a short path. Also, make sure there is no "." or "/" in the path.

**Comment by hlu2** [comment]
@markwoods241 
Thanks for posting it.

**Comment by salmanahmad456** [comment]
Thanks @markwoods241 issue was due to path length, it is working fine now
