### ISSUE TITLE
Timeout while api is up

### ISSUE THREAD

**Issue by TravisDavis-ops** [intuit/QuickBooks-V3-PHP-SDK#378]
Error Message: Severity: error --> Exception: cURL error during making API call. cURL Error Number:[28] with error:[Operation timed out after 15001 milliseconds with 0 bytes received]
An uncaught Exception was encountered
Type: QuickBooksOnline\API\Exception\SdkException

Message: cURL error during making API call. cURL Error Number:[28] with error:[Operation timed out after 15001 milliseconds with 0 bytes received]

Filename: /var/www/codeigniter/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/CurlHttpClient.php

Line Number: 112

Backtrace:

File: /var/www/codeigniter/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/CurlHttpClient.php
Line: 47
Function: handleErrors

File: /var/www/codeigniter/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/SyncRestHandler.php
Line: 215
Function: makeAPICall

File: /var/www/codeigniter/vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/SyncRestHandler.php
Line: 127
Function: OAuth2APICall

File: /var/www/codeigniter/vendor/quickbooks/v3-php-sdk/src/DataService/DataService.php
Line: 1021
Function: sendRequest

File: /var/www/codeigniter/application/models/QuickBooks_model.php
Line: 249
Function: Query

File: /var/www/codeigniter/application/controllers/QBO.php
Line: 67
Function: query

File: /var/www/codeigniter/index.php
Line: 315
Function: require_once

**Comment by TravisDavis-ops** [comment]
So this has happened again but this time it  has been happening for 2 days, any one know whats up.

**Comment by TravisDavis-ops** [comment]
I will close this, at some point someone added a Global  I can set to change the default timeout, thanks

**Comment by Bondarenko93** [comment]
how did you fix this problem ?

**Comment by TravisDavis-ops** [comment]
Hope this helps, but there a global not mentioned in the docs that can be used if your requesting alot of data at once.
`        if (defined('QUICKBOOKS_API_TIMEOUT')) {
            // if the timeout constant is set, use it for the timeout
            $timeOut = (int)QUICKBOOKS_API_TIMEOUT;
        }`

**Comment by BarnumD** [comment]
How do you set the global?
