### ISSUE TITLE
Required parameter $dir follows optional parameter $fileName

### ISSUE THREAD

**Issue by shawnreid** [intuit/QuickBooks-V3-PHP-SDK#383]
quickbooks/v3-php-sdk/src/DataService/DataService.php:1670

Caused by this line:

`protected function processDownloadedContent(ContentWriter $writer, $responseCode, $fileName = null, $dir)`

https://php.watch/versions/8.0/deprecate-required-param-after-optional

**Comment by abisalehalliprasan** [comment]
Fixed with new release [v5.4.6](https://github.com/intuit/QuickBooks-V3-PHP-SDK/tree/5.4.6)
