### ISSUE TITLE
DataService FindById Company/CompanyInfo handling is unusual

### ISSUE THREAD

**Issue by markwoods241** [intuit/QuickBooks-V3-PHP-SDK#39]
The DataService FindById code has special handling for Company/CompanyInfo entities. It seems the intention here is to handle the unusual state where the Company/CompanyInfo entity id isn't set as you may expect (i.e. it does not match the realmId, and seems to be set to 1 in most cases).

```
        elseif ((strtolower('company') == strtolower($urlResource)) ||
            (strtolower('companyinfo') == strtolower($urlResource))
        ) {
            // FindById semantics for CompanyInfo are unusual.  Handle via special case.
            $allEntities = $this->FindAll('Company');
            foreach ($allEntities as $oneCompany) {
                if (0 == strcmp($oneCompany->Id, $entity->Id)) {
                    return $oneCompany;
                }
            }

            return null;
        } else {
            // Normal case
            $uri = implode(CoreConstants::SLASH_CHAR, array('company', $this->serviceContext->realmId, $urlResource, $entityId));
        }
```

Issue here is with the conditional statement in there looping through the results and checking the entity id...the fact that it's actually checking the id matches the entity id provided renders the code pointless - if the user is aware of the "real" entity id, then there is no need for the "FindAll" workaround, since running the "Normal case" against the companyinfo urlResource would suffice.

My guess is that the ideal scenario here would be to remove the need to pass any id in the case of Company/CompanyInfo types, and have it simply return the one result found when calling FindAll('CompanyInfo')? This is on the assumption that you will only ever have one CompanyInfo record - I may well be wrong here, but all the examples I can find seem to have different approaches to pulling CompanyInfo data, so it's hard to tell.

Regards,

Mark

**Comment by hlu2** [comment]
@markwoods241 
Hi Mark,
I didn't pay attention to the FindById part. The implementation is a little strange in my sense as well. I will take a look and see why it is implemented in that way. If it is wrong, I will re-implement it.

Thanks for paying attention to the details on PHP SDK, mark. I really appreciate it.

Best,
Hao

**Comment by hlu2** [comment]
Done.
