### ISSUE TITLE
SDK 5.4.5 Logging does not work

### ISSUE THREAD

**Issue by shawncrigger** [intuit/QuickBooks-V3-PHP-SDK#390]
I stupidly updated my composer and it upgraded the SDK to 5.4.5 and all of a sudden my request and response logs no longer worked,  I checked the directory exists, `is_writeable()` and that logging is enabled. Since all of a sudden, some other issues started happening and without the log to debug anything I revered back to 5.4.4 which seems to be the most stable version atm?

**Comment by abisalehalliprasan** [comment]
@shawncrigger : Thanks for reporting this. We will look into it. This might have been introduced with the PR #364 . We apologize for the inconvenience caused.

**Comment by abisalehalliprasan** [comment]
@shawncrigger : Thanks for reporting, this should be fixed with the release : [5.4.7](https://github.com/intuit/QuickBooks-V3-PHP-SDK/tree/5.4.7)
