### ISSUE TITLE
PHP 8 possible issue with queries

### ISSUE THREAD

**Issue by jplevene** [intuit/QuickBooks-V3-PHP-SDK#396]
I am getting the following query go wrong using the latest SDK running on a PHP 8 server:
`select * from Invoice where Id in ('16938', '16995', '17438', '17440', '17858', '17906', '17907', '17911', '17912', '17977', '18226', '18227', '18246', '18242', '18318', '18336', '18344', '18345', '18362', '18363', '18416') and Balance='0' and MetaData.LastUpdatedTime>'2021-03-19T21:34:34Z' STARTPOSITION 0 MAXRESULTS 1000`
The error I get is completely incorrect:
**message=AuthenticationFailed; errorCode=003200; statusCode=401 (AUTHENTICATION)**
The session is still logged in, token is still valid and I can do other calls.
I have also posted the error here https://help.developer.intuit.com/s/question/0D54R00007leTrQSAU/query-on-invoices-causes-an-authentication-failure

The error only occurs if the query returns data!  If I do the same query on a PHP7 server, all is fine.  If I then remove the Id's that have a Balance=0, no error on the PHP8 server

**Comment by abisalehalliprasan** [comment]
@jplevene : Just to confirm, are you seeing this only for Query operations on PHP 8 using the latest SDK? I will take a look at it.

**Comment by jplevene** [comment]
Yes, only on PHP 8 with latest SDK and only when the query returns results.  If the query has no Invoices in the results, it's fine.

**Comment by jplevene** [comment]
Please drop it, it was our end.
