### ISSUE TITLE
Allow minorVersion to be set using DataService::Configure([])

### ISSUE THREAD

**Issue by challgren** [intuit/QuickBooks-V3-PHP-SDK#4]
There is no way to set the minorVersion when calling DataService::Configure. After looking around it looks likeServiceContext::ConfigureFromPassedArray([]) has the minorVersion hard coded to version 3 ServiceContext.php line 188

**Comment by hlu2** [comment]
I will add the option to set minor versions on next Release, which is either this Friday or next Monday.

**Comment by hlu2** [comment]
Now you can use:
$dataService->setMinorVersion("4");
for setting up your own minor Version.
