### ISSUE TITLE
API minor version default not compatible with IPPSalesFormsPrefs properties

### ISSUE THREAD

**Issue by markwoods241** [intuit/QuickBooks-V3-PHP-SDK#40]
With API minor version upgraded to v8 in last release, a problem with pulling preferences has cropped up.

It looks like a new parameter was added (EmailCopyToCompany) that isn't yet defined in the IPPSalesFormsPrefs class in the SDK.

Details of new parameter:
>https://developer.intuit.com/docs/0100_quickbooks_online/release_notes/quickbooks_api_release_notes#/section_5

Error message:
>Property EmailCopyToCompany does not exist. Class QuickBooksOnline\\API\\Data\\IPPSalesFormsPrefs

**Comment by hlu2** [comment]
@markwoods241 
I will include in the next release. Somehow the Data folder is not picking it up. Thanks for pointing it out:)

**Comment by hlu2** [comment]
@markwoods241 
Fixed in v3.3.0. I thought it is there as it is auto-generated, somehow it is not. Thanks for pointing it out:)
