### ISSUE TITLE
Method is misnamed

### ISSUE THREAD

**Issue by tomcat90** [intuit/QuickBooks-V3-PHP-SDK#400]
The method should be getClientName and is actually spelled getClinetName

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/73c395d7243fa4dc63027a94cda20180c8b3b5cb/src/DataService/DataService.php#L355

**Comment by abisalehalliprasan** [comment]
We are fixing this in the next release. Thanks @tomcat90
