### ISSUE TITLE
DataService Upload Encoding

### ISSUE THREAD

**Issue by markwoods241** [intuit/QuickBooks-V3-PHP-SDK#43]
The QuickBooksOnline\API\DataService\DataService class contains an Upload function.

The function appears to work, but has a few minor issues:

1. Comments/Params/Variables specifically references "image" uploads, though many other MIME types are supported.
2. Content-Transfer-Encoding is set to base64. Whilst this may come in handy at times, it may be better to avoid this in a production system if not required, due to the 33% network overheads when transmitting binary data as base64.

Regards,

Mark

**Comment by hlu2** [comment]
@markwoods241 
Working on it:)

**Comment by hlu2** [comment]
Done
