### ISSUE TITLE
Cannot install via composer

### ISSUE THREAD

**Issue by blemaire** [intuit/QuickBooks-V3-PHP-SDK#44]
I just tried to install this but got the following error:

```
 [ErrorException]
 ZipArchive::extractTo(C:\Users\Bastien\SoapSaltsAndScents\SoapsSaltsAndScents/vendor/composer/cb5a4ab7/intuit-Quick
 Books-V3-PHP-SDK-d711124\src\XSD2PHP\test\data\expected\ContactCompany\oasis\names\specification\ubl\schema\xsd\Com
 monAggregateComponents_2/AccountingCustomerParty.php): failed to open stream: No such file or directory
```

**Comment by bkdotcom** [comment]
https://www.google.com/search?q=composer+ZipArchive%3A%3AextractTo+failed+to+open+stream%3A

Windows, Linux, OSX, other?

**Comment by hlu2** [comment]
hi @blemaire 
It is the path length issue on windows. Change the installation to a short path should resolve your issue. Refer to here: https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/37

**Comment by blemaire** [comment]
Thanks a lot for your prompt reply.
