### ISSUE TITLE
Psr7\str method is deprecated

### ISSUE THREAD

**Issue by stevenmaguire** [intuit/QuickBooks-V3-PHP-SDK#475]
On the most recent release of this library, a deprecated PSR7 method is used when an error occurs. This obscures the relevant error and instead throws a code-related error.

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/20ce804a7e643d91b0a8f115e969bf6a0713f64e/src/Core/HttpClients/GuzzleHttpClient.php#L60

<img width="969" alt="CleanShot 2023-03-01 at 10 47 31@2x" src="https://user-images.githubusercontent.com/1851973/222206443-829414ab-3e36-4dd7-9cc1-9b7e62e48408.png">

**Comment by thalysantana** [comment]
Same issue here.
