### ISSUE TITLE
PHP 8.2 Deprecated Warnings

### ISSUE THREAD

**Issue by racerguy** [intuit/QuickBooks-V3-PHP-SDK#483]
Creation of dynamic property QuickBooksOnline\API\Diagnostics\LoggerBase::$ServiceRequestLoggingLocation is deprecated in vendor/quickbooks/v3-php-sdk/src/Core/Configuration/LocalConfigReader.php on line 417.

Creation of dynamic property QuickBooksOnline\API\Data\IPPBatchItemRequest::$operationSpecified is deprecated in vendor/quickbooks/v3-php-sdk/src/DataService/Batch.php on line 230.

Creation of dynamic property QuickBooksOnline\API\Data\IPPBatchItemRequest::$operationSpecified is deprecated in vendor/quickbooks/v3-php-sdk/src/DataService/Batch.php on line 230.

**Comment by marcLeeroy** [comment]
Same issue when trying to get the oauth link.

Getting: `Can't Config Environments from passed parameters` but it's a blanket error for the actual error that is a dynamic property creation by the sdk. 

It does not seem php 8.2 compatible at all.

**Comment by philippe-leeroy** [comment]
I've found when the exception is triggered... It's in the file `LocalConfigReader.php` on line 124 when the logger is setup: 

`LocalConfigReader::setupLogger($ippConfig, $defaultLoggingLocation, "TRUE");`

The exception is :
Creation of dynamic property QuickBooksOnline\API\Diagnostics\LoggerBase::$ServiceRequestLoggingLocation is deprecated

So what I would propose is simply add this in the LoggerBase.php file before the class creation:

`use QuickBooksOnline\API\Core\CoreConstants;`
`use \AllowDynamicProperties;`

`#[AllowDynamicProperties]`
`class LoggerBase`
`{`

**Comment by gitbjorn** [comment]
We are waiting for the same fix

**Comment by devbanana** [comment]
Getting the same error; hoping for a fix soon.

**Comment by mherbold** [comment]
Same error here - what is taking so long to fix this?  The fix is rather simple.

**Comment by sujitharamadass** [comment]
@poolsimon We will update you soon

**Comment by sujitharamadass** [comment]
The fix will be released soon

**Comment by sujitharamadass** [comment]
Fixed in version 6.1.2
