### ISSUE TITLE
Incorrect Transaction List report parameter names in ReportService.php

### ISSUE THREAD

**Issue by bch36** [intuit/QuickBooks-V3-PHP-SDK#489]
The parameter name "both_amount" on line 1236 should be "bothamount".

```
array_push($uriParameterList, array("both_amount", $this->getBothAmount()));
```
should be:
```
array_push($uriParameterList, array("bothamount", $this->getBothAmount()));
```

Similarly, the parameter name "doc_num" on line 1242 of ReportService.php should actually be "docnum".  
```
array_push($uriParameterList, array("doc_num", $this->getDocNum()));
```
should be:
```
array_push($uriParameterList, array("docnum", $this->getDocNum()));
```

As is, they are silently ignored when running a Transaction List report.

**Comment by sujitharamadass** [comment]
Fixed in version 6.1.2
