### ISSUE TITLE
DataService->Query() has unused params

### ISSUE THREAD

**Issue by bkdotcom** [intuit/QuickBooks-V3-PHP-SDK#49]
here's the docblock and function signature for the Query method

```
    /**
     * Retrieves specified entities based passed page number and page size and query
     *
     * @param string $query Query to issue
     * @param int $pageNumber Starting page number
     * @param int $pageSize Page size
     * @return array Returns an array of entities fulfilling the query.
     */
    public function Query($query, $pageNumber = 0, $pageSize = 500)
```

`$pageNumber` and `$pageSize` are UNUSED... passing values does absolutely nothing
(there's no `func_get_args()` type call to grab these param values either)

if someone wants to specify page & pagesize, they need to specify it in the query
ie: `STARTPOSITION 11 MAXRESULTS 10`

unrelated:  only being able to pass 30 entities in a batch request seems pretty weak.

**Comment by hlu2** [comment]
@bkdotcom 
Brad, I will assign it to me now, but it will be fixed at a later release, as I have something on a higher priority right now. This is a known issue and I probably will fix it along with the GraphQL support

**Comment by hlu2** [comment]
@bkdotcom 
The query method is outdated. It should be     
`public function Query($query, $pageNumber = 0, $pageSize = 500)`
However, for version compatibility, I cannot remove the two parameters. I will include this in the readme file for how to use pagination.

Thanks for pointing it out.

Best,
Hao
