### ISSUE TITLE
Fatal Error Core\HttpClients\SyncRestHandler.php

### ISSUE THREAD

**Issue by challgren** [intuit/QuickBooks-V3-PHP-SDK#5]
Error: Class 'QuickBooksOnline\API\Core\HttpClients\Exception' not found	
File: /Vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/SyncRestHandler.php	
Line: 238

**Comment by hlu2** [comment]
My bad. It misses a class declaration. On the line:
 /Vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/SyncRestHandler.php:
if (!extension_loaded('OAuth')) {
				throw new Exception('The PHP exention OAuth 1.2.3 must be installed to use this library.');
		}

change it to:
if (!extension_loaded('OAuth')) {
				throw new \Exception('The PHP exention OAuth 1.2.3 must be installed to use this library.');
		}

I will include this fix on the next release coming this Friday.

**Comment by challgren** [comment]
Ok cool

**Comment by challgren** [comment]
My guess is these will also produce errors
![screenshot 2017-04-17 23 08 44](https://cloud.githubusercontent.com/assets/88909/25114246/e532253a-23c2-11e7-8e8a-885ddbca51c4.png)

**Comment by hlu2** [comment]
I have updated the Exception class. Please check with the latest version.

Thanks
Hao
