### ISSUE TITLE
DataService download capabilities

### ISSUE THREAD

**Issue by markwoods241** [intuit/QuickBooks-V3-PHP-SDK#51]
Similar to the issue logged in #43 where uploads specifically reference image files, the DataService class contains 2 "download" functions:

1) Download -> this appears to just be an alias of FindById at the moment, so makes things a little confusing, since one would perhaps expect that this would be the respective companion to the Upload function, and thus be used to download an Attachable item.

2) DownloadPDF -> this appears to be a download handler for downloading pdf versions of IPPSalesReceipt, IPPInvoice and IPPEstimate types.

So at present, at a glance, it appears there is no support for downloading Attachables? Can that be added?

Regards,

Mark

**Comment by hlu2** [comment]
@markwoods241 
Mark, I will need to take a look. Will let you know later.

Thanks
Hao

**Comment by hlu2** [comment]
Done.
