### ISSUE TITLE
/Core/HttpClients/FaultHandler triggers fatal error

### ISSUE THREAD

**Issue by bkdotcom** [intuit/QuickBooks-V3-PHP-SDK#52]
message being passed to parseResponse:

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?><FaultInfo xmlns="http://www.intuit.com/sb/cdm/baseexceptionmodel/xsd"><Message>Bad Request</Message><ErrorCode>400</ErrorCode><Cause>CLIENT</Cause></FaultInfo>

Warning: .../vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/FaultHandler.php (line 119): QuickBooksOnline\API\Core\HttpClients\FaultHandler::parseResponse(): Node no longer exists
Fatal Error: .../vendor/quickbooks/v3-php-sdk/src/Core/HttpClients/FaultHandler.php (line 124): Call to a member function attributes() on null

caused by attempting to update preferences

    $prefs = $dataService->FindAll('Preferences');
    // prefs is an array of QuickBooksOnline\API\Data\IPPPreferences objects (length: 1)
    $prefs = $prefs[0];
    $dataService->Update($prefs);

How does one update preferences via the SDK?

Edit: 2017-08-01:
for what it's worth, the request body generated by the SDK also fails in the API explorer
https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO#?id=Preferences

**Comment by hlu2** [comment]
@bkdotcom 
I will fix the FaultHanlder exception in the next release. A little busy with other staff these days.
Thanks
Hao

**Comment by hlu2** [comment]
@bkdotcom 
Fixed on v3.4.0.

**Comment by hlu2** [comment]
@bkdotcom 
For Updating Preference, do not pass the WHOLE PREFERENCE object to the Update function. Only get the ID, SyncToken, and the preferences you need to update. There is a bug in QBO that can't validate all the fields of a Preference Object, thus giving you a 400 error.
