### ISSUE TITLE
 Exception appears in converting Response to XML

### ISSUE THREAD

**Issue by tomtomhotep2** [intuit/QuickBooks-V3-PHP-SDK#525]
I don't understand why the SDK is throwing this error.

Here are the Request and Response Log files:

REQUEST URI FOR SEQUENCE ID 00017
==================================
https://sandbox-quickbooks.api.intuit.com/v3/company/9341452970090425/query?minorversion=73

REQUEST HEADERS
================
Authorization: Bearer eyJlbmMiOiJBMTI4Q0JD........
host: sandbox-quickbooks.api.intuit.com
user-agent: V3PHPSDK6.1.4
accept: */*
connection: close
content-type: application/text
content-length: 95

REQUEST BODY
=============
select * from Account where Classification = 'Liability' AND AccountSubType = 'AccountsPayable'

RESPONSE URI FOR SEQUENCE ID 00018
==================================
https://sandbox-quickbooks.api.intuit.com/v3/company/9341452970090425/query?minorversion=73

RESPONSE HEADERS
================
date: Fri, 25 Oct 2024 14:48:13 GMT
content-type: application/xml;charset=UTF-8
content-length: 898
connection: close
x-spanid: cab05243-bc16-d553-a6bd-00038f78b0e2
x-amzn-trace-id: Root=1-671bafac-07a89a3c5f5193774e6f2de6
x-content-type-options: nosniff
x-envoy-upstream-service-time: 349
server: istio-envoy
x-envoy-decorator-operation: v3-facade-service-desired-service.dev-devx-v3facadeservice-usw2-prd-ids.svc.cluster.local:8090/*
strict-transport-security: max-age=31536000
intuit_tid: 1-671bafac-07a89a3c5f5193774e6f2de6
x-request-id: 1-671bafac-07a89a3c5f5193774e6f2de6

RESPONSE BODY
=============
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2024-10-25T07:48:12.967-07:00">
  <QueryResponse startPosition="1" maxResults="1">
    <Account domain="QBO" sparse="false">
      <Id>33</Id>
      <SyncToken>0</SyncToken>
      <MetaData>
        <CreateTime>2024-07-24T10:12:02-07:00</CreateTime>
        <LastUpdatedTime>2024-07-31T13:10:36-07:00</LastUpdatedTime>
      </MetaData>
      <Name>Accounts Payable (A/P)</Name>
      <SubAccount>false</SubAccount>
      <FullyQualifiedName>Accounts Payable (A/P)</FullyQualifiedName>
      <Active>true</Active>
      <Classification>Liability</Classification>
      <AccountType>Accounts Payable</AccountType>
      <AccountSubType>AccountsPayable</AccountSubType>
      <CurrentBalance>-1602.67</CurrentBalance>
      <CurrentBalanceWithSubAccounts>-1602.67</CurrentBalanceWithSubAccounts>
      <CurrencyRef name="United States Dollar">USD</CurrencyRef>
    </Account>
  </QueryResponse>
</IntuitResponse>

---------------

As you can see, Intuit returned XML, why would the SDK try to "convert" it to XML?????

**Comment by tomtomhotep2** [comment]
Sorry, didn't preview that.

Response Body:


```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2024-10-25T07:48:12.967-07:00">
  <QueryResponse startPosition="1" maxResults="1">
    <Account domain="QBO" sparse="false">
      <Id>33</Id>
      <SyncToken>0</SyncToken>
      <MetaData>
        <CreateTime>2024-07-24T10:12:02-07:00</CreateTime>
        <LastUpdatedTime>2024-07-31T13:10:36-07:00</LastUpdatedTime>
      </MetaData>
      <Name>Accounts Payable (A/P)</Name>
      <SubAccount>false</SubAccount>
      <FullyQualifiedName>Accounts Payable (A/P)</FullyQualifiedName>
      <Active>true</Active>
      <Classification>Liability</Classification>
      <AccountType>Accounts Payable</AccountType>
      <AccountSubType>AccountsPayable</AccountSubType>
      <CurrentBalance>-1602.67</CurrentBalance>
      <CurrentBalanceWithSubAccounts>-1602.67</CurrentBalanceWithSubAccounts>
      <CurrencyRef name="United States Dollar">USD</CurrencyRef>
    </Account>
  </QueryResponse>
</IntuitResponse>

```

**Comment by tomtomhotep2** [comment]
I believe I've traced the problem to the following:

DataService::Query() contains the statement:

`$parsedResponseBody = $this->responseSerializer->Deserialize($tmpXML, false);`

inside a try-catch block.

That statement calls XmlObjectSerializer::Deserialize(), which contains the statement:

`$onePhpObj = XmlObjectSerializer::PhpObjFromXml($phpClassName, $oneXmlObj->asXML());`

XmlObjectSerializer::PhpObjFromXml() contains the statement:

`$bind = new Bind(CoreConstants::PHP_CLASS_PREFIX);`

But there is NO CLASS named "Bind" in the SDK.

Where do I get the library containing this class?????

Please Help.

Thank You!

**Comment by chas688** [comment]
Have you tried this through postman or directly to the API itself? I’ve had some issues in going through the library that are not present in communication with the endpoint directly.

**Comment by tomtomhotep2** [comment]
I don't have postman, so the other thing.

**Comment by chas688** [comment]
So probably Insomnia, so what you’re saying is it works through that and then the SDK is messing it up. $bind isn’t a class from what I see, it’s a method. I will step through this and see what it’s missing.

**Comment by chas688** [comment]
OK, so I see where the class Bind is - it's in:
https://github.com/intuit/QuickBooks-V3-PHP-SDK/tree/master/src/XSD2PHP/src/com/mikebevz/xsd2php
Are you sure you have the latest version of the SDK?

**Comment by tomtomhotep2** [comment]
I downloaded `QuickBooks-V3-PHP-SDK-6.1.4.zip`, so I _should_ have v6.1.4 of the SDK.

I did not have the `xsd2php` folder uploaded to the server, but now I do, and this block of DataService::Query() :

```
            try {
                $responseXmlObj = simplexml_load_string($responseBody);
                if ($responseXmlObj && $responseXmlObj->QueryResponse) {
                    $tmpXML = $responseXmlObj->QueryResponse->asXML();
                    $parsedResponseBody = $this->responseSerializer->Deserialize($tmpXML, false);
                    $this->serviceContext->IppConfiguration->Logger->CustomLogger->Log(TraceLevel::Info, $parsedResponseBody);
                }

            } catch (\Exception $e) {
                throw new \Exception("Exception appears in converting Response to XML.");
            }

```

is still throwing the "Exception appears in converting Response to XML." Exception.

Of course, I don't know which line in the try block is throwing an exception...


Thanks for helping!!

**Comment by tomtomhotep2** [comment]
I temporally added debug echos to that block in DataService::Query() :

```
            try {
                echo '<h2>DEBUG DataService::Query(): before simplexml_load_string</h2>';
                $responseXmlObj = simplexml_load_string($responseBody);
                echo '<h2>DEBUG DataService::Query(): after simplexml_load_string</h2>';
                if ($responseXmlObj && $responseXmlObj->QueryResponse) {
                    echo '<h2>DEBUG DataService::Query(): inside IF, before QueryResponse->asXML</h2>';
                    $tmpXML = $responseXmlObj->QueryResponse->asXML();
                    echo '<h2>DEBUG DataService::Query(): after QueryResponse->asXML, before Deserialize</h2>';
                        $parsedResponseBody = $this->responseSerializer->Deserialize($tmpXML, false);
                    echo '<h2>DEBUG DataService::Query(): after Deserialize</h2>';
                    $this->serviceContext->IppConfiguration->Logger->CustomLogger->Log(TraceLevel::Info, $parsedResponseBody);
                }

            } catch (\Exception $e) {
                throw new \Exception("Exception appears in converting Response to XML.");
            }

```

And this was the output:

```
DEBUG DataService::Query(): before simplexml_load_string
DEBUG DataService::Query(): after simplexml_load_string
DEBUG DataService::Query(): inside IF, before QueryResponse->asXML
DEBUG DataService::Query(): after QueryResponse->asXML, before Deserialize

```

it never got to `echo '<h2>DEBUG DataService::Query(): after Deserialize</h2>';`

so the exception must be happening in XmlObjectSerializer::Deserialize().

**Comment by chas688** [comment]
I'm trying to reproduce this. Send me an email to my chas688@gmail.com with your DM stuff.

Thanks

**Comment by tomtomhotep2** [comment]
I got it working!

Thanks!

**Comment by goldy-566** [comment]
We migrated PHP SDK from 6.0.0 to 6.2.0, which updates the minorversion 36 to 75.

Now, when we create new tax code and then try to fetch anything (GET apis), then it throws exception "Exception appears in converting Response to XML".

While, at the next time, we try to fetch that tax code, we are able to fetch that tax code and run all the GET apis.

Can anyone help me on this?
