### ISSUE TITLE
Throttle Limits Exceeded 

### ISSUE THREAD

**Issue by amitcorcrm** [intuit/QuickBooks-V3-PHP-SDK#54]
When I am pushing data from my web application to QuickBooks Online using PHP-SDK-V3 and I am getting below errors, can anyone face this error before ,if yes so please help me on this how can i overcome this issue.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse time="2017-07-30T22:45:22.933-07:00" xmlns="http://schema.intuit.com/finance/v3">
    <Fault type="SERVICE">
        <Error code="3001">
            <Message>message=ThrottleExceeded; errorCode=003001; statusCode=429</Message>
            <Detail>The request limit was reached.  Try again later</Detail>
        </Error>
    </Fault>
</IntuitResponse>
```

**Comment by hlu2** [comment]
@amitcorcrm 
This is a throttling Error. If you take a look at our documentation here:https://developer.intuit.com/docs/0100_quickbooks_online/0300_references/0000_programming_guide/0000_rest_api_quick_reference#/Limits_and_throttles
You can find the below information:
Production servers
Reports API endpoints—Throttled to 200 requests per minute per realm ID.
Payments API endpoints—Throttled to 40 requests per minute per app.
All other Accounting API endpoints—Throttled to 500 requests per minute per realm ID.
Sandbox servers

Payments API endpoints—Throttled to 40 requests per minute per app.
All other Accounting API endpoints—Requests are throttled at 100 requests per minute per individual app. For complete information about sandbox environments, click here.
Request and response limits

The maximum number of batch items in a single request is 30.
The maximum number of entities returned in a query response is 1000. To handle more than 1000, fetch the entities in chunks, as described in Pagination.
