### ISSUE TITLE
(1/1) SdkException cURL error during making API call. cURL Error Number:[60] with error:[SSL certificate problem: self signed certificate in certificate chain]

### ISSUE THREAD

**Issue by m3Lvs** [intuit/QuickBooks-V3-PHP-SDK#55]
Good day I just installed the library on laravel using composer and deployed it on my https server.

I just copy pasted the example for Oauth2:
```
use QuickBooksOnline\API\DataService\DataService;

$dataService = DataService::Configure(array(
         'auth_mode' => 'oauth2',
         'ClientID' => "Q0XG3aA8zb7WQbKURFRISkt3QrWJxgWGS1jRF2l3nYtM6dOw2h",
         'ClientSecret' => "34z5qBRskA161AaKDadGAiY4ojz8TXX9RsSfu0E1",
         'accessTokenKey' => 'eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..4z4Assj4x1qt8H4DtQco6A.nmV2jTxaDMVdFWEUO16q5qhbd5aD6U-U-RYnSNywqg-HPC_3_jvwpMJU1a1S5X-PgPUy60WvVy_8p1awY7kIoFzTV4IhdFLrZpYtBUGCjcsvjxWeOSgP6oCayBEmCv7zzabtgB6vxU46jQqKX2IXYUGPPtyYO64hrgELFR4SKUK6boZiVnh8z19gnvsReKMmIINA3-NgC6QJqMRp6HWgzCa9RuDN9tCtrAK2dy5xmJRNSNgdv_gyg1bfdX4l4b30fLPzFk31fsTT9NTJq9PuGtdTsvUuCj7Hme6HPldD9TKYRXWU8TKrQQrQWEpdlbPr6F3rhP6IdmCv9t1XH_WzF_1IseRUoYhiTUjubig-j8gzwajIdYQTzpJQKJ92QiAEyt8k40WWg0v69hEC0w7WRBuUE-IJ50xWypqS_P28IWt1G14rovZ97soGOteSik-41g1icR2zxfNhXGq7zO7oU5B8r-ej5Pb52T0MCMktgd6y32bqwo2pcEzblL2bZs7DZ7LDx5peY4TIfGW21crTE6xjhRr7LdqB8K505pRqIOP20eaRgwtGHLZ3bdBt1_negw2AGjc409BM0nLzzmODxr3yo-YdGwkcOjm5QgbGAsrnpoSo9tSpxPHoN0vMRneRdsKCd6CZG5M1OIOMuj7spkm442tvwiAMCx2Fh-STG6fMnhOq7l_f8NW_3kscxtF2.obQxJKjPfi1KlaQQ_OUoNg',
         'refreshTokenKey' => "L011509163184Q0K7DT40SVXhJXAfyoj6B6EbSr3Ty64yVvF5A",
         'QBORealmID' => "123145862616089",
         'baseUrl' => "https://sandbox-quickbooks.api.intuit.com"
        ));
        $dataService->setMinorVersion("9");
        $dataService->disableLog();

        $CompanyInfo = $dataService->getCompanyInfo();
        $error = $dataService->getLastError();
        if ($error != null) {
            echo "The Status code is: " . $error->getHttpStatusCode() . "\n";
            echo "The Helper message is: " . $error->getOAuthHelperError() . "\n";
            echo "The Response message is: " . $error->getResponseBody() . "\n";
            echo "The Intuit Helper message is: IntuitErrorType:{" . $error->getIntuitErrorType() . "} IntuitErrorCode:{" . $error->getIntuitErrorCode() . "} IntuitErrorMessage:{" . $error->getIntuitErrorMessage() . "} IntuitErrorDetail:{" . $error->getIntuitErrorDetail() . "}";
        } 

```

I just also installed SSL on my server too..

how do I fix this please.

**Comment by josephmancuso** [comment]
@m3Lvs for some reason this isn't in the documentation. Took me a whole day to figure this out.

go into your vendor folder and comment out this line:

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/Core/HttpClients/CurlHttpClient.php#L107

what this is doing is getting the ca certificate from that directory. commenting it out will get the ca cert from wherever the server specified it (wherever it is in your php.ini file) 

note that this is what i did and it works but its a bad work around since whenever you run any major composer command, its going to uncomment out that line. I recommend trying to put the ca cert wherever this package is trying to retrieve it from (in this case `dirname(dirname(__FILE__)) . "/OAuth/OAuth2/certs/apiintuitcom.pem";`)

hope this helps. the owners of this repo might want to put this in the readme somewhere @hlu2

took me a long time to figure this out

**Comment by m3Lvs** [comment]
Hi @josephmancuso  Thank you for commenting, I just also figured out.. after searching for 2 days.. I really thought it was an SSL problem so I installed SSL on my server.. now Im getting 401 error though but I think this is better :D

**Comment by jfkhome** [comment]
Are you sure the baseURL is right?  The sandbox baseURL was the final problem I needed to solve after the above issue with certs to get connected.  In some of the example code it is outdated.  I updated the base to this "https://sandbox-quickbooks.api.intuit.com" and it worked, now I am connected and make API calls (both oauth 2 and 1)

**Comment by m3Lvs** [comment]
hello @jfkhome  nice to hear from you, yep.. I used the https://sandbox-quickbooks.api.intuit.com.. im currently figuring out the way to create accesstokenkey and accesstokensecret, did you used the example  OAuth2PHPExample.php to do so?

**Comment by m3Lvs** [comment]
would you mid to share your code @jfkhome  :) Im always getting an error whenever redirected to https://appcenter.intuit.com/connect/oauth2 though

**Comment by josephmancuso** [comment]
@m3Lvs are you getting this error: `Fatal error: Uncaught QuickBooksOnline\API\Exception\SdkException: [0]: Http Status Code:[401] Http Response Body are null or Empty. thrown in C:\Users\idman\Desktop\manager\vendor\quickbooks\v3-php-sdk\src\Core\HttpClients\IntuitResponse.php on line 26` ?

**Comment by jfkhome** [comment]
Hi

Already deleted the sample app.  Things that caught me:  need to use Ngrok not local host (see readme), need to make sure that you are using a new developer account on Intuit (your old account is oauth 1 and won’t be able to migrate until a future release).  Need to make sure that your new developer account has your ngrok address (there is a place for it below your keys) – they change every time you run it unless you upgrade to ngrok paid which I did.

Then when you make calls, the call should not have an access Secret.  This is replaced by the refresh token.  See createCustomer example in SDK

**Comment by jfkhome** [comment]
Hi

I did.  There has been a recent update to fix the cert issue (similar to SDK), so it works as long as you pull down a fresh copy and use the cacert.

Some of the sample code on the webpage for how to do API calls with oauth2 still show the oauth1 parameters.    I think createCustomers in the _sample file of the SDK is right though.

**Comment by m3Lvs** [comment]
hi @josephmancuso  yes I have the same error..  

```
(1/1) SdkExceptionHttp Status Code:[401] Http Response Body are null or Empty.
--
in IntuitResponse.php (line 26)
at IntuitResponse->__construct('HTTP/1.1 401 Unauthorized Server: nginx Date: Thu, 03 Aug 2017 15:13:10 GMT Content-Type: text/plain Content-Length: 0 Connection: close intuit_tid: ff30922a-431a-a3d3-3fe1-d33a4f3c9d49 WWW-Authenticate: Bearer realm="Intuit", error="invalid_token" ', '', 401)in CurlHttpClient.php (line 85)

```
did you manage to fix it?

**Comment by josephmancuso** [comment]
@m3Lvs yeah your access token expired. put in a new access token. the access token expires every hour. For some reason this library doesn't handle / account for that.

**Comment by m3Lvs** [comment]
@josephmancuso  thanks for the link man..  where did you get the key you add on refresh token field.. I only have  "Authorization Code" ( it refers to access token right?)
![image](https://user-images.githubusercontent.com/5618660/28934816-e5d4e3e6-78b4-11e7-981c-342a9d789f0d.png)

**Comment by hlu2** [comment]
@all

Sorry, I didn't think about the case for using the root Certificate from the Server. I will update the code with it accordingly. Please see the next release.

Best,
Hao

**Comment by josephmancuso** [comment]
@m3Lvs hm very weird. mine just shows up as i go through steps 1 and 2. Make sue you read the small text inside the number 1 step.

@hlu2 hey man is there any class that retrieves an access token using the refresh token?

**Comment by m3Lvs** [comment]
@josephmancuso  got it now..  I just need to click 'get token' button :D I thought I need to proceed to step 3, got me confused for a while.. anyways.. I think we are on the same page now.. needs to automate refresh token so that the user wont need to go on the steps everytime.. 

is this possible @hlu2  ? if so.. can you please point out where to start? thanks!

**Comment by hlu2** [comment]
@m3Lvs 
@josephmancuso 
It will be available next Monday.

Hao

**Comment by m3Lvs** [comment]
@josephmancuso  Hi.. I have found a sample code on https://github.com/IntuitDeveloper/OAuth2_PHP this sample has a generateAccessToken Functionality and openID too..  im just wondering if this is part of this SDK since its on the same account as this one..

but the thing is you need to add url on the quickbooks account as well.. 
like "https://mytestserver.com/test/OAuth2PHPExample.php" and
https://mytestserver.com/test/OAuthOpenIDExample.php if your using openID

**Comment by josephmancuso** [comment]
@m3Lvs oh awesome. I'll deff take a look into it! Lets keep in touch!

**Comment by m3Lvs** [comment]
Hi @hlu2  could you also consider on extending access_token validity please, just like in OAuth 1.0a where it lasts for 6 months.. I need to send invoice to non-qb user .. or I am referring to other function? Thanks for clarifying

**Comment by hlu2** [comment]
@all
A new function for refresh token is available. Also, I have updated the cacert on the PHP SDK. Let me know if you have any other issues.

@m3Lvs 
We are working on extending the OAuth 2 Access Token validity AFTER you refreshed it each time. However, it is still under discussion, no details yet. I will post it when it is coming out.

Thanks
Hao
