### ISSUE TITLE
revoke access method?

### ISSUE THREAD

**Issue by jfkhome** [intuit/QuickBooks-V3-PHP-SDK#60]
Hi

I am having a hard time locating the OAuth2PlatformClient class with revokeToken() mentioned in the documentation as the proper way to disconnect an Oauth2 connection.  Am I missing something?  Any help appreciated.  

Documentation:

"To revoke the access or refresh tokens and invalidate access, use the revokeToken() method in the OAuth2PlatformClient class. The following example revokes the Refresh token:

//Revoke the token
$client->revokeOAuth2AccessTokens($accessToken, $refreshToken);

- from:  https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0209_php/0020_authorization

**Comment by hlu2** [comment]
hi @jfkhome 
It is a documentation error. We don't have "revoke" tokens in the SDK. Since the lifetime for OAuth2 Access Token is only 1 hour, there is really no need to revoke the Access Token.

**Comment by jfkhome** [comment]
Thanks Hao.  So the technical requirements for launching an app will be revised as well I assume?

I was thinking that the user might want the ability to revoke the refresh token since it is good for longer.
________________________________

**Comment by hlu2** [comment]
@jfkhome 
You have a point. I will add both methods in the next release.

Thanks
Hao

**Comment by jfkhome** [comment]
Thanks appreciate it

**Comment by hlu2** [comment]
Now it is available by calling: revokeToken($accessTokenOrRefreshToken)
