### ISSUE TITLE
JSON Decoding Issue for Non-TaxSerivce API endpoint

### ISSUE THREAD

**Issue by hlu2** [intuit/QuickBooks-V3-PHP-SDK#61]
On DataService.php file, Line 588:
```
  $this->verifyOperationAccess($entity, __FUNCTION__);
        if ($this->isJsonOnly($entity)) {
            $this->forceJsonSerializers();
        }
```
Once Json is used, it never switch back to XML. Causing some issue for later entities. 
Will fixed in next release.

Thanks
Hao

**Comment by bricehartmann** [comment]
@hlu2 I encountered this as well. You can call `useXml()` on your `$dataService` to switch back to XML serializers
