### ISSUE TITLE
No method for grabbing access token from authorization code!

### ISSUE THREAD

**Issue by JGCore** [intuit/QuickBooks-V3-PHP-SDK#62]
I'm surprised this is missing considering you cant access the API without this step.

How are you supposed to exchange the authorization code for the access token?

There is a method for REFRESHING an existing code, which is nice, but the SDK is completely silent on the issue of grabbing the token in the first place.

Consider the following methods:

```
    public function refreshToken(){
       $theAccessToken = $this->getAccessToken();
       $refreshToken =$theAccessToken->getRefreshToken();
       $refreshTokenEndpoint = CoreConstants::OAUTH2_TOKEN_ENDPOINT_URL;
       $http_header = $this->constructRefreshTokenHeader();
       $requestBody = $this->constructRefreshTokenBody($refreshToken);
       $intuitResponse = $this->curlHttpClient->makeAPICall($refreshTokenEndpoint, CoreConstants::HTTP_POST, $http_header, $requestBody, null, true);
       $this->closeConnection();
       $faultHandler = $intuitResponse->getFaultHandler();
       if(isset($faultHandler)) {
             $this->faultHandler = $faultHandler;
             return null;
       }else{
          $this->accessToken = $this->parseNewAccessTokenFromResponse($intuitResponse->getBody());
          return $this->getAccessToken();
       }
    }
```

This uses the following method to build the request body:

```
    private function constructRefreshTokenBody($refresh_token){
        $parameters = array(
          'grant_type' => CoreConstants::OAUTH2_REFRESH_GRANTYPE,
          'refresh_token' => $refresh_token
        );
        return http_build_query($parameters);
    }
```

As you can see the grant_type is set to 'refresh_token' via the OAUTH2_REFRESH_GRANTYPE constant.

According to the documentation, the following body is required to exchange the authorization code for the access token:

```
POST https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer HTTP/1.1
Accept: application/json
Authorization: Basic UTM0dVBvRDIwanp2OUdxNXE1dmlMemppcTlwM1d2
    NzRUdDNReGkwZVNTTDhFRWwxb0g6VEh0WEJlR3dheEtZSlVNaFhzeGxma1l
    XaFg3ZlFlRzFtN2szTFRwbw==
Content-Type: application/x-www-form-urlencoded
Host: oauth.platform.intuit.com
Body: grant_type=authorization_code&
code=L3114709614564VSU8JSEiPkXx1xhV8D9mv4xbv6sZJycibMUI&
redirect_uri=https://www.mydemoapp.com/oauth-redirect
```

So what gives? Why is the PHP SDK silent on such a crucial step? Am I supposed to manually implement this singular call while the rest is handled by the SDK? If so why, because that just feels kinda gross.

If you want, I can just implement it and submit a pull request, but I don't want to go through the trouble if it will be rejected.

**Comment by jfkhome** [comment]
Hi There

The SDK deals mainly with data calls not establishing the oAuth2 token.  You can get the code for establishing the token here:  https://github.com/IntuitDeveloper/OAuth2_PHP

Note that once you get this done, an update is pending for the SDK to fix some people having issues with the SSL certifictes.

**Comment by jfkhome** [comment]
looks like they fixed the cert issue in the SDK so please ignore my last sentence

**Comment by hlu2** [comment]
@JGCore 
Hi JG, the previous way of getting access Token from Authorization Code is not very clear to some developers(as you can see from our documentation, it is a little confused), so I removed the code and revised it right now. It will be out on the next release. I appreciate you pointing it out, that is the attitude we are looking from our PHP developers!

**Comment by ajoudeh** [comment]
Any updates regarding to this issue?

**Comment by hlu2** [comment]
@ajoudeh 
There will be a big release by the end of this month. Please expect see all OAuth 2 changes and the other changes on that release.

**Comment by hlu2** [comment]
See documentation.
