### ISSUE TITLE
JSON Serialization on zero value keys

### ISSUE THREAD

**Issue by vfranchi** [intuit/QuickBooks-V3-PHP-SDK#64]
On JsonObjectSerializer.php line 189, array_filter is called to remove any null properties from the array. This gives an error when trying to add a new TaxService with a TaxRateValue = 0 (zero).

The property is removed from the object and Quickbooks throws an error:
"Error":[{"Message":"Required param missing, need to supply the required value for the API","Detail":"Required parameter TaxRateValue is missing in the request","code":"2020","element":"TaxService.TaxCode"}]

**Comment by vfranchi** [comment]
A suggestion a made in my code:

    /**
     * Custom filter for array_filter
     * Return true if value is not NULL or an empty string
     */
    public function customFilter($val)
    {
        return !($val === null || $val === "");
    }
    
    /**
     * The input will always be an asscoiate array
     * So we will judge based on this two situration
     */
    private function removeNullProperties($val){
        $filterArray = array_filter($val, array(&$this, "customFilter"));
        $returned = array();
        foreach($filterArray as $k => $v){
          if(is_array($v)){
            if(FacadeHelper::isRecurrsiveArray($v)){
              $list = array();
              foreach($v as $kk => $vv){
                $list[] = array_filter($vv, array(&$this, "customFilter"));
              }
              $returned[$k] = $list;
            }
          }else{
            $returned[$k] = $v;
          }
        }
        return $returned;
    }

**Comment by hlu2** [comment]
@vfranchi 
Nice Catch! I will update it in the code! Thanks!
