### ISSUE TITLE
count(*) queries returning NULL

### ISSUE THREAD

**Issue by curiousfreelancer** [intuit/QuickBooks-V3-PHP-SDK#65]
I still have this problem with latest version of PHP SDK. And doing the solution suggested in https://bitbucket.org/snippets/kuzman05/B8Lpk to return "totalCount" seem to break the queries other than count(*). Is there any standard solution available because it looked like this issue was fixed in older version of SDK (2.5.*) under the issue SDK-326.

Please advise. @hlu2

**Comment by Baldrs** [comment]
Yea that's because count is returned as attribute of QueryResponse, but DataService calls don't actually parse QueryResponse, but it's body, which is empty. It must be a bug.

**Comment by thewunder** [comment]
Also running into this...  Without support for count queries, there is effectively no way to actually page

**Comment by lordlele** [comment]
I've resolved changing in file:

```
Core/Http/Serialization/XmlObjectSerializer.php
```

The piece of code

```
$responseXmlObj = simplexml_load_string($message);
```

with 

```
$responseXmlObj = simplexml_load_string($message);
        // handle count(*) style queries
        if (isset($responseXmlObj->attributes()["totalCount"])) {
            $totalCount = (array)$responseXmlObj;
            $totalCount = intval(($responseXmlObj->attributes()["totalCount"]));
            return $totalCount;
        }
```

Hope that help!

**Comment by hlu2** [comment]
@lordlele 
I have merged the code. The count (*) should work now. Thanks for pointing out!
