### ISSUE TITLE
CDC ChangedSince is unpredictable based on local time

### ISSUE THREAD

**Issue by challgren** [intuit/QuickBooks-V3-PHP-SDK#69]
When setting the ChangedSince time for the $dataService->CDC() call. The time sent to the server is expected in ISO 8601 format it would best be wise to send the correct timestamp. 

On line 891 of DataService we should change it from `$formattedChangedSince = date("Y-m-d\TH:m:s", $this->verifyChangedSince($changedSince));` to `$formattedChangedSince = date("Y-m-d\TH:m:sP", $this->verifyChangedSince($changedSince));` or `$formattedChangedSince = date("c", $this->verifyChangedSince($changedSince));`

**Comment by hlu2** [comment]
@challgren 
I didn't realize it. Let me check and I will change it accordingly.

**Comment by hlu2** [comment]
Fixed.

**Comment by challgren** [comment]
Ok then the docs need to clearly state send a PST timestamp. I messed around with this for almost 3 hours trying to get the timestamps figured out as one would assume a timestamp without a timezone is UTC time and not PST time. But this is not the case because UTC sent timestamps would fail.
