### ISSUE TITLE
Unsupported OperationOperation CREATE CATEGORY is not supported.

### ISSUE THREAD

**Issue by furqantechverx** [intuit/QuickBooks-V3-PHP-SDK#70]
I am trying to create item with category using API V3 SDK . Can you please guide how its work. here is my code .
$Item = Item::create([
"Name" => "Cedar",
"Type"=>"Category"
]);

**Comment by hlu2** [comment]
@furqantechverx 

If you look at our documentation:
https://developer.intuit.com/docs/api/accounting/item

You can see there is no type "Category" available, the type that we support for API is:
Inventory, Group, Service and NonInventory.

Try use Group and it should work

**Comment by furqantechverx** [comment]
Check out this query : 

SAMPLE QUERY
select * from Item where Type='Category'
And this response 
SAMPLE RESPONSE
{
    "Item":
    {
        "Name":"Organic Trees",
        "Active":true,
        "FullyQualifiedName":"Organic Trees",
        "Type":"Category",
        "domain":"QBO",
        "sparse":false,
        "Id":"29",
        "SyncToken":"2",
        "MetaData":
        {
            "CreateTime":"2015-10-06T08:50:34-07:00",
            "LastUpdatedTime":"2015-10-07T12:38:03-07:00"
        }
    },
    "time":"2015-10-07T12:40:29.199-07:00"
}

**Comment by furqantechverx** [comment]
And check out this error 
Uncaught exception 'Exception' with message 'Trying to construct IPPReferenceType based on Array. The array should contain at most two fields. name and value' 

$Item = Item::create([
        "Name"=> "Deluxe Fountain",
        "Sku"=> "234",
        "Active"=> true,
        "FullyQualifiedName"=> "Deluxe Fountain",
        "Taxable"=> false,
        "UnitPrice"=> 0,
        "Type"=> "Group",
        "PurchaseCost"=> 0,
        "TrackQtyOnHand"=> false,
        "PrintGroupedItems"=> true,
        "ItemGroupDetail"=> [
            "ItemGroupLine"=> [
            [
                "ItemRef"=> [
                    "value"=> "11",
                    "name"=> "Pump",
                    "type"=> "Inventory"
                ],
                "Qty"=> 1
            ], [
                "ItemRef"=> [
                    "value"=> "5",
                    "name"=> "Rock Fountain",
                    "type"=> "Inventory"
                ],
                "Qty"=> 1
            ], [
                "ItemRef"=> [
                    "value"=> "8",
                    "name"=> "Lighting",
                    "type"=> "Service"
                ],
                "Qty"=> 2
            ],[
                "ItemRef"=> [
                    "value"=> "7",
                    "name"=> "Installation",
                    "type"=> "Service"
                ],
                "Qty"=> 4
            ],
            ],
            ],
        "domain"=> "QBO",
        "sparse"=> false,
        "Id"=> "49",
        "SyncToken"=> "1",
]);

**Comment by furqantechverx** [comment]
if this type not exit why api docs query the type with category 
![screenshot from 2017-09-13 12 37 00](https://user-images.githubusercontent.com/31100689/30365176-5c554c32-9880-11e7-94e5-c1b7cf2a0b22.png)

**Comment by furqantechverx** [comment]
And check this Response with type of category  in Api Doc.
![screenshot from 2017-09-13 15 32 53](https://user-images.githubusercontent.com/31100689/30372899-deb60f0a-9898-11e7-952b-65bca8d51e0c.png)

**Comment by hlu2** [comment]
@furqantechverx 
The item reference:
ItemRef"=> [
"value"=> "5",
"name"=> "Rock Fountain",
"type"=> "Inventory"
],

Only have two fields. Value and Name. The type is not something you should pass.
