### ISSUE TITLE
Last Error not cleared

### ISSUE THREAD

**Issue by Baldrs** [intuit/QuickBooks-V3-PHP-SDK#72]
So even after successful call, last error from prev call is still there. For example you've got 401, then tried again, got expected NULL for example for empty results set, BUT getLastError still reports 401, and it had reported NULL, not FALSE as per docs, so how do you distinguish between EXPECTED NULL and ERROR?

**Comment by Baldrs** [comment]
You should consider refactoring this to exception. 

Even you still use that pattern, consider following it as json_ functions do

```
>>> json_decode("garbage")           
=> null                      
>>> json_last_error_msg()    
=> "Syntax error"            
>>> json_decode("{}")                
=> {#837}                    
>>> json_last_error_msg()    
=> "No error"                
>>> json_last_error()
=> 0
```
See how does it return 0 when there's no error? So the point is, you should clear your lastError before each call, not store it forever

**Comment by hlu2** [comment]
@Baldrs Thanks for pointing it out, it should be false instead of Null.

**Comment by hlu2** [comment]
Fixed.
