### ISSUE TITLE
Refreshing Oauth2 Token fails if accessToken is Valid but expired

### ISSUE THREAD

**Issue by thewunder** [intuit/QuickBooks-V3-PHP-SDK#79]
Setting up with this configuration calling refreshToken() works:
  auth_mode: oauth2
  oath_scope: com.intuit.quickbooks.accounting
  ClientID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  ClientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  accessTokenKey: true
  refreshTokenKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  QBORealmID: 193514608xxxxx
  baseUrl: Development

But with a valid but expired token refreshing gives 400 invalid_grant:
  auth_mode: oauth2
  oath_scope: com.intuit.quickbooks.accounting
  ClientID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  ClientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  accessTokenKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx....
  refreshTokenKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  QBORealmID: 193514608xxxxx
  baseUrl: Development

Where as omitting the access token causes an exception :
Uncaught QuickBooksOnline\API\Exception\SdkException: [0]: 'accessTokenKey' must be provided in OAuth2

This is pretty inconsistent.

**Comment by hlu2** [comment]
@thewunder This part has changed in the code. It is part of the big release on the end of the month.

**Comment by hlu2** [comment]
Now it is no longer a required field. See documentation for more details.
