### ISSUE TITLE
PHP SDK Error on Mac os

### ISSUE THREAD

**Issue by Antonystefano** [intuit/QuickBooks-V3-PHP-SDK#8]
The Status code is: 400 The Helper message is: Invalid auth/bad request (got a 400, expected HTTP/1.1 20X or a redirect) 
The Response message is: {"Fault":{"Error":[{"Message":"Error parsing query","Detail":"
QueryParserError: The query provided was empty","code":"4000"}],"type":"ValidationFault"},"time":"2017-04-18T06:05:13.189-07:00"}

**Comment by Antonystefano** [comment]
`require "../QuickBooks/vendor/autoload.php";

use QuickBooksOnline\API\DataService\DataService;
use QuickBooksOnline\API\Core\Http\Serialization\XmlObjectSerializer;
use QuickBooksOnline\API\Data\IPPCustomer;


$dataService = DataService::Configure(array(
                'auth_mode' => 'oauth1',
                'consumerKey' => "qyprdDiyFCasbGj8Is21kaMaqV8JIz",
                'consumerSecret' => "ScST7k1LWv6x2J3umzWxHR9iDg9F0XK4m6sG0R7J",
                'accessTokenKey' => "qyprdppvT3SNruBHA6gvgsjw9Ey9jFld0bELHdtYQn5ZmcPD",
                'accessTokenSecret' => "8wDIMG5l3vAnNluC4kP2kDpBnmcp6ZGaibZ1iK4O",
                'QBORealmID' => "123145808150389",
                'baseUrl' => "https://quickbooks.api.intuit.com/v3/company/"
));

if (!$dataService)
	exit("Problem while initializing DataService.\n");

$allAccounts = $dataService->Query("SELECT * FROM Account");`

**Comment by Antonystefano** [comment]
I don't understand what did I make mistake?
I tried to fix it in many times but not success yet.
Please help me.
Thank you.

**Comment by hlu2** [comment]
I believe there is an error so that the Query string is not constructed properly. Can you post your error message?

**Comment by Antonystefano** [comment]
Thank you for your response.
This is the error message.
The Status code is: 400 The Helper message is: Invalid auth/bad request (got a 400, expected HTTP/1.1 20X or a redirect)
The Response message is: {"Fault":{"Error":[{"Message":"Error parsing query","Detail":"
QueryParserError: The query provided was empty","code":"4000"}],"type":"ValidationFault"},"time":"2017-04-18T06:05:13.189-07:00"}

**Comment by hlu2** [comment]
Hi Antony,
Please Update the Library to the v3.0.2 version. 
For Mac OS, since the Log location was default to /tmp/IdsLogs directory, Mac OS may not allow PHP SDK to access the root. 
Use :
$dataService->setLogLocation("/Folders/You/Want/To/Store");
to re-config for the log directory.
chmod 777 to the new directory to see if it solve the problem.

Thanks
Hao

**Comment by Antonystefano** [comment]
Hi. Hao Lu.
Thank you very much for your response.
Would you help me one more thing about APIs?
Regards.
Yuki.

**Comment by hlu2** [comment]
Hi Antony,

You can make a charge but I am not sure about the context of "delayed charge". Can you provide a use case for it?

Hao

**Comment by Antonystefano** [comment]
Hi Hao Lu.

Thank you for responding.

I am programming with QBO APIs.

There are SalesReceipt, Invoice, Estimate, TimeActivity and etc.

But I can not find some APIs for Delayed Charge.

If there is no APIs for Delayed Charge, what is the best way to create or
simulate the API?

**Comment by hlu2** [comment]
Hi Antony,

Sorry I forget to reply your comment. Somehow I thought I did it already.
Currently QuickBooks Online API do not support Delayed Charge, so unfortunately I can't provide it on the PHP SDK. I have put it as a feature request in our jira system. One of our managers will evaluate it and decide if it is a feature we can implement.

Thanks
Hao
