### ISSUE TITLE
Sending an Invoice

### ISSUE THREAD

**Issue by zackkrida** [intuit/QuickBooks-V3-PHP-SDK#81]
How do I send an invoice to a customer (As specified here: https://developer.intuit.com/docs/api/accounting/invoice)?

Seems like a significant omission. Is there any way to do so via the `IPP` objects?

**Comment by zackkrida** [comment]
So it appears i can do `DataService->SendEmail($invoice)`. I will try this. Could use more documentation!

**Comment by grawlins** [comment]
Thanks for pointing this out. I will put together a page on invoicing with PHP. Let me know if there are any other issues you have that you think need clarification.

**Comment by UVLabs** [comment]
@grawlins it looks like you never got around to it?
