### ISSUE TITLE
Sometimes state, city, and zip are missing from response

### ISSUE THREAD

**Issue by JGCore** [intuit/QuickBooks-V3-PHP-SDK#85]
I sent the following query:

select * from Invoice

In the results, sometimes billing and shipping addresses are missing their states, cities, and zips.

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                  $qbAddress                                  │
└──────────────────────────────────────────────────────────────────────────────┘
QuickBooksOnline\API\Data\IPPPhysicalAddress (16) (
    public Id -> string (2) "69"
    public Line1 -> string (16) "35 Van Gordon St"
    public Line2 -> string (18) "Lakewood, CO 80228"
    public Line3 -> NULL
    public Line4 -> NULL
    public Line5 -> NULL
    public City -> NULL
    public Country -> NULL
    public CountryCode -> NULL
    public CountrySubDivisionCode -> NULL
    public PostalCode -> NULL
    public PostalCodeSuffix -> NULL
    public Lat -> NULL
    public Long -> NULL
    public Tag -> NULL
    public Note -> NULL
)
```

This is causing our system to insert null for these values, and then on EXPORT, the QB values are also set to null resulting in a loss of information. I need this information to be present every single time for my sync to work right, unless anyone has a better way to do this?

**Comment by hlu2** [comment]
@JGCore 
It is not a SDK issue, it is a QBO issue.
For the first time when you create an Invoice, it will show the state, city and zip information properly. However, once the invoice is updated, it will return the information on the SAME Line, as your example shows. We are working to fix this one on our backend, it is in progress.

**Comment by mattpramschufer** [comment]
I have the same issue...
