### ISSUE TITLE
Closing PHP tags in 4.0.0

### ISSUE THREAD

**Issue by javabudd** [intuit/QuickBooks-V3-PHP-SDK#92]
[This](https://github.com/intuit/QuickBooks-V3-PHP-SDK/commit/45e1b18efc69ed6cab2ff88b00dc3966832fd958) commit has many new files with closing PHP tags. 

There are several reasons why you should not due this. Please consider following PSR-2 guidelines.

**Comment by hlu2** [comment]
@javabudd 
It has been removed.
