### ISSUE TITLE
JSON and XML response in API call

### ISSUE THREAD

**Issue by lordlele** [intuit/QuickBooks-V3-PHP-SDK#95]
Hi,
I'm trying to send an Invoice (with customer and all other things) to QuickBooks, however I get this error:

```
{"Fault":{"Error":[{"Message":"Invalid Reference Id","Detail":"Invalid Reference Id : Something you're trying to use has been made inactive. Check the fields with accounts, customers, items, vendors or employees.","code":"2500","element":""}],"type":"ValidationFault"},"time":"2017-11-23T08:05:18.937-08:00"}
```
The problem is not the error (maybe a I need to activate something... what is it I'm still questioning...), but it's NOT an XML string and I get this error:

```
PHP Error[2]: DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1
    in file .../quickbooks/intuit/src/Core/HttpClients/SyncRestHandler.php at line 308
```

How I can enforce XML response even for errors? Or ther's another workaround?

**Comment by hlu2** [comment]
@lordlele 
The JSON serializer I need to rewrite it. But that is a different story.
When you specify the Content-Type, always set to XML for now. It should return XML response. If it returns JSON, it will be a Server error.

**Comment by prsheth** [comment]
It seems response in already in XML so just comment out  loadXML() function call. This worked for me PHP v3 SDK 4.0.0

**Comment by drubage** [comment]
We are able to get an invoice like this just fine but it still throws the above error:

```
    $query = "SELECT * FROM Invoice WHERE Id = '{$invoice}'";
    $invoices = $dataService->Query($query);
```

Is there a fix aside from turning off PHP warnings?

**Comment by hlu2** [comment]
@lordlele This one will be fixed on the API side. The API will not send any HTML response in the future.
