### ISSUE TITLE
0 value not being passed into XML

### ISSUE THREAD

**Issue by dsbcourtney** [intuit/QuickBooks-V3-PHP-SDK#97]
I believe there is a bug with the API which is stopping 0 values being parsed into the XML. For example when I try to update an item using the following code:
`
$item = new QuickBooksOnline\API\Data\IPPItem;
$item->Id = 21;
$item->SyncToken = 0;
$item->Name = 'Test Name';
$item->Description = 'Test Description'
$item->UnitPrice = '9.99';
$item->PurchaseDesc = 'Test Description';
$item->PurchaseCost = '4.99';
$item->Type = 'NonInventory';
$item->SalesTaxCodeRef = 6;
$item->PurchaseTaxCodeRef = 6;
$item->Taxable = true;
$item->IncomeAccountRef = 2;
$item->ExpenseAccountRef = 2;

$resultingItemObj = $dataService->Add($item);
`
It creates the following XML:

`
<?xml version="1.0" encoding="UTF-8"?>
<ns0:Item xmlns:ns0="http://schema.intuit.com/finance/v3">
  <ns0:Id>21</ns0:Id>
  <ns0:Name>Test Name</ns0:Name>
  <ns0:Description>Test Description</ns0:Description>
  <ns0:Taxable/>
  <ns0:UnitPrice>9.99</ns0:UnitPrice>
  <ns0:Type>NonInventory</ns0:Type>
  <ns0:IncomeAccountRef>2</ns0:IncomeAccountRef>
  <ns0:PurchaseDesc>Test Description</ns0:PurchaseDesc>
  <ns0:PurchaseCost>4.99</ns0:PurchaseCost>
  <ns0:ExpenseAccountRef>2</ns0:ExpenseAccountRef>
  <ns0:SalesTaxCodeRef>6</ns0:SalesTaxCodeRef>
  <ns0:PurchaseTaxCodeRef>6</ns0:PurchaseTaxCodeRef>
</ns0:Item>
`
SyncToken is not included meaning that I get a "Stale Object Error"

If I add SyncToken to the XML and process it using the API Explorer it works fine. I am using 4.0.1.

Thanks

**Comment by hlu2** [comment]
@dsbcourtney I cannot reproduce the same error, can you provide the complete code so I can try? Also, in your code, the $item->Description = 'Test Description' is missing ";" at the end.

**Comment by hlu2** [comment]
@dsbcourtney 
It is the XML parser. The SyncToken is Type "String" in the Object, so if you provide:
$item->SyncToken = "0";
it will work.
the
$item->SyncToken = 0;
cannot be worked correctly because int(0) cannot be matched correctly to string(0). It has to be a string.

I would not suggest using the Facade class to do it, like:
$Item = Item::create([
      "Id" => 27,
      "SyncToken" => 1,
      "Name" => "1111Office Sudfsfasdfpplies",
      "Description" => "This is the sales description.",
      "Active" => true,
      "FullyQualifiedName" => "Office Supplies",
      "Taxable" => true,
      "UnitPrice" => 25,
      "Type" => "Inventory",
      "IncomeAccountRef"=> [
        "value"=> 66,
        "name" => "Landscaping Services:Job Materials:Fountains and Garden Lighting"
      ],
      "PurchaseDesc"=> "This is the purchasing description.",
      "PurchaseCost"=> 35,
      "ExpenseAccountRef"=> [
        "value"=> 67,
        "name"=> "Cost of Goods Sold"
      ],
      "AssetAccountRef"=> [
        "value"=> 65,
        "name"=> "Inventory Asset"
      ],
      "TrackQtyOnHand" => true,
      "QtyOnHand"=> 100,
      "InvStartDate"=> $dateTime
]);

When I map the key to values, I will convert it properly. However, it won't happen when you manually assign the value. The library we are using "XSD2PHP" is pretty old. I need to change it, just didn't find a good candidate.

**Comment by dsbcourtney** [comment]
Thank you. I did think that might be the reason and in the end just used:

`$item->SyncToken = strval($SyncToken);`

which has worked ok.

Thanks for your help.
