### ISSUE TITLE
Get the last error

### ISSUE THREAD

**Issue by ThomasNixon** [intuit/QuickBooks-V3-PHP-SDK#98]
https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/3d2147286b14e5b8d43848974a91a7099aa792a0/src/_Samples/CustomerUpdate.php#L43

Need to get the last error
`$error = $dataService->getLastError();`

**Comment by hlu2** [comment]
@ThomasNixon I forget to update the Sample, will do.
