### ISSUE TITLE
CDC not working as it should

### ISSUE THREAD

**Issue by dsbcourtney** [intuit/QuickBooks-V3-PHP-SDK#99]
I don't believe the CDC is working as it should. From using the sample code I am getting strange responses especially when only 1 result per entity is returned from the API. I just get an integer response.

More than 1 and I do get entity objects returned although they don't tell me a status.

**Comment by hlu2** [comment]
@dsbcourtney I will take a look. Can you provide your code snippet?

**Comment by dsbcourtney** [comment]
Yes of course, I am using this:

` $entityList = array('Item','Customer','Vendor','Invoice','PurchaseOrder','Estimate', 'SalesReceipt');
  $query = $dataService->CDC($entityList, '2017-12-04T00:00:00-08:00');

  var_dump($query);
`

When there is more than one result per entity to return it works ok but when there is only the one result to return per entity it just returns an int.
